substitutions:
  project_name: rtclauss.bluetoothproxy
  project_version: "2.0.0"
  fallback_ap_password: "w6bg4m9c9rY7"
  wifi_power_save_mode: NONE

esphome:
  name: ${device_name}
  project:
    name: ${project_name}
    version: ${project_version}

wifi:
  ssid: !secret wifi_ap
  password: !secret wifi_password
  min_auth_mode: WPA2
  power_save_mode: ${wifi_power_save_mode}
  ap:
    ssid: ${fallback_ap_name}
    password: ${fallback_ap_password}

logger:

api:

ota:
  - platform: esphome
    password: ${ota_password}

improv_serial:

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

binary_sensor:
  - platform: status
    name: "${device_label} Status"
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: "${device_label} Uptime"
    type: seconds
    update_interval: 60s
    entity_category: diagnostic
  - platform: wifi_signal
    name: "${device_label} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: version
    name: "${device_label} ESPHome Version"
    hide_timestamp: true
    hide_hash: true
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${device_label} IP Address"
      entity_category: diagnostic
    mac_address:
      name: "${device_label} MAC Address"
      entity_category: diagnostic
    ssid:
      name: "${device_label} Connected SSID"
      entity_category: diagnostic
