esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

xiaomi_ble:
