language: python
python:
  - "3.8"
dist: bionic
git:
    submodules: false
before_install:
  - mv travis_secrets.yaml secrets.yaml
  ### Remove stream component
  # - sed -i 's/^stream:/#stream:/g' configuration.yaml
  - sudo apt-get update
  #- sudo apt-get install -y ffmpeg libudev-dev autoconf libssl-dev libxml2-dev libxslt1-dev libjpeg-dev libffi-dev zlib1g-dev
  - sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  #- sudo apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev

install:
  - pip3 install sqlalchemy
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c . --script check_config
