language: python
python:
  - "3.6"
git:
    submodules: false
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
