- id: '1662058600945'
  alias: Garbage Holiday in week
  description: ''
  use_blueprint:
    path: bruxy70/holiday_in_week.yaml
    input:
      holiday_entity: calendar.mn_holidays
      garbage_collection_entity: calendar.garbage_collection
- id: '1662058764387'
  alias: WM Holiday in Week
  description: ''
  use_blueprint:
    path: bruxy70/holiday_in_week.yaml
    input:
      garbage_collection_entity: sensor.waste_management
      holiday_entity: calendar.mn_holidays
