- platform: template
  sensors:
    away_from_curling:
      value_template: >
        {% if
          (((as_timestamp(now()) - as_timestamp(states.sensor.twincities.last_changed))//60) > 10) and (states.sensor.twincities.state=="away_from")
          or
          (((as_timestamp(now()) - as_timestamp(states.sensor.heading_occ.last_changed))//60) > 5) and (states.sensor.heading_occ.state=="away_from")
        %} true
        {% else %}
          false
        {% endif %}
      friendly_name: 'Leaving Curling'
      entity_id: sensor.time
      device_class: moving
    test_homeward:
      value_template: >
        {% if
          (((as_timestamp(now()) - as_timestamp(states.sensor.heading_home.last_changed))//60) > 10) and (states.sensor.heading_home.state=="towards")
        %} true
        {% else %}
          false
        {% endif %}
      friendly_name: "Homeward bound"
      entity_id: sensor.time
      device_class: moving
    nest_home:
      friendly_name: 'Nest Home/Away Mode'
      device_class: presence
      value_template: "{% if is_state('states.climate.hallway_glycol.attributes.away_mode', 'on') %} false {%- else -%} true  {%- endif %}"

- platform: bayesian
  prior: 0.5
  name: Bayesian Zeke Home
  device_class: occupancy
  probability_threshold: 0.9
  observations: 
  - entity_id: device_tracker.4098ad3265d4
    prob_given_true: 0.99
    prob_given_false: 0.15
    platform: 'state'
    to_state: 'home'
  - entity_id: device_tracker.wethop
    prob_given_true: 0.9
    prob_given_false: 0.1
    platform: 'state'
    to_state: 'home'
  - entity_id: sensor.iphone_battery_state
    prob_given_true: 0.75
    prob_given_false: 0.3
    platform: 'state'
    to_state: 'Charging'
  - entity_id: binary_sensor.nest_home
    prob_given_true: 0.7
    prob_given_false: 0.4
    platform: 'state'
    to_state: 'on'
