homeassistant:
  name: The Brewery
  unit_system: imperial
  time_zone: America/Chicago
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  packages: !include_dir_named packages

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

hassio:

ffmpeg:

map:

ios:

config:

logger:
  default: warn
  #default: info
  logs:
    #homeassistant.components.device_tracker: debug
    #homeassistant.components.media_player: debug
    pytraccar: debug
    zha-quirks: debug
#  default: warn 
#  default: debug
#  logs:
#    homeassistant.components.device_tracker: debug
#    custom_components.device: debug
#    custom_components.zha_new: debug
#    custom_components.device.lumi_sensor_magnet_aq2: debug
#    custom_components.binary_sensor.zha_new: debug
#    custom_components.device.lumi_sensor_switch_aq2: debug
#    custom_components.sensor.zha_new: debug
#    custom_components.light.zha_new: debug
#    bellows: debug
#    bellows.zigbee.application: debug
#    homeassistant.components.zha: debug
#    zigpy: debug
#    homeassistant.components.zha_new: debug
#    homeassistant.custom_components.zha_new: debug
#    homeassistant.custom_components.binary_sensor.zha_new: debug
#    homeassistant.custom_components.sensor.zha_new: debug
#    homeassistant.components.sensor.zha_new: debug
#    homeassistant.components.binary_sensor.zha_new: debug
#    homeassistant.components.alarm_control_panel: debug
#    homeassistant.components.wink: debug
#    homeassistant.components.hue: debug

http:
  api_password: !secret http_password
  base_url: !secret public_url
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.1.99
    - 2602:100:602a:5df5::82c 
  ip_ban_enabled: true 
  trusted_networks:
    - 172.16.0.0/12
  login_attempts_threshold: 5

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Enables the frontend
frontend:
  javascript_version: latest

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

climate:
  platform: nest

tts:
  - platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

scene: !include scene.yaml

automation: !include automations.yaml

sensor: !include sensor.yaml

group: !include_dir_merge_named group

script: !include script.yaml

vacuum: !include vacuum.yaml

#telegram_bot:
#  platform: polling
#  api_key: !secret telegram_api_key
#  allowed_chat_ids:
#    - !secret telegram_chat_id

notify: !include notify.yaml

media_player:
  - platform: vizio
    host: 192.168.1.114
    access_token: !secret vizio_tv_token

recorder:
#  db_url: postgresql://@/hass
  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 30
  exclude:
    domains:
      - media_player
      - updater
      - sun
      - zone
      - camera
      - group
      - clients
      - persistent_notification
      - scene
      - script
      - vacuum
      - weather
    entities:
      - sensor.time
      - sensor.date
      - sensor.last_boot
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_probability_4
      - sensor.dark_sky_precip_probability_5
      - sensor.dark_sky_precip_probability_6

influxdb:
  host: !secret influx_db_host
  exclude:
    domains:
      - media_player
      - updater
      - sun
      - zone
      - automation
      - camera
      - group
      - clients
      - input_number
      - persistent_notification
      - scene
      - script
      - vacuum
      - weather
    entities:
      - sensor.time
      - sensor.date
      - sensor.last_boot

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://ide.rtclauss.org
  traccar:
    title: Traccar
    icon: mdi:car-connected
    url: https://traccar.rtclauss.org

cloud:
  alexa:
    filter:
      include_entities:
        - input_boolean.guest_mode
        - scene.reset_living_room
        - scene.bedroom_prep
        - scene.chill
      include_domains:
        - light
        - switch
      exclude_entities:
        - switch.livingroom_motion_tracking
        - switch.basement_night_mode
        - switch.livingroom_yellow_led
        - switch.basementcam_ir_led
        - switch.livingroom_motion_send_mail
        - switch.livingroom_night_mode_auto
        - switch.basementcam_ir_filter
        - switch.basement_motion_send_mail
        - switch.basement_ir_led
        - switch.basement_mjpeg_rtsp_server
        - switch.livingroom_ir_filter
        - switch.basementcam_motion_tracking
        - switch.basementcam_blue_led
        - switch.livingroom_blue_led
        - switch.hass
        - switch.basementcam_yellow_led
        - switch.basement_motion_tracking
        - switch.livingroom_mjpeg_rtsp_server
        - switch.basement_h264_rtsp_server
        - switch.livingroom_motion_detection
        - switch.basement_ir_filter
        - switch.basement_motion_detection
        - switch.basementcam_mjpeg_rtsp_server
        - switch.basement_blue_led
        - switch.basementcam_night_mode_auto
        - switch.basementcam_motion_detection
        - switch.livingroom_h264_rtsp_server
        - switch.livingroom_ir_led
        - switch.basement_yellow_led
        - switch.basement_night_mode_auto
        - switch.livingroom_motion_tracking
        - switch.basement_night_mode
        - switch.livingroom_yellow_led
        - switch.basementcam_h264_rtsp_server
        - switch.basementcam_night_mode
    entity_config:
      input_boolean.guest_mode:
        name: Guest Mode
        description: Turn on guest mode
      switch.flux:
        name: Flux
        description: Toggle f.lux in living room
      scene.reset_living_room:
        name: Reset Living Room
        description: Reset Living Room lights
      switch.deck_led_string:
        name: Deck Lights
        description: Deck LED String of lights
      
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
  - platform: darksky
    api_key: !secret darksky_api_key
    
lovelace:
  mode: yaml

cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain


#zha_new:
#  usb_path: /dev/ttyUSB1
#  database_path: /config/zigbee.db

# zha:
  # usb_path: /dev/ttyUSB1
  # database_path: /config/zigbee.db

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  
system_health:

person:

default_config:

mobile_app:

########################
# Stream
########################
stream:
