homeassistant:
  name: The Brewery
  unit_system: imperial
  time_zone: America/Chicago
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  packages: !include_dir_named packages
  external_url: !secret public_url
  internal_url: !secret public_url
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 172.16.0.0/12
        - !secret private_subnet
        - !secret iot_subnet
        - !secret ipv6_subnet

hassio:

ffmpeg:

map:

ios:

config:

logger:
  #default: warn
  default: warn
  #homeassistant.components.device_tracker: debug
  #homeassistant.components.media_player: debug
  #pytraccar: debug
  #zha-quirks: debug
#  default: warn
#  default: debug
#  logs:
#    hass_nabucasa.iot: debug
#   custom_components.circadian_lighting: debug
#   custom_components.circadian_lighting.sensor: debug
#   custom_components.circadian_lighting.switch: debug
#homeassistant.helpers: debug
#homeassistant.helpers.condition: debug
#homeassistant.components.proximity: debug
#    custom_components.device: debug
#    custom_components.zha_new: debug
#    custom_components.device.lumi_sensor_magnet_aq2: debug
#    custom_components.binary_sensor.zha_new: debug
#    custom_components.device.lumi_sensor_switch_aq2: debug
#    custom_components.sensor.zha_new: debug
#    custom_components.light.zha_new: debug
#    bellows: debug
#    bellows.zigbee.application: debug
#    homeassistant.components.zha: debug
#    zigpy: debug
#    homeassistant.components.zha_new: debug
#    homeassistant.custom_components.zha_new: debug
#    homeassistant.custom_components.binary_sensor.zha_new: debug
#    homeassistant.custom_components.sensor.zha_new: debug
#    homeassistant.components.sensor.zha_new: debug
#    homeassistant.components.binary_sensor.zha_new: debug
#    homeassistant.components.alarm_control_panel: debug
#    homeassistant.components.wink: debug
#    homeassistant.components.hue: debug
#    homeassistant.components.flux: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret fermentor_ipv4
    - !secret fermentor_ipv6
  #ip_ban_enabled: true
  #login_attempts_threshold: 5

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
#conversation:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.battery_sensor_from_attributes
      - automation.update_battery_status_group_members
      - automation.battery_persistent_notification
      - automation.battery_persistent_notification_clear
      - sensor.xiaomi_map

# Discover some devices automatically
discovery:

tts:
  - platform: google_translate
    service_name: google_say

# rtclauss - disable with move to zwave-thermostat
# nest:
#   client_id: !secret nest_client_id
#   client_secret: !secret nest_client_secret

recorder:
  #  db_url: postgresql://@/hass
  db_url: !secret recorder_db_url
  purge_keep_days: 90
  exclude:
    domains:
      - media_player
      - updater
      - sun
      - zone
      - camera
      - group
      - clients
      - persistent_notification
      - scene
      - script
      - vacuum
      - weather
    entities:
      - sensor.time
      - sensor.date
      - sensor.xiaomi_map
      - sensor.last_boot
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_probability_4
      - sensor.dark_sky_precip_probability_5
      - sensor.dark_sky_precip_probability_6

influxdb:
  host: !secret influx_db_host
  exclude:
    domains:
      - media_player
      - updater
      - zone
      - automation
      - camera
      - group
      - clients
      - input_datetime
      - input_number
      - persistent_notification
      - scene
      - script
      - vacuum
    entities:
      - sensor.time
      - sensor.date
      - sensor.last_boot
      - sensor.xiaomi_map

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# panel_custom:
#   - name: zwavegraph2
#     sidebar_title: Z-Wave Graph
#     sidebar_icon: mdi:access-point-network
#     url_path: zwave

cloud:
  alexa:
    entity_config:
      input_boolean.guest_mode:
        name: Guest Mode
        description: Turn on guest mode
      switch.flux:
        name: Flux
        description: Toggle flux in bedroom
      script.reset_bedroom:
        name: Reset Living Room
        description: Reset Living Room lights
      scene.reset_bedroom:
        name: Reset Bedroom
        description: Reset bedroom Lights
      switch.deck_led_string:
        name: Deck Lights
        description: Deck LED String of lights

lovelace:
  mode: yaml
  resources:
    # - url: /hacsfiles/custom-header/custom-header.js
    #   type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
      type: js
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/zha-network-card/zha-network-card.js
      type: js
    # - url: /hacsfiles/lovelace-card-mod/card-mod.js
    #   type: js
    - url: /hacsfiles/threedy/threedy-card.js
      type: module
    - url: /hacsfiles/gauge-card/gauge-card.js
      type: js
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: js
    - url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
      type: js
    # - url: /local/zha-network-visualization-card/zha-network-visualization-card.js
    #   type: module
    - url: /hacsfiles/firetv-card/firetv-card.js
      type: js
    - type: module
      url: /hacsfiles/flex-table-card/flex-table-card.js
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module

  dashboards:
    db-pc:
      mode: yaml
      title: Dev/PC
      icon: mdi:laptop-mac
      show_in_sidebar: false
      filename: ui-pc.yaml
      require_admin: true
    db-phone:
      mode: yaml
      title: Phone
      icon: mdi:cellphone-iphone
      show_in_sidebar: false
      filename: ui-phone.yaml
      require_admin: true
    db-tablet:
      mode: yaml
      title: iPad
      icon: mdi:tablet-ipad
      show_in_sidebar: false
      filename: ui-tablet.yaml
      require_admin: true
    db-guest:
      mode: yaml
      title: Guest
      icon: mdi:bag-checked
      show_in_sidebar: false
      filename: ui-guest.yaml

#zha_new:
#  usb_path: /dev/ttyUSB1
#  database_path: /config/zigbee.db

zha:
  #usb_path: /dev/ttyUSB1
  #radio_type: deconz
  #radio_type: ezsp
  database_path: /config/zigbee.db
  enable_quirks: true
  device_config:
    ##Allow dimming of KoF bedroom light
    00:22:a3:00:00:27:8b:81-1:
      type: "light"
    00:22:a3:00:00:27:88:08-1:
      type: "light"

# zwave:
#   usb_path: /dev/ttyUSB0
#   network_key: !secret zwave_network_key
#   device_config:
#     switch.stairs:
#       polling_intensity: 2

system_health:

person:

default_config:

mobile_app:

########################
# Stream
########################
stream:

##temporary for fans
#wink:

mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#
  ignore_event:
    - call_service
    - state_changed
# image_processing:
#   - platform: tensorflow
#     source:
#       - entity_id: camera.basement
#       - entity_id: camera.livingroom
#     model:
#       graph: /config/tensorflow/model/frozen_inference_graph.pb
#       categories:
#         - category: person

# image_processing:
#   - platform: deepstack_face
#     ip_address: localhost
#     port: 4999
#     scan_interval: 20000
#     source:
#       - entity_id: camera.livingroom
#         name: face_counter

# zha_map:

# hacs:
#   token: !secret hacs_token
#   appdaemon: true

# circadian_lighting:
#   # negative numbers make for earlier sunrises
#   sunrise_offset: "1:00:00"

#   #positive makes later sunset
#   sunset_offset: "+01:00:00"
