homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml

logger:
  default: info
  logs:
    homeassistant.components.automation: debug

http:
  api_password: !secret http_password

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

wink:
  access_token: !secret wink_access_t
#  refresh_token: !secret wink_refresh_t

climate:
  platform: nest
#  measurement_scale: 'F'

nest:
  username:  !secret email_address
  password:  !secret nest_password
#  measurement_scale: 'F'

device_tracker:
  - platform: luci
#  - platform: ubus
    host: 192.168.1.1
    username: root
    password: !secret router_password
    track_new_devices: no
    interval_seconds: 30
  - platform: icloud
    username: !secret email_address
    password: !secret icloud_password
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    username: !secret email_address
    password: !secret automatic_password


scene: !include scene.yaml

automation: !include automation.yaml

sensor: !include sensor.yaml

zone: !include_dir_list zone

group: !include_dir_merge_named group

proximity: !include proximity.yaml
#proximity: !include_dir_list proximity

input_boolean:
  vacation:
    name: On Vacation
    initial: off
    icon: mdi:nature-people
  home:
    name: Home
    initial: off 
    icon: mdi:home

mqtt:
  broker: 192.168.1.99
  port: 8883
  client_id: home-assistant_1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  protocol: 3.1.1

notify:
  name: telegram
  platform: telegram
  api_key: !secret telegram_api_key
  chat_id: !secret telegram_chat_id

