homeassistant:
  # Name of the location where Home Assistant is running
  name: The Brewery
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  packages: !include_dir_named packages

map:

ios:

config:

logger:
#  default: info
  default: warn
  logs:
    custom_components.device: debug
    homeassistant.components.zha_new: debug
    homeassistant.custom_components.zha_new: debug
    homeassistant.components.sensor.zha_new: debug
    homeassistant.components.wink: debug
    homeassistant.components.hue: debug

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Enables the frontend
frontend:
  javascript_version: latest
# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:

#hue:
#  bridges:
#    - host: 192.168.1.150

wink:
#  email: !secret wink_email
#  password: !secret wink_password
#  access_token: !secret wink_access_t
#  refresh_token: !secret wink_refresh_t

climate:
  platform: nest
#  measurement_scale: 'F'

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
#  username:  !secret email_address
#  password:  !secret nest_password
#  measurement_scale: 'F'

device_tracker:
  - platform: luci
#  - platform: ubus
    host: 192.168.1.1
    username: root
    password: !secret router_password
    consider_home: 180
    track_new_devices: no
    interval_seconds: 30
#  - platform: icloud
#    username: !secret email_address
#    password: !secret icloud_password

#  - platform: automatic
#    client_id: !secret automatic_client_id
#    secret: !secret automatic_secret
#    username: !secret email_address
#    password: !secret automatic_password
  - platform: bluetooth_tracker
  - platform: mqtt
    devices:
      arrival_sensor: 'smartthings/Arrival Sensor/presence'

scene: !include scene.yaml

automation: !include automations.yaml

sensor: !include sensor.yaml

binary_sensor: !include binary_sensor.yaml

zone: !include_dir_list zone

group: !include_dir_merge_named group

proximity: !include proximity.yaml
#proximity: !include_dir_list proximity

script: !include script.yaml

vacuum: !include vacuum.yaml

light: !include light.yaml

mqtt:
  broker: 192.168.1.99
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  protocol: 3.1.1
#  certificate: /etc/ssl/certs/ca-certificates.crt

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify: !include notify.yaml

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: cast
  - platform: firetv
#  - platform: vizio
#    host: 192.168.1.114
#    access_token: !secret vizio_tv_token

recorder:
##  db_url: postgresql://@/hass
#  db_url: !secret recorder_db_url
  purge_interval: 30
  exclude:
    domains:
      - media_player
      - updater
      - sun
    entities:
      - sensor.time
      - sensor.fail2ban_sshd
      - sensor.fail2ban_recidive


influxdb:
  host: 127.0.0.1
  #username: home-assistant
  #password: !secret influx_db_pass

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
