homeassistant:
  name: The Brewery
  unit_system: imperial
  time_zone: America/Chicago
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  packages: !include_dir_named packages

hassio:

ffmpeg:

map:

ios:

config:

logger:
#  default: info
  default: warn
  logs:
    custom_components.device: debug
    homeassistant.components.zha_new: debug
    homeassistant.custom_components.zha_new: debug
    homeassistant.components.sensor.zha_new: debug
#    homeassistant.components.alarm_control_panel: debug
#    homeassistant.components.wink: debug
#    homeassistant.components.hue: debug

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Enables the frontend
frontend:
  javascript_version: latest
# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
hue:
  bridges:
    - host: !secret hue_host

wink:

climate:
  platform: nest
#  measurement_scale: 'F'

tts:
  - platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

scene: !include scene.yaml

automation: !include automations.yaml

sensor: !include sensor.yaml

group: !include_dir_merge_named group

script: !include script.yaml

vacuum: !include vacuum.yaml

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: hassio
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  protocol: 3.1.1

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id

notify: !include notify.yaml

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: cast
  - platform: firetv
#  - platform: vizio
#    host: 192.168.1.114
#    access_token: !secret vizio_tv_token

recorder:
##  db_url: postgresql://@/hass
#  db_url: !secret recorder_db_url
  purge_interval: 30
  exclude:
    domains:
      - media_player
      - updater
      - sun
    entities:
      - sensor.time


influxdb:
  host: !secret influx_db_host

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://ide.rtclauss.org
