version: '3'
services:
  web:
    #image: homeassistant/home-assistant:0.62.0
    image: rtclauss/home-assistant:latest
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - /var/opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/log/fail2ban:/fail2ban
    restart: always
    network_mode: host
