- platform: group
  name: All Living Room
  entities:
    - light.right_lamp
    - light.left_lamp
    - light.tv
    - light.pendant_lamp
- platform: group
  name: Master Bedroom
  entities:
    - light.bedroom_lamp
    - light.bedroom_lamp_2
