- platform: time_date
  display_options:
    - time

##Turn the direction of travel into a sensor which I can use in my automations
##Since sensors have a last changed timestamp.
- platform: template
  sensors:
    home_distance:
      value_template: '{{ states.proximity.home.state }}'
      friendly_name: "Distance to Home"
      entity_id: sensor.time
      unit_of_measurement: 'mi'
    home_time:
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.sensor.heading_home.last_changed)) | int //60 }}'
      friendly_name: "Last Change in Home Dir"
      entity_id: sensor.time
      unit_of_measurement: 'minutes'
    twincities:
      value_template: '{{ states.proximity.twincities.attributes.dir_of_travel |default("unknown") }}'
      friendly_name: 'Direction of Twin Cities'
    heading_home:
      value_template: '{{ states.proximity.home.attributes.dir_of_travel |default("unknown") }}'
      friendly_name: 'Direction of Home'
    test_homeward:
      value_template: >-
        {% if
           (((as_timestamp(now()) - as_timestamp(states.sensor.heading_home.last_changed))//60) > 10) and (states.sensor.heading_home.state=="towards")
        %} true
        {% else %}
          false
        {% endif %}
      friendly_name: "Test Homeward bound"
      entity_id: sensor.time
      