- platform: time_date
  display_options:
    - time

#- platform: systemmonitor
#  resources:
#    - type: memory_use_percent
#    - type: memory_free
#    - type: swap_use_percent
#    - type: network_in
#     arg: eth0
#    - type: network_out
#      arg: eth0
#    - type: last_boot