- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - temperature
    - apparent_temperature
#  - dew_point
#  - wind_speed
#  - wind_bearing
    - cloud_cover
    - humidity
#  - pressure
#  - visibility
#  - ozone

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - feelslike_f
    - heat_index_f
    - observation_time
    - precip_today_in
    - precip_1d_in
    - precip_1d
    - pressure_trend
    - relative_humidity
    - temp_f
    - temp_high_1d_f
    - temp_low_1d_f
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_1h
    - weather_2h
    - weather_3h
    - weather_4h
    - wind_mph
    - wind_dir
    - wind_1d_mph

- platform: mqtt
  state_topic: "sensor/temperature"
  name: "Garage Temperature"
  unit_of_measurement: "°F"
  force_update: true
  retain: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "sensor/humidity"
  name: "Garage Humidity"
  unit_of_measurement: "%"
  force_update: true
  retain: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "sensor/basement_temperature"
  name: "Basement Temperature"
  unit_of_measurement: "°F"
  force_update: true
  retain: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "sensor/basement_humidity"
  name: "Basement Humidity"
  unit_of_measurement: "%"
  force_update: true
  retain: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "smartthings/Livingroom/humidity"
  name: "Living Room Humidity"
  retain: true
  unit_of_measurement: "%"
  force_update: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "smartthings/Livingroom/temperature"
  name: "Living Room Temperature"
  retain: true
  unit_of_measurement: "°F"
  force_update: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "smartthings/Livingroom/battery"
  name: "Living Room Battery"
  retain: true
  force_update: true
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "smartthings/Bathroom/humidity"
  name: "Bathroom Humidity"
  retain: true
  unit_of_measurement: "%"
  force_update: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "smartthings/Bathroom/temperature"
  name: "Bathroom Temperature"
  unit_of_measurement: "°F"
  retain: true
  force_update: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "smartthings/Bathroom/battery"
  name: "Bathroom Battery"
  retain: true
  force_update: true
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "smartthings/Guest/humidity"
  name: "Guest Room Humidity"
  retain: true
  unit_of_measurement: "%"
  force_update: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "smartthings/Guest/temperature"
  name: "Guest Room Temperature"
  retain: true
  unit_of_measurement: "°F"
  force_update: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "smartthings/Guest/battery"
  name: "Guest Room Battery"
  retain: true
  force_update: true
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "smartthings/Master/humidity"
  name: "Master Bedroom Humidity"
  retain: true
  unit_of_measurement: "%"
  force_update: true
#  value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "smartthings/Master/temperature"
  name: "Master Bedroom Temperature"
  unit_of_measurement: "°F"
  retain: true
  force_update: true
#  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "smartthings/Master/battery"
  name: "Master Bedroom Battery"
  retain: true
  force_update: true
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "smartthings/Arrival Sensor/battery"
  name: "Arrival Sensor Battery"
  retain: true
  force_update: true
  unit_of_measurement: "%"


#- platform: nest
#  monitored_conditions:
#    - 'temperature'
#    - 'target'
#    - 'humidity'

- platform: time_date
  display_options:
    - time

##Turn the direction of travel into a sensor which I can use in my automations
##Since sensors have a last changed timestamp.
- platform: template
  sensors:
    fail2ban_total_sshd:
      friendly_name: "Total sshd bans"
      icon_template: mdi:cancel
      entity_id: sensor.fail2ban_sshd
      value_template: "{{states.sensor.fail2ban_sshd.attributes.current_bans|length}}"
    fail2ban_recidive_sshd:
      friendly_name: "Recidive bans"
      icon_template: mdi:cancel
      entity_id: sensor.fail2ban_recidive
      value_template: "{{states.sensor.fail2ban_recidive.attributes.current_bans|length}}"
    home_distance:
      value_template: '{{ states.proximity.home.state }}'
      friendly_name: "Distance to Home"
      entity_id: sensor.time
      unit_of_measurement: 'mi'
    home_time:
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.sensor.heading_home.last_changed)) | int //60 }}'
      friendly_name: "Last Change in Home Dir"
      entity_id: sensor.time
      unit_of_measurement: 'minutes'
    twincities:
      value_template: '{{ states.proximity.twincities.attributes.dir_of_travel |default("unknown") }}'
      friendly_name: 'Direction of Twin Cities'
    heading_home:
      value_template: '{{ states.proximity.home.attributes.dir_of_travel |default("unknown") }}'
      friendly_name: 'Direction of Home'
    motion_sensor_battery:
      value_template: '{{ states.binary_sensor.motion_sensor_motion.attributes.battery_level |int}}'
      friendly_name: 'Motion Sensor Battery'
      entity_id: binary_sensor.motion_sensor_motion
      unit_of_measurement: '%'
    test_homeward:
      value_template: >-
        {% if
           (((as_timestamp(now()) - as_timestamp(states.sensor.heading_home.last_changed))//60) > 10) and (states.sensor.heading_home.state=="towards")
        %} true
        {% else %}
          false
        {% endif %}
      friendly_name: "Test Homeward bound"
      entity_id: sensor.time

- platform: fail2ban
  jails:
    - sshd
    - recidive
  #file_path: /var/log/fail2ban.log
  file_path: /fail2ban/fail2ban.log
  scan_interval: 120
