title: The Brewery
resources:
  - url: /local/custom-lovelace/monster-card/monster-card.js
    type: js
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js
    type: js
views:
- title: Home
  id: home
  icon: mdi:beer
  cards:
    - type: glance
      entities:
        - entity: alarm_control_panel.home_alarm
          name: Alarm
        - entity: device_tracker.bayesian_zeke_home
          name: Where?

    - type: entities
      title: Average Climate
      entities:
        - sensor.average_house_temp
        - sensor.average_house_humidity
        - sensor.average_house_pressure
      
    - type: entities
      title: External
      entities:
        - switch.deck
        - switch.deck_led_string
        - switch.front_door
    
    - type: entities
      title: Living Room
      show_header_toggle: false
      entities:
        - light.living_room_all
        - light.tv
        - light.pendant_lamp
        - switch.flux
        - switch.christmas_tree
        - light.christmas_lights
        - sensor.living_room_temperature
        - sensor.living_room_humidity
        
    - type: entities
      title: Master Bedroom
      show_header_toggle: false
      entities:
        - light.master_bedroom
        - sensor.master_bedroom_temperature
        - sensor.master_bedroom_humidity
      
    - type: entities
      title: Kitchen
      show_header_toggle: false
      entities:
      - light.kitchen_table
      - light.kitchen_sink
      - sensor.kitchen_temperature
      - sensor.kitchen_humidity
      
    - type: entities
      title: Other Lights
      entities:
      - switch.stairs
      - light.hallway_light
      - light.office_lamp
    
    - type: entities
      title: Scenes
      show_header_toggle: false
      entities:
        - scene.bedroom_prep
        - scene.chill
        - scene.the_walking_dead
        - scene.reset_living_room
    
    - type: media-control
      entity: media_player.living_room
      
    - type: media-control
      entity: media_player.amazon_fire_tv
      
    - type: media-control
      entity: media_player.vizio_smartcast

##################################################

- title: Vacation
  id: vacation
  icon: mdi:airport
  cards:
    - type: horizontal-stack
      cards:
      - type: entities
        title: Trip Status
        entities:
          - binary_sensor.planned_vacation_calendar
          - binary_sensor.planned_work_trip_calendar
          - binary_sensor.sensed_trip
          - binary_sensor.flying_home_today
          - sensor.turn_off_time

    - type: horizontal-stack
      cards:
      - type: "custom:monster-card"
        card:
          type: entities
          title: "Lighting Override"
        filter:
          include:
            - entity_id: light.living_room_all
            - entity_id: switch.front_door
            - entity_id: scene.vacation_group_1
        when:
          entity: input_number.random_vacation_light_group
          state: "1.0"
  
      - type: "custom:monster-card"
        card:
          type: entities
          title: "Lighting Override"
        filter:
          include:
            - entity_id: light.living_room_all
            - entity_id: light.master_bedroom
            - entity_id: switch.stairs
            - entity_id: scene.vacation_group_2
        when:
          entity: input_number.random_vacation_light_group
          state: "2.0"
  
      - type: "custom:monster-card"
        card:
          type: entities
          title: "Lighting Override"
        filter:
          include:
            - entity_id: light.living_room_all
            - entity_id: light.master_bedroom
            - entity_id: light.kitchen_table
            - entity_id: scene.vacation_group_3
        when:
          entity: input_number.random_vacation_light_group
          state: "3.0"
  
      - type: "custom:monster-card"
        card:
          type: entities
          title: "Lighting Override"
        filter:
          include:
            - entity_id: light.living_room_all
            - entity_id: light.kitchen_table
            - entity_id: light.office_lamp
            - entity_id: switch.stairs
            - entity_id: switch.front_door
            - entity_id: scene.vacation_group_4
        when:
          entity: input_number.random_vacation_light_group
          state: "4.0"


##################################################

- title: Weather
  id: weather
  icon: mdi:weather-lightning
  cards: 
    - type: iframe
      url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=MPX&brand=wui&num=10&delay=15&type=N0Z&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25525140&lat=0&lon=0&label=you
      aspect_ration: 25%
    - type: "custom:entity-attributes-card"
      title: Weather Alerts
      attributes:
        - key: sensor.pws_alerts.Description
          name: Type
        - key: sensor.pws_alerts.Message
          name: Details
  
    - type: entities
      title: Current Conditions
      entities:
        - sun.sun
        - sensor.pws_weather
        - sensor.pws_temp_f
        - sensor.pws_feelslike_f
        - sensor.pws_dewpoint_f
        - sensor.pws_relative_humidity
        - sensor.pws_heat_index_f
        - sensor.pws_pressure_mb
        - sensor.pws_pressure_trend
        - sensor.dark_sky_cloud_coverage
        - sensor.dark_sky_precip_intensity
        - sensor.dark_sky_precip
        - sensor.precip_next_6h
        - sensor.pws_observation_time
  
    - type: entities
      title: Daily Forecast
      entities:
        - sensor.pws_weather_1d
        - sensor.pws_weather_1n
        - sensor.pws_weather_2d
        - sensor.pws_weather_2n
        - sensor.pws_weather_3d
        - sensor.pws_weather_3n

    - type: entities
      title: Six-hour Forecast
      entities:
        - sensor.pws_weather
        - sensor.pws_weather_1h
        - sensor.pws_weather_2h
        - sensor.pws_weather_3h
        - sensor.pws_weather_4h
        - sensor.pws_weather_5h
        - sensor.pws_weather_6h

    - type: entities
      title: Pressure Trends
      entities:
        - binary_sensor.pressure_rising_v_rapidly
        - binary_sensor.pressure_rising_quickly
        - binary_sensor.pressure_rising
        - binary_sensor.pressure_rising_slowly
        - binary_sensor.pressure_falling_slowly
        - binary_sensor.pressure_falling
        - binary_sensor.pressure_falling_quickly
        - binary_sensor.pressure_falling_v_rapidly

##################################################

- title: Cameras
  id: cameras
  icon: mdi:cctv
  cards:
    - type: vertical-stack
      cards:
        - type: picture-entity
          entity: camera.livingroom
        - type: entities
          title: Living Room Controls
          show_header_toggle: false
          entities:
            - cover.livingroom_move_leftright
            - cover.livingroom_move_updown
            - switch.livingroom_motion_detection
            - switch.livingroom_motion_tracking
        - type: picture-entity
          entity: camera.livingroom_motion_snapshot

    - type: vertical-stack
      cards:
        - type: picture-entity
          entity: camera.basement
        - type: entities
          title: Basement Controls
          show_header_toggle: false
          entities:
            - cover.basement_move_leftright
            - cover.basement_move_updown
            - switch.basement_motion_detection
            - switch.basement_motion_tracking
        - type: picture-entity
          entity: camera.basement_motion_snapshot

##################################################

- title: Climate
  id: climate
  icon: mdi:gauge
  cards:
    - type: entities
      title: Current Conditions
      entities:
        - sun.sun
        - sensor.pws_weather
        - sensor.pws_temp_f
        - sensor.pws_feelslike_f
        - sensor.pws_dewpoint_f
        - sensor.pws_relative_humidity
        - sensor.pws_heat_index_f
        - sensor.pws_pressure_mb
        - sensor.pws_pressure_trend
        - sensor.dark_sky_cloud_coverage
        - sensor.dark_sky_precip_intensity
        - sensor.dark_sky_precip
        - sensor.precip_next_6h
        - sensor.pws_observation_time
  
    - type: entities
      title: Climate at a Glance
      entities:
        - climate.hallway_glycol
        - sensor.hallway_thermostat_glycol_temperature
        - sensor.hallway_thermostat_glycol_humidity
        - sensor.hallway_thermostat_glycol_target
        - sensor.hallway_thermostat_glycol_operation_mode
  
    - type: entities
      title: Living Room
      entities:
      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.living_room_pressure
      - sensor.living_room_battery
      - sensor.motion_sensor_temperature
    - type: entities
      title: Master Bedroom
      entities:
      - sensor.master_bedroom_temperature
      - sensor.master_bedroom_humidity
      - sensor.master_bedroom_pressure
      - sensor.master_bedroom_battery
    - type: entities
      title: Guest Bedroom
      entities:
      - sensor.guest_room_temperature
      - sensor.guest_room_humidity
      - sensor.guest_room_pressure
      - sensor.guest_room_battery
    - type: entities
      title: Kitchen
      entities:
      - sensor.kitchen_temperature
      - sensor.kitchen_humidity
      - sensor.kitchen_pressure
      - sensor.kitchen_battery
    - type: entities
      title: Bathroom
      entities:
      - sensor.bathroom_temperature
      - sensor.bathroom_humidity
      - sensor.bathroom_pressure
      - sensor.bathroom_battery
    - type: entities
      title: Basement
      entities:
      - sensor.basement_temperature
      - sensor.basement_humidity
    - type: entities
      title: Garage
      entities:
      - sensor.garage_temperature
      - sensor.garage_humidity

##################################################

- title: Plants
  id: plants
  icon: mdi:tree
  cards:
    - type: vertical-stack
      cards:
      - type: plant-status
        entity: plant.east_hanging_nepenthes
      - type: plant-status
        entity: plant.west_hanging_nepenthes
      - type: plant-status
        entity: plant.four_inch_nepenthes
    - type: vertical-stack
      cards:
      - type: plant-status
        entity: plant.orchid

##################################################

- title: Automations
  id: automations
  icon: mdi:robot
  cards:
    - type: entities
      title: Motion Sensors
      entities:
        - binary_sensor.hallway_motion
        - binary_sensor.office_motion
        - binary_sensor.master_bedroom_motion
        - binary_sensor.downstairs_motion
        - binary_sensor.motion_sensor_motion
        - binary_sensor.livingroom_motion_sensor
        - binary_sensor.basement_motion_sensor
  
    - type: glance
      title: Travel Sensors
      entities:
        - sensor.home_distance
        - sensor.home_time
        - sensor.heading_home
        - sensor.twincities
        - binary_sensor.test_homeward
  
    - type: entities
      title: Bayesian Presence
      entities:
        - binary_sensor.bayesian_zeke_home
        - device_tracker.bayesian_zeke_home
        - device_tracker.wethop
        - device_tracker.4098ad3265d4
        - device_tracker.arrival_sensor
        - device_tracker.iphone_bt
        - sensor.iphone_battery_state
        - binary_sensor.nest_home
  
    - type: entities
      title: Logging Level
      entities:
        - input_select.log_level
  
    - type: entities
      title: Vacation Light Settings
      entities:
      - input_number.random_vacation_light_group
      - input_number.random_hour
      - input_number.random_minute
  
    - type: entity-filter
      card_config:
        title: All Automations
      filter:
        - domain: automation

##################################################

- title: Batteries
  id: batteries
  icon: mdi:battery
  cards:
    - type: entities
      title: Status
      entities:
          - sensor.arrival_sensor_battery
          - sensor.basement_door_battery
          - sensor.bathroom_battery
          - sensor.deck_door_battery
          - sensor.downstairs_motion_battery
          - sensor.ene_window_battery
          - sensor.ese_window_battery
          - sensor.front_door_battery
          - sensor.guest_room_button_battery
          - sensor.guest_room_battery
          - sensor.hallway_motion_battery
          - sensor.kitchen_battery
          - sensor.living_room_battery
          - sensor.living_room_button_battery
          - sensor.master_bedroom_battery
          - sensor.master_bedroom_motion_battery
          - sensor.motion_sensor_battery
          - sensor.north_kitchen_sink_window_battery
          - sensor.north_master_bedroom_window_battery
          - sensor.nne_window_battery
          - sensor.nw_basement_window_battery
          - sensor.office_motion_battery
          - sensor.office_north_window_battery
          - sensor.se_basement_window_battery
          - sensor.sw_basement_window_battery

##################################################

- title: Blocked Domains
  id: adblock
  icon: mdi:close-circle-outline
  cards:
    - type: entities
      title: PiHole Data
      entities:
        - sensor.pihole_dns_unique_clients
        - sensor.pihole_dns_queries_today
        - sensor.pihole_ads_blocked_today
        - sensor.pihole_ads_percentage_blocked_today

##################################################

- cards:
  - card_config:
      title: All Entities
    filter:
    - {}
    type: entity-filter
  title: All Entities
  icon: mdi:settings

