title: The Brewery

# custom_header:
#   compact_mode: true
#   voice: hide
#   swipe: true
#   hide_config: true
#test_template: '{% if is_state("binary_sensor.sensed_trip", "off") %}vacation,{% endif %}{% if is_state("binary_sensor.bayesian_zeke_home", "on") %}cameras,{% endif %}{% if is_state("binary_sensor.curling_season", "off") %}curling{% endif %}'
#hide_tabs: '{% if is_state("binary_sensor.sensed_trip", "off") %}vacation,{% endif %}{% if is_state("binary_sensor.bayesian_zeke_home", "on") %}cameras,{% endif %}{% if is_state("binary_sensor.curling_season", "off") %}curling{% endif %}'

views:
  - title: Home
    path: home
    icon: mdi:beer
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: menu
              - type: entity
                entity: alarm_control_panel.home_alarm
              - type: entity
                entity: person.ryan
                icon: mdi:face-man
              - type: entity
                entity: sensor.average_house_temp
              - type: entity
                entity: climate.hallway_glycol
          - type: weather-forecast
            entity: weather.dark_sky
            secondary_info_attribute: humidity
            show_current: true
            show_forecast: true
          - type: custom:mushroom-entity-card
            entity: climate.hallway_glycol
            primary_info: state
            secondary_info: name
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.average_house_temp
                primary_info: state
                secondary_info: name
              - type: custom:mushroom-entity-card
                entity: sensor.average_house_humidity
                primary_info: state
                secondary_info: name
              - type: custom:mushroom-entity-card
                entity: sensor.average_house_pressure
                primary_info: state
                secondary_info: name
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-light-card
                entity: light.west_guest_room_lamp
                show_brightness_control: true
                show_color_temp_control: true
                hide_state: true
                use_light_color: true
                hide_icon: true
                # secondary_info: name
              - type: custom:mushroom-light-card
                entity: light.dining_room_lamp_bulb
                show_brightness_control: true
                show_color_temp_control: true
                hide_state: true
                use_light_color: true
                hide_icon: true
          - type: custom:mushroom-light-card
            entity: light.kitchen_sink
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.main_hall_entry_lights
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.main_hall_upstairs_lights
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.den_ceiling
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.owner_suite_ceiling
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.owner_suite_bathroom_lights
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.office_ceiling
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-light-card
                entity: light.den_ceiling
                show_brightness_control: true
                show_color_temp_control: true
                hide_state: true
                use_light_color: true
                hide_icon: true
                hold_action: more-info
                collapsible_controls: true
              - type: custom:mushroom-light-card
                entity: light.den_floods
                show_brightness_control: true
                show_color_temp_control: true
                hide_state: true
                use_light_color: true
                hide_icon: true
                hold_action: more-info
                collapsible_controls: true

          - type: custom:mushroom-light-card
            entity: light.guest_room_ceiling
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
          - type: custom:mushroom-light-card
            entity: light.basement_all_down_lights
            show_brightness_control: true
            show_color_temp_control: true
            hide_state: true
            use_light_color: true
            hide_icon: true
            hold_action: more-info
            collapsible_controls: true
