esphomeyaml:
  name: basement
  platform: ESP8266
  board: huzzah

wifi:
  ssid: !secret wifi_ap
  password: !secret wifi_password
  domain: '.lan'

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

# Enable logging
logger:

ota:

sensor:
  - platform: dht
    pin: 14
    model: AM2302
    temperature: 
      name: "Basement Temperature"
      unit_of_measurement: "°F"
      icon: "mdi:thermometer"
      filters:
        - lambda: return x * (9.0 / 5.0) + 32.0;
    humidity:
      name: "Basement Humidity"
      unit_of_measurement: "%"
      icon: "mdi:water-percent"
    
