esphome:
  name: bedloadcell2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ap
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedloadcell2 Fallback Hotspot"
    password: "nfV2kQYGCrzj"

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

ota:

sensor:
  - platform: hx711
    name: "Bed Load Cell 2"
    dout_pin: GPIO0
    clk_pin: GPIO14
    gain: 128
    update_interval: 2s
    filters:
      - calibrate_linear:
          - 550700 -> 0
          - -125000 -> 86
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
    unit_of_measurement: kg
    accuracy_decimals: 2
