substitutions:
  device_name: denbluetoothproxy
  device_label: Den Bluetooth Proxy
  ota_password: "70342fb7c4171e7a76a18f21449c76a1"
  fallback_ap_name: "Bluetoothproxy1 Fallback Hotspot"

packages:
  common_base: !include packages/common/base.yaml
  bluetooth_proxy: !include packages/common/bluetooth_proxy.yaml
