substitutions:
  device_name: diningroom-bt-proxy
  device_label: Dining Room Bluetooth Proxy
  ota_password: "a2165fb9213f0f478846082f5d7399e0"
  fallback_ap_name: "LivingRoomBt Fallback Hotspot"

packages:
  common_base: !include packages/common/base.yaml
  bluetooth_proxy: !include packages/common/bluetooth_proxy.yaml
