esphome:
  name: watersoftener
  platform: ESP8266
  board: esp01_1m
  libraries:
    - "VL53L0X"
  includes:
    - "vl53l0x_sensor.h"

wifi:
  ssid: "barley"
  password: "1107claussen"


# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:

ota:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new VL53L0XSensor(300000);
    App.register_component(my_sensor);
    return {my_sensor};

  sensors:
    name: "My Water Softener VL53L0X Sensor"
    icon: "mdi:shaker-outline"
    unit_of_measurement: mm
#    filters:
#      - exponential_moving_average:
#          alpha: 0.1
#          send_every: 15
