################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "TO_CHANGE"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Climate
    ################################################

    ################################################
    ## Covers
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ##  Notify
    ################################################

    ################################################
    ##  Octoprint
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Weather
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Climate
########################
climate:

########################
# Covers
########################
cover:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input DateTime
########################
input_datetime:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Notify
########################
notify:

########################
# Octoprint
########################
# YAML Deprecated 2022.2
# octoprint:

########################
# Plant
########################
plant:

########################
# REST Sensor
########################

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: rest
    name: "ADSB Aircraft Raw"
    resource: http://10.24.1.188:8080/data/aircraft.json
    scan_interval: 30
    value_template: "{{ value_json.now }}"
    json_attributes:
      - aircraft

  - platform: rest
    name: Closest Aircraft Photo Raw
    resource_template: >-
      {% set hx = state_attr('sensor.closest_aircraft_overhead','hex') %}
      {% if hx %}https://api.planespotters.net/pub/photos/hex/{{ hx }}{% else %}https://api.planespotters.net/pub/photos/hex/000000{% endif %}
    scan_interval: 30
    headers:
      User-Agent: "HomeAssistant/1.0 (aircraft display)"
    value_template: >-
      {{ value_json.photos | count if value_json.photos is defined else 0 }}
    json_attributes:
      - photos

########################
# Switch
########################
switch:

########################
# Templates
########################
template:
  - sensor:
      - name: "Closest Aircraft Overhead"
        icon: mdi:airplane
        state: >-
          {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
          {% set home_lat = state_attr('zone.home', 'latitude') %}
          {% set home_lon = state_attr('zone.home', 'longitude') %}
          {% set max_km = 5 * 1.609344 %}
          {% set max_alt = 10000 %}

          {% set ns = namespace(best=None, best_d=999999) %}

          {% for p in planes %}
            {% set lat = p.lat | default(none) %}
            {% set lon = p.lon | default(none) %}
            {% set alt = p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) %}
            {% if lat is not none and lon is not none and alt is not none and alt != 'ground' %}
              {% set alt_ft = alt | float(-1) %}
              {% if 0 <= alt_ft < max_alt %}
                {% set d_km = distance(home_lat, home_lon, lat, lon) %}
                {% if d_km is not none and d_km < max_km and d_km < ns.best_d %}
                  {% set ns.best_d = d_km %}
                  {% set ns.best = p %}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}

          {% if ns.best %}
            {% set cs = (ns.best.flight | default('') ) | trim %}
            {% if cs != '' %}
              {{ cs }}
            {% else %}
              {{ ns.best.hex | default('unknown') }}
            {% endif %}
          {% else %}
            none
          {% endif %}
        attributes:
          distance_km: >-
            {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
            {% set home_lat = state_attr('zone.home', 'latitude') %}
            {% set home_lon = state_attr('zone.home', 'longitude') %}
            {% set max_km = 5 * 1.609344 %}
            {% set max_alt = 10000 %}
            {% set ns = namespace(best=None, best_d=999999) %}
            {% for p in planes %}
              {% set lat = p.lat | default(none) %}
              {% set lon = p.lon | default(none) %}
              {% set alt = p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) %}
              {% if lat is not none and lon is not none and alt is not none and alt != 'ground' %}
                {% set alt_ft = alt | float(-1) %}
                {% if 0 <= alt_ft < max_alt %}
                  {% set d_km = distance(home_lat, home_lon, lat, lon) %}
                  {% if d_km is not none and d_km < max_km and d_km < ns.best_d %}
                    {% set ns.best_d = d_km %}
                    {% set ns.best = p %}
                  {% endif %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {% if ns.best %}{{ ns.best_d | round(3) }}{% else %}{{ none }}{% endif %}
          distance_mi: >-
            {% if this.attributes.distance_km is not none %}
              {{ (this.attributes.distance_km | float * 0.621371) | round(2) }}
            {% else %}
              {{ none }}
            {% endif %}
          callsign: >-
            {% set cs = (states('sensor.closest_aircraft_overhead') | trim) %}
            {% if cs not in ['none','unknown','unavailable'] %}{{ cs }}{% else %}{{ none }}{% endif %}
          hex: >-
            {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
            {% set cs = states('sensor.closest_aircraft_overhead') | trim %}
            {% for p in planes %}
              {% if (p.flight | default('') | trim) == cs %}
                {{ p.hex | default(none) }}
              {% endif %}
            {% endfor %}
          altitude_ft: >-
            {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
            {% set cs = states('sensor.closest_aircraft_overhead') | trim %}
            {% for p in planes %}
              {% if (p.flight | default('') | trim) == cs %}
                {{ p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) }}
              {% endif %}
            {% endfor %}
          is_military: >-
            {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
            {% set cs = states('sensor.closest_aircraft_overhead') | trim %}
            {% for p in planes %}
              {% if (p.flight | default('') | trim) == cs %}
                {{ p.is_military | default(false) }}
              {% endif %}
            {% endfor %}

########################
# Weather
########################
weather:

########################
# Zone
########################
zone:
