################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "TO_CHANGE"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Climate
    ################################################

    ################################################
    ## Covers
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ##  Notify
    ################################################

    ################################################
    ##  Octoprint
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Weather
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Climate
########################
climate:

########################
# Covers
########################
cover:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input DateTime
########################
input_datetime:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Notify
########################
notify:

########################
# Octoprint
########################
# YAML Deprecated 2022.2
# octoprint:

########################
# Plant
########################
plant:

########################
# REST Sensor
########################

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: rest
    name: "ADSB Aircraft Raw"
    resource: http://10.24.1.188:8080/data/aircraft.json
    scan_interval: 10
    value_template: "{{ value_json.now }}"
    json_attributes:
      - aircraft

  - platform: rest
    name: Closest Aircraft Photo Raw
    resource_template: >-
      {% set hx = state_attr('sensor.closest_aircraft_overhead','hex') %}
      {% if hx %}
        https://api.planespotters.net/pub/photos/hex/{{ hx }}
      {% else %}
        https://api.planespotters.net/pub/photos/hex/000000
      {% endif %}
    scan_interval: 120
    headers:
      User-Agent: "HomeAssistant/1.0 (aircraft display)"
    value_template: >-
      {{ (value_json.photos | length) if value_json.photos is defined else 0 }}
    json_attributes:
      - photos

  - platform: rest
    name: Closest Aircraft Route Raw
    resource_template: >-
      {% set cs = state_attr('sensor.closest_aircraft_overhead','callsign') %}
      {% if cs %}
        https://api.adsbdb.com/v0/callsign/{{ cs }}
      {% else %}
        https://api.adsbdb.com/v0/callsign/NULL
      {% endif %}
    scan_interval: 120
    value_template: >-
      {{ value_json.response is defined }}
    json_attributes:
      - response

########################
# Switch
########################
switch:

########################
# Templates
########################
template:
  - sensor:
      - name: "Closest Aircraft Overhead"
        icon: mdi:airplane

        # State: callsign if present, else HEX, else "none"
        state: >-
          {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
          {% set home_lat = state_attr('zone.home', 'latitude') %}
          {% set home_lon = state_attr('zone.home', 'longitude') %}
          {% set max_km = 5 * 1.609344 %}
          {% set max_alt = 10000 %}

          {% set ns = namespace(best=None, best_d=999999) %}
          {% for p in planes %}
            {% set lat = p.lat | default(none) %}
            {% set lon = p.lon | default(none) %}
            {% set alt = p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) %}
            {% if lat is not none and lon is not none and alt is not none and alt != 'ground' %}
              {% set alt_ft = alt | float(-1) %}
              {% if 0 <= alt_ft < max_alt %}
                {% set d_km = distance(home_lat, home_lon, lat, lon) %}
                {% if d_km is not none and d_km < max_km and d_km < ns.best_d %}
                  {% set ns.best_d = d_km %}
                  {% set ns.best = p %}
                {% endif %}
              {% endif %}
            {% endif %}
          {% endfor %}

          {% if ns.best %}
            {% set cs = (ns.best.flight | default('')) | trim %}
            {% if cs != '' %}
              {{ cs }}
            {% else %}
              {{ ns.best.hex | default('unknown') }}
            {% endif %}
          {% else %}
            none
          {% endif %}

        attributes:
          # Compute the selected aircraft once as "raw" (hex-based), then all other attrs read from it.
          raw: >-
            {% set planes = state_attr('sensor.adsb_aircraft_raw', 'aircraft') or [] %}
            {% set home_lat = state_attr('zone.home', 'latitude') %}
            {% set home_lon = state_attr('zone.home', 'longitude') %}
            {% set max_km = 5 * 1.609344 %}
            {% set max_alt = 10000 %}

            {% set ns = namespace(best=None, best_d=999999) %}
            {% for p in planes %}
              {% set lat = p.lat | default(none) %}
              {% set lon = p.lon | default(none) %}
              {% set alt = p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) %}
              {% if lat is not none and lon is not none and alt is not none and alt != 'ground' %}
                {% set alt_ft = alt | float(-1) %}
                {% if 0 <= alt_ft < max_alt %}
                  {% set d_km = distance(home_lat, home_lon, lat, lon) %}
                  {% if d_km is not none and d_km < max_km and d_km < ns.best_d %}
                    {% set ns.best_d = d_km %}
                    {% set ns.best = p %}
                  {% endif %}
                {% endif %}
              {% endif %}
            {% endfor %}
            {{ ns.best if ns.best else dict() }}

          hex: >-
            {% set p = this.attributes.raw %}
            {{ p.hex if p and p.hex is defined else none }}

          callsign: >-
            {% set p = this.attributes.raw %}
            {% set cs = (p.flight | default('')) | trim if p else '' %}
            {{ cs if cs != '' else none }}

          altitude_ft: >-
            {% set p = this.attributes.raw %}
            {% if p %}
              {{ p.alt_baro if p.alt_baro is defined else (p.alt_geom if p.alt_geom is defined else none) }}
            {% else %}
              {{ none }}
            {% endif %}

          distance_km: >-
            {# Use computed distance from selection pass, if present in feed; else recompute #}
            {% set p = this.attributes.raw %}
            {% if p and p.lat is defined and p.lon is defined %}
              {% set home_lat = state_attr('zone.home', 'latitude') %}
              {% set home_lon = state_attr('zone.home', 'longitude') %}
              {{ distance(home_lat, home_lon, p.lat, p.lon) | round(3) }}
            {% else %}
              {{ none }}
            {% endif %}

          distance_mi: >-
            {% if this.attributes.distance_km is not none %}
              {{ (this.attributes.distance_km | float * 0.621371) | round(2) }}
            {% else %}
              {{ none }}
            {% endif %}

          # Plane description + ICAO type code
          desc: >-
            {% set p = this.attributes.raw %}
            {{ p.desc if p and p.desc is defined else none }}

          type_code: >-
            {% set p = this.attributes.raw %}
            {{ p.t if p and p.t is defined else none }}

          # Military flag comes directly from your feed (best)
          is_military: >-
            {% set p = this.attributes.raw %}
            {{ p.is_military | default(false) if p else false }}

          # Route: best-effort from whatever your feed has
          route: >-
            {% set p = this.attributes.raw %}
            {% if not p %}
              {{ none }}
            {% elif p.route is defined and (p.route | string | trim) != '' %}
              {{ p.route }}
            {% elif p.from is defined and p.to is defined and (p.from | string | trim) != '' and (p.to | string | trim) != '' %}
              {{ (p.from | string | trim) ~ " → " ~ (p.to | string | trim) }}
            {% elif p.from_iata is defined and p.to_iata is defined and (p.from_iata | string | trim) != '' and (p.to_iata | string | trim) != '' %}
              {{ (p.from_iata | string | trim) ~ " → " ~ (p.to_iata | string | trim) }}
            {% elif p.from_icao is defined and p.to_icao is defined and (p.from_icao | string | trim) != '' and (p.to_icao | string | trim) != '' %}
              {{ (p.from_icao | string | trim) ~ " → " ~ (p.to_icao | string | trim) }}
            {% else %}
              {{ none }}
            {% endif %}

  - sensor:
      - name: "Closest Aircraft Photo"
        state: >-
          {% set photos = state_attr('sensor.closest_aircraft_photo_raw','photos') or [] %}
          {{ 'ok' if (photos | length) > 0 else 'none' }}
        attributes:
          url: >-
            {% set photos = state_attr('sensor.closest_aircraft_photo_raw','photos') or [] %}
            {% if (photos | length) > 0 %}
              {% set p = photos[0] %}
              {{ p.thumbnail_large.src
                if p.thumbnail_large is defined and p.thumbnail_large.src is defined
                else (p.thumbnail.src if p.thumbnail is defined and p.thumbnail.src is defined else none) }}
            {% else %}
              {{ none }}
            {% endif %}
          link: >-
            {% set photos = state_attr('sensor.closest_aircraft_photo_raw','photos') or [] %}
            {% if (photos | length) > 0 %}
              {{ photos[0].link | default(none) }}
            {% else %}
              {{ none }}
            {% endif %}
          photographer: >-
            {% set photos = state_attr('sensor.closest_aircraft_photo_raw','photos') or [] %}
            {% if (photos | length) > 0 %}
              {{ photos[0].photographer | default(none) }}
            {% else %}
              {{ none }}
            {% endif %}

  - sensor:
      - name: "Closest Aircraft Route"
        state: >-
          {% set r = state_attr('sensor.closest_aircraft_route_raw','response') %}
          {% if r and r.flightroute is defined %}
            {% set fr = r.flightroute %}
            {% set o = fr.origin.icao_code if fr.origin is defined else none %}
            {% set d = fr.destination.icao_code if fr.destination is defined else none %}
            {% if o and d %}
              {{ o ~ " → " ~ d }}
            {% else %}
              unknown
            {% endif %}
          {% else %}
            unknown
          {% endif %}
        attributes:
          origin_icao: >-
            {% set r = state_attr('sensor.closest_aircraft_route_raw','response') %}
            {{ r.flightroute.origin.icao_code
              if r and r.flightroute is defined and r.flightroute.origin is defined
              else none }}
          origin_name: >-
            {% set r = state_attr('sensor.closest_aircraft_route_raw','response') %}
            {{ r.flightroute.origin.name
              if r and r.flightroute is defined and r.flightroute.origin is defined
              else none }}
          destination_icao: >-
            {% set r = state_attr('sensor.closest_aircraft_route_raw','response') %}
            {{ r.flightroute.destination.icao_code
              if r and r.flightroute is defined and r.flightroute.destination is defined
              else none }}
          destination_name: >-
            {% set r = state_attr('sensor.closest_aircraft_route_raw','response') %}
            {{ r.flightroute.destination.name
              if r and r.flightroute is defined and r.flightroute.destination is defined
              else none }}

########################
# Weather
########################
weather:

########################
# Zone
########################
zone:
