################################################################
## Packages / Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "alerts"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: true

    ################################################
    ## Alarm Panels
    ################################################
    alarm_control_panel.home_alarm:
      <<: *customize
      friendly_name: Home Alarm
      icon: mdi:home-alert

    ################################################
    ## Automation
    ################################################
    automation.arm_alarm:
      <<: *customize
      friendly_name: "Arm Home Alarm"
      icon: mdi:home-alert

    automation.disarm_alarm:
      <<: *customize
      friendly_name: "Disarm Home Alarm"
      icon: mdi:home-alert

    automation.motion_detected_on_trip:
      <<: *customize
      friendly_name: "Home Alarm Triggered"
      icon: mdi:home-alert

    automation.send_notification_when_alarm_triggered:
      <<: *customize
      friendly_name: "Notify Home Alarm Triggered"
      icon: mdi:home-alert

    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.flash_lights:
      <<: *customize
      friendly_name: "Flash lights"
      icon: mdi:alarm-light

########################
# Alarm Panel
########################
alarm_control_panel:
  - platform: manual
    name: home_alarm
    code: !secret alarm_code
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 30

########################
# Automations
########################
automation:
  - id: water_leak_detected
    alias: water_leak_detected
    trigger:
      - trigger: state
        entity_id: binary_sensor.basement_unfinished_leak_water_leak
        from: "on"
        to: "off"
        id: dry
      - trigger: state
        entity_id: binary_sensor.basement_unfinished_leak_water_leak
        from: "off"
        to: "on"
        id: wet

      - trigger: state
        entity_id: binary_sensor.kitchen_sink_leak_water_leak
        from: "off"
        to: "on"
        id: wet
      - trigger: state
        entity_id: binary_sensor.kitchen_sink_leak_water_leak
        from: "on"
        to: "off"
        id: dry

      - trigger: state
        entity_id: binary_sensor.laundry_room_leak_water_leak
        from: "off"
        to: "on"
        id: wet
      - trigger: state
        entity_id: binary_sensor.laundry_room_leak_water_leak
        from: "off"
        to: "on"
        id: dry

    action:
      - choose:
          - conditions:
              - condition: trigger
                id: wet
            sequence:
              # Select Wet
              - action: persistent_notification.create
                data:
                  title: Wet floor
                  message: >-
                    {{  trigger.from_state.attributes.friendly_name }} is wet.
                  notification_id: wet-floor-alert
              - action: notify.all
                data:
                  message: >-
                    {{  trigger.from_state.attributes.friendly_name }} is wet.
          - conditions:
              - condition: trigger
                id: dry
            sequence:
              # Select dry
              - action: persistent_notification.create
                data:
                  title: Dry floor
                  message: >-
                    {{  trigger.from_state.attributes.friendly_name }} is dry.
                  notification_id: wet-floor-alert
              - action: notify.all
                data:
                  message: >-
                    {{  trigger.from_state.attributes.friendly_name }} has dried.

  - id: motion_detected_on_trip
    alias: motion_detected_on_trip
    mode: restart
    trigger:
      - trigger: state
        entity_id:
          - binary_sensor.basement_door_contact
          - binary_sensor.se_basement_window_contact
          - binary_sensor.sw_basement_window_contact
          - binary_sensor.deck_door_contact
          #        - binary_sensor.downstairs_motion
          - binary_sensor.ene_window_contact
          - binary_sensor.ese_window_contact
          - binary_sensor.main_foyer_front_door_contact
          #        - binary_sensor.hallway_motion
          #        - binary_sensor.master_bedroom_motion
          - binary_sensor.nne_window_contact
          - binary_sensor.north_kitchen_sink_window_contact
          - binary_sensor.north_master_bedroom_window_contact
          - binary_sensor.nw_basement_window_contact
          - binary_sensor.office_occupancy
          - binary_sensor.office_north_window_contact
          #        - binary_sensor.motion_sensor_motion
          - binary_sensor.sse_window_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      - action: alarm_control_panel.alarm_trigger
        target:
          entity_id: alarm_control_panel.home_alarm
      - action: notify.all
        data:
          message: >
            Motion detected at {{ trigger.to_state.attributes.friendly_name }} while you're away!
      #    - action: tts.google_say
      #      data:
      #        message: "Intruder Alert! Intruder Alert! You are detected and recorded."
      - action: light.turn_on
        data:
          entity_id: light.dining_room_lamps
          flash: long
      - delay: 00:00:02
      - action: light.turn_on
        data:
          entity_id: light.dining_room_lamps
          flash: long
      - delay: 00:00:02
      - action: light.turn_on
        data:
          entity_id: light.dining_room_lamps
          flash: long

  - alias: send_notification_when_alarm_triggered
    id: send_notification_when_alarm_triggered
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - action: notify.all
        data:
          message: >
            Alarm triggered while you're away

  - alias: send_pic_from_camera
    id: send_pic_from_camera
    trigger:
      - trigger: state
        entity_id:
          - binary_sensor.basement_motion_sensor
          - binary_sensor.livingroom_motion_sensor
        from: "off"
        to: "on"
        for:
          seconds: 5
    # condition:
    action:
      - action: notify.mobile_app_wethop
        data:
          message: >-
            Stream from {{ trigger.to_state.attributes.friendly_name }}
          entity_id: >-
            {% if trigger.entity_id == "binary_sensor.basement_motion_sensor" %}
              camera.tikiroomcamera
            {% else %}
              camera.livingroomcamera
            {% endif %}

  - alias: arm_alarm
    id: arm_alarm
    trigger:
      - trigger: state
        entity_id: binary_sensor.bayesian_zeke_home
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      #    - action: notify.all
      #      data_template:
      #        message: >
      #          Enabled alarm and turned on motion detection
      - action: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.home_alarm
        data:
          code: !secret alarm_code
      - action: switch.turn_on
        target:
          entity_id:
            - switch.livingroom_motion_detection
            - switch.tikiroomcam_tikiroom_motion_detection
      - action: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.house_unoccupied

  - alias: disarm_alarm
    id: disarm_alarm
    trigger:
      - trigger: state
        entity_id: binary_sensor.bayesian_zeke_home
        from: "off"
        to: "on"
    action:
      - action: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.home_alarm
        data:
          code: !secret alarm_code
      - action: switch.turn_off
        target:
          entity_id:
            - switch.livingroom_motion_detection
            - switch.tikiroomcam_tikiroom_motion_detection
      #    - action: notify.all
      #      data_template:
      #        message: >
      #          Disabled alarm and turned off motion detection
      - action: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.house_unoccupied

  - alias: notify_ios_app
    id: notify_ios_app
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - action: notify.mobile_app_wethop
        data:
          message: "Something triggered alarm panel at home!"

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Groups
########################
group:
  motion_sensors:
    entities:
      - binary_sensor.hall_upstairs_motion_occupancy
      - binary_sensor.office_occupancy_2
      - binary_sensor.bedroom_occupancy
      - binary_sensor.hall_main_foyer_motion_occupancy
      - binary_sensor.den_occupancy_2
      - binary_sensor.livingroom_motion_sensor
      - binary_sensor.basement_landing_occupancy
      - binary_sensor.basement_occupancy_2

########################
# Input Booleans
########################
input_boolean: {}

########################
# Input Numbers
########################
input_number: {}

########################
# iOS
########################
ios: {}

########################
# Light
########################
light: []

########################
# Notify
########################
notify:
  - name: all
    platform: group
    services:
      #    - action: telegram
      - action: mobile_app_faro
      - action: mobile_app_wethop
      - action: mobile_app_rtclauss
      - action: mobile_app_ryans_macbook_pro
      - action: lg_webos_tv_oled65cxpua

########################
# Scenes
########################
scene: []

########################
# Scripts
########################
script:
  flash_lights:
    sequence:
      - alias: Lights On
        action: light.turn_on
        data:
          entity_id: all
      - delay:
          # time for flash light on
          seconds: 1
      - alias: Lights Off
        action: light.turn_off
        data:
          entity_id: all
      - delay:
          # time for flash light off
          seconds: 1
      - alias: loop_lights
        action: script.turn_on
        data:
          entity_id: script.flash_lights
