################################################################
## Packages / Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "alerts"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: true

    ################################################
    ## Alarm Panels
    ################################################
    alarm_control_panel.home_alarm:
      <<: *customize
      friendly_name: Home Alarm
      icon: mdi:home-alert

    ################################################
    ## Automation
    ################################################
    automation.arm_alarm:
      <<: *customize
      friendly_name: "Arm Home Alarm"
      icon: mdi:home-alert

    automation.disarm_alarm:
      <<: *customize
      friendly_name: "Disarm Home Alarm"
      icon: mdi:home-alert

    automation.motion_detected_on_trip:
      <<: *customize
      friendly_name: "Home Alarm Triggered"
      icon: mdi:home-alert

    automation.send_notification_when_alarm_triggered:
      <<: *customize
      friendly_name: "Notify Home Alarm Triggered"
      icon: mdi:home-alert

    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.flash_lights:
      <<: *customize
      friendly_name: "Flash lights"
      icon: mdi:alarm-light

########################
# Alarm Panel
########################
alarm_control_panel:
  - platform: manual
    name: home_alarm
    code: !secret alarm_code
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 30

########################
# Automations
########################
automation:
  - id: basement_dry
    alias: basement_dry
    # TODO replace this with a AppDaemon app that looks at the distance to the location
    # and decides whether to turn on max range or not.
    trigger:
      - platform: state
        entity_id: binary_sensor.basement_unfinished_leak_water_leak
        from: "on"
        to: "off"
    action:
      - service: persistent_notification.create
        data_template:
          title: Dry floor
          message: "Basement floor is dry."
          notification_id: wet-floor-alert
      - service: notify.all
        data_template:
          message: >-
            Basement floor has dried.

  - id: basement_wet
    alias: basement_wet
    # TODO replace this with a AppDaemon app that looks at the distance to the location
    # and decides whether to turn on max range or not.
    trigger:
      - platform: state
        entity_id: binary_sensor.basement_unfinished_leak_water_leak
        from: "off"
        to: "on"
    action:
      - service: persistent_notification.create
        data_template:
          title: Wet floor
          message: "Basement floor is wet"
          notification_id: wet-floor-alert
      - service: notify.all
        data_template:
          message: >-
            Basement floor is wet. Prop up foam to dry.

  - id: kitchen_wet
    alias: kitchen_wet
    # TODO replace this with a AppDaemon app that looks at the distance to the location
    # and decides whether to turn on max range or not.
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_sink_leak_water_leak
        from: "off"
        to: "on"
    action:
      - service: persistent_notification.create
        data_template:
          title: Wet floor
          message: "Area under kitchen sink is wet"
          notification_id: wet-floor-alert
      - service: notify.all
        data_template:
          message: >-
            Area under kitchen sink is wet. Prop up foam to dry.

  - id: laundry_wet
    alias: laundry_wet
    # TODO replace this with a AppDaemon app that looks at the distance to the location
    # and decides whether to turn on max range or not.
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_leak_water_leak
        from: "off"
        to: "on"
    action:
      - service: persistent_notification.create
        data_template:
          title: Wet floor
          message: "Area under kitchen sink is wet"
          notification_id: wet-floor-alert
      - service: notify.all
        data_template:
          message: >-
            Area under kitchen sink is wet. Prop up foam to dry.

  - id: motion_detected_on_trip
    alias: motion_detected_on_trip
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.basement_door_contact
          - binary_sensor.se_basement_window_contact
          - binary_sensor.sw_basement_window_contact
          - binary_sensor.deck_door_contact
          #        - binary_sensor.downstairs_motion
          - binary_sensor.ene_window_contact
          - binary_sensor.ese_window_contact
          - binary_sensor.front_door_contact
          #        - binary_sensor.hallway_motion
          #        - binary_sensor.master_bedroom_motion
          - binary_sensor.nne_window_contact
          - binary_sensor.north_kitchen_sink_window_contact
          - binary_sensor.north_master_bedroom_window_contact
          - binary_sensor.nw_basement_window_contact
          #        - binary_sensor.office_motion_occupancy
          - binary_sensor.office_north_window_contact
          #        - binary_sensor.motion_sensor_motion
          - binary_sensor.sse_window_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm
      - service: notify.all
        data_template:
          message: >
            Motion detected at {{ trigger.to_state.attributes.friendly_name }} while you're away!
      #    - service: tts.google_say
      #      data:
      #        message: "Intruder Alert! Intruder Alert! You are detected and recorded."
      - service: light.turn_on
        data:
          entity_id: light.living_room_all
          flash: long
      - delay: 00:00:02
      - service: light.turn_on
        data:
          entity_id: light.living_room_all
          flash: long
      - delay: 00:00:02
      - service: light.turn_on
        data:
          entity_id: light.living_room_all
          flash: long

  - alias: send_notification_when_alarm_triggered
    id: send_notification_when_alarm_triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: notify.all
        data_template:
          message: >
            Alarm triggered while you're away

  - alias: send_pic_from_camera
    id: send_pic_from_camera
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.basement_motion_sensor
          - binary_sensor.livingroom_motion_sensor
        from: "off"
        to: "on"
        for:
          seconds: 5
    # condition:
    action:
      - service: notify.mobile_app_wethop
        data_template:
          message: >-
            Stream from {{ trigger.to_state.attributes.friendly_name }}
          entity_id: >-
            {% if trigger.entity_id == "binary_sensor.basement_motion_sensor" %}
              camera.basement
            {% else %}
              camera.livingroom
            {% endif %}

  - alias: arm_alarm
    id: arm_alarm
    trigger:
      - platform: state
        entity_id: binary_sensor.bayesian_zeke_home
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      #    - service: notify.all
      #      data_template:
      #        message: >
      #          Enabled alarm and turned on motion detection
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm
        data:
          code: !secret alarm_code
      - service: switch.turn_on
        entity_id:
          - switch.livingroom_motion_detection
          - switch.basement_motion_detection
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.house_unoccupied

  - alias: disarm_alarm
    id: disarm_alarm
    trigger:
      - platform: state
        entity_id: binary_sensor.bayesian_zeke_home
        from: "off"
        to: "on"
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
        data:
          code: !secret alarm_code
      - service: switch.turn_off
        entity_id:
          - switch.livingroom_motion_detection
          - switch.basement_motion_detection
      #    - service: notify.all
      #      data_template:
      #        message: >
      #          Disabled alarm and turned off motion detection
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.house_unoccupied

  - alias: notify_ios_app
    id: notify_ios_app
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: notify.mobile_app_wethop
        data:
          message: "Something triggered alarm panel at home!"

########################
# Binary Sensors
########################
binary_sensor:

########################
# Groups
########################
group:
  motion_sensors:
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.office_motion_occupancy
      - binary_sensor.owner_suite_occupancy
      - binary_sensor.downstairs_motion
      - binary_sensor.motion_sensor_motion
      - binary_sensor.livingroom_motion_sensor
      - binary_sensor.basement_motion_sensor

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Notify
########################
notify:
  - name: all
    platform: group
    services:
      #    - service: telegram
      - service: mobile_app_faro
      - service: mobile_app_wethop
      - service: mobile_app_rtclauss
      - service: mobile_app_ryans_macbook_pro
      - service: lg_webos_tv_oled65cxpua

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:
  flash_lights:
    sequence:
      - alias: Lights On
        service: light.turn_on
        data:
          entity_id: all
      - delay:
          # time for flash light on
          seconds: 1
      - alias: Lights Off
        service: light.turn_off
        data:
          entity_id: all
      - delay:
          # time for flash light off
          seconds: 1
      - alias: loop_lights
        service: script.turn_on
        data:
          entity_id: script.flash_lights
