################################################################
## Packages / Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alerts'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################
    alarm_control_panel.home_alarm:
      <<: *customize
      friendly_name: Home Alarm
      icon: mdi:home-alert

    ################################################
    ## Automation
    ################################################
    automation.arm_alarm:
      <<: *customize
      friendly_name: "Arm Home Alarm"
      icon: mdi:home-alert
      
    automation.disarm_alarm:
      <<: *customize
      friendly_name: "Disarm Home Alarm"
      icon: mdi:home-alert
      
    automation.motion_detected_on_trip:
      <<: *customize
      friendly_name: "Home Alarm Triggered"
      icon: mdi:home-alert
      
    automation.send_notification_when_alarm_triggered:
      <<: *customize
      friendly_name: "Notify Home Alarm Triggered"
      icon: mdi:home-alert
      
    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.flash_lights:
      <<: *customize
      friendly_name: "Flash lights"
      icon: mdi:alarm-light

########################
# Alarm Panel
########################
alarm_control_panel:
  - platform: manual
    name: home_alarm
    code: !secret alarm_code
    pending_time: 30
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

########################
# Automations
########################
automation:
  - id: motion_detected_on_trip
    alias: motion_detected_on_trip
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.basement_door_contact
        - binary_sensor.se_basement_window_contact
        - binary_sensor.sw_basement_window_contact
        - binary_sensor.deck_door_contact
#        - binary_sensor.downstairs_motion
        - binary_sensor.ene_window_contact
        - binary_sensor.ese_window_contact
        - binary_sensor.front_door_contact
#        - binary_sensor.hallway_motion
#        - binary_sensor.master_bedroom_motion
        - binary_sensor.nne_window_contact
        - binary_sensor.north_kitchen_sink_window_contact
        - binary_sensor.north_master_bedroom_window_contact
        - binary_sensor.nw_basement_window_contact
#        - binary_sensor.office_motion
        - binary_sensor.office_north_window_contact
#        - binary_sensor.motion_sensor_motion
        - binary_sensor.sse_window_contact
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: notify.all
      data_template:
        message: >
          Motion detected at {{ trigger.to_state.attributes.friendly_name }} while you're away!
#    - service: tts.google_say
#      data:
#        message: "Intruder Alert! Intruder Alert! You are detected and recorded."
    - service: light.turn_on
      data:
        entity_id: light.living_room_all
        flash: long
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.living_room_all
        flash: long
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.living_room_all
        flash: long

  - alias: send_notification_when_alarm_triggered
    id: send_notification_when_alarm_triggered
    trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
    action:
    - service: notify.all
      data_template:
        message: >
          Alarm triggered while you're away
          
  - alias: send_pic_from_camera
    id: send_pic_from_camera
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.basement_motion_sensor
        - binary_sensor.livingroom_motion_sensor
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    condition:
    action:
    - service: notify.mobile_app_wethop
      data_template:
        message: > 
          Stream from {{ trigger.to_state.attributes.friendly_name }}
        data:
          push:
            category: camera
          entity_id: >-
            {% if trigger.entity_id == "binary_sensor.basement_motion_sensor" %}
              camera.basement
            {% else %}
              camera.livingroom
            {% endif %}
          
  - alias: arm_alarm
    id: arm_alarm
    trigger:
    - platform: state
      entity_id: binary_sensor.bayesian_zeke_home
      from: 'on'
      to: 'off'
    condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
#    - service: notify.all
#      data_template:
#        message: >
#          Enabled alarm and turned on motion detection
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
      data:
        code: !secret alarm_code
    - service: switch.turn_on
      entity_id:
        - switch.livingroom_motion_detection
        - switch.basement_motion_detection

  - alias: disarm_alarm
    id: disarm_alarm
    trigger:
    - platform: state
      entity_id: binary_sensor.bayesian_zeke_home
      from: 'off'
      to: 'on'
    action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
      data:
         code: !secret alarm_code
    - service: switch.turn_off
      entity_id:
        - switch.livingroom_motion_detection
        - switch.basement_motion_detection
#    - service: notify.all
#      data_template:
#        message: >
#          Disabled alarm and turned off motion detection

  - alias: notify_ios_app
    id: notify_ios_app
    trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
    action:
    - service: notify.mobile_app_wethop
      data:
        message: "Something happened at home!"
        data:
          push:
            badge: 5
            #sound: <SOUND FILE HERE>
            category: "alarm" # Needs to match the top level identifier you used in the ios configuration
          action_data: # Anything passed in action_data will get echoed back to Home Assistant.
            entity_id: light.test
            my_custom_data: foo_bar

########################
# Binary Sensors
########################
binary_sensor:


########################
# Groups
########################
group:
  motion_sensors:
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.office_motion
      - binary_sensor.master_bedroom_motion
      - binary_sensor.downstairs_motion
      - binary_sensor.motion_sensor_motion
      - binary_sensor.livingroom_motion_sensor
      - binary_sensor.basement_motion_sensor

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# iOS
########################
ios:
  push:
    categories:
      - name: alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

########################
# Light
########################
light:

########################
# Notify
########################
notify:
  - name: all
    platform: group
    services:
  #    - service: telegram
      - service: mobile_app_faro
      - service: mobile_app_wethop
      - service: ios_wethop

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:
  flash_lights:
    sequence:
      - alias: Lights On
        service: light.turn_on
        data:
          entity_id: all
      - delay:
          # time for flash light on
          seconds: 1
      - alias: Lights Off
        service: light.turn_off
        data:
          entity_id: all
      - delay:
          # time for flash light off
          seconds: 1
      - alias: loop_lights
        service: script.turn_on
        data:
          entity_id: script.flash_lights
