################################################################
## Packages / Alerts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alerts'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.motion_detected_on_trip:
      <<: *customize
      friendly_name: "Detected motion while on trip"

    ################################################
    ## Binary Sensor
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.flash_lights:
      <<: *customize
      friendly_name: "Flash lights"

########################
# Automations
########################
automation:
  - id: motion_detected_on_trip
    alias: motion_detected_on_trip
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.basement_door_contact
        - binary_sensor.se_basement_window_contact
        - binary_sensor.sw_basement_window_contact
        - binary_sensor.deck_door_contact
        - binary_sensor.downstairs_motion
        - binary_sensor.ene_window_contact
        - binary_sensor.ese_window_contact
        - binary_sensor.front_door_contact
        - binary_sensor.hallway_motion
        - binary_sensor.master_bedroom_motion
        - binary_sensor.nne_window_contact
        - binary_sensor.north_kitchen_sink_window_contact
        - binary_sensor.north_master_bedroom_window_contact
        - binary_sensor.nw_basement_window_contact
        - binary_sensor.office_motion
        - binary_sensor.office_north_window_contact
        - binary_sensor.motion_sensor_motion
        - binary_sensor.sse_window_contact
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: binary_sensor.bayesian_zeke_home
      state: 'off'
    action:
    - service: notify.all
      data_template:
        message: >
          Motion detected at {{ trigger.entity_id }} while you're away!
#    - service: tts.google_say
#      data:
#        message: "Intruder Alert! Intruder Alert! You are detected and recorded."
    - service: light.turn_on
      data:
        entity_id: light.all_living_room
        flash: long
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.all_living_room
        flash: long
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.all_living_room
        flash: long

########################
# Binary Sensors
########################
binary_sensor:


########################
# Groups
########################
group:
  motion_sensors:
    entities:
      - binary_sensor.hallway_motion
      - binary_sensor.office_motion
      - binary_sensor.master_bedroom_motion
      - binary_sensor.downstairs_motion


########################
# Scripts
########################
script:
  flash_lights:
    sequence:
      - alias: Lights On
        service: homeassistant.turn_on
        data:
          entity_id: group.all_lights
      - delay:
          # time for flash light on
          seconds: 1
      - alias: Lights Off
        service: homeassistant.turn_off
        data:
          entity_id: group.all_lights
      - delay:
          # time for flash light off
          seconds: 1
      - alias: loop_lights
        service: script.turn_on
        data:
          entity_id: script.flash_lights
