################################################################
## Packages / Automatic
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'automatic'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.honda_fit_gas_level:
      <<: *customize
      icon: mdi:gas-station
      unit_of_measurement: '%'
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - trigger: 
      - platform: numeric_state
        entity_id: sensor.honda_fit_gas_level
        below: 25
    action:
      - service: persistent_notification.create
        data_template:
          title: Gas Low
          message: "Honda Fit gas at {{ trigger.to_state.state }}% full"
          notification_id: low-battery-alert
      - service: notify.all
        data_template:
          message: >-
            "Honda Fit gas at {{ trigger.to_state.state }}% full"

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
  

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: template
    sensors:
      honda_fit_gas_level:
        value_template: >-
          {{ state_attr('device_tracker.honda_fit', 'fuel_level') }}

########################
# Zone
########################
zone: