################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.notify_battery_dying_20:
      <<: *customize
      icon: mdi:battery-charging-wireless-20
    automation.notify_battery_dying_10:
      <<: *customize
      icon: mdi:battery-charging-wireless-10
    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

################################################
## Automation
################################################
automation:
  - id: notify_battery_dying_20
    alias: notify_battery_dying_20
    trigger:
    - platform: numeric_state
      entity_id: sensor.arrival_sensor_battery, sensor.bathroom_battery, sensor.guest_room_battery, sensor.living_room_battery, sensor.living_room_battery, sensor.master_bedroom_battery, sensor.motion_sensor_battery
      below: 20
      above: 10
    action:
    - service: notify.all
      data_template:
        message: >-
          Battery '{{ trigger.entity_id }}' is below 20%.

  - id: notify_battery_dying_10
    alias: notify_battery_dying_10
    trigger:
    - platform: numeric_state
      entity_id: sensor.arrival_sensor_battery, sensor.bathroom_battery, sensor.guest_room_battery, sensor.living_room_battery, sensor.living_room_battery, sensor.master_bedroom_battery, sensor.motion_sensor_battery
      below: 10
    action:
    - service: notify.all
      data_template:
        message: >-
          Battery '{{ trigger.entity_id }}' is below 10%.

########################
# Binary Sensors
########################
binary_sensor:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  battery_status:
    name: Battery Status
    entities:
      - sensor.living_room_battery 
      - sensor.bathroom_battery
      - sensor.guest_room_battery
      - sensor.master_bedroom_battery
      - sensor.arrival_sensor_battery
      - sensor.motion_sensor_battery

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
