################################################################
## Packages / Batteries
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'batteries'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.notify_battery_dying_20:
      <<: *customize
      friendly_name: "Notify Sensor Battery at 20%"
      icon: mdi:battery-charging-wireless-20

    automation.notify_battery_dying_10:
      <<: *customize
      friendly_name: "Notify Sensor Battery at 10%"
      icon: mdi:battery-charging-wireless-10
      
    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

################################################
## Automation
################################################
automation:
  - id: notify_battery_dying_20
    alias: notify_battery_dying_20
    trigger:
    - platform: numeric_state
      entity_id:
        - sensor.arrival_sensor_battery
        - sensor.basement_door_battery
        - sensor.bathroom_battery
        - sensor.deck_door_battery
        - sensor.downstairs_motion_battery
        - sensor.ene_window_battery
        - sensor.ese_window_battery
        - sensor.front_door_battery
        - sensor.guest_room_button_battery
        - sensor.guest_room_battery
        - sensor.living_room_battery
        - sensor.living_room_button_battery
        - sensor.master_bedroom_battery
        - sensor.master_bedroom_motion_battery
        - sensor.motion_sensor_battery
        - sensor.north_kitchen_sink_window_battery
        - sensor.north_master_bedroom_window_battery
        - sensor.nne_window_battery
        - sensor.nw_basement_window_battery
        - sensor.office_motion_battery
        - sensor.office_north_window_battery
        - sensor.se_basement_window_battery
        - sensor.sw_basement_window_battery
      below: 20
      above: 10
    action:
    - service: persistent_notification.create
      data_template:
        title: Low Battery
        message: "Battery {{  trigger.from_state.attributes.friendly_name }} is below 20%"
        notification_id: low-battery-alert
    - service: notify.all
      data_template:
        message: >-
          Battery '{{ trigger.from_state.attributes.friendly_name }}' is below 20%.

  - id: notify_battery_dying_10
    alias: notify_battery_dying_10
    trigger:
    - platform: numeric_state
      entity_id:
        - sensor.arrival_sensor_battery
        - sensor.basement_door_battery
        - sensor.bathroom_battery
        - sensor.deck_door_battery
        - sensor.downstairs_motion_battery
        - sensor.ene_window_battery
        - sensor.ese_window_battery
        - sensor.front_door_battery
        - sensor.guest_room_button_battery
        - sensor.guest_room_battery
        - sensor.living_room_battery
        - sensor.living_room_button_battery
        - sensor.master_bedroom_battery
        - sensor.master_bedroom_motion_battery
        - sensor.motion_sensor_battery
        - sensor.north_kitchen_sink_window_battery
        - sensor.north_master_bedroom_window_battery
        - sensor.nne_window_battery
        - sensor.nw_basement_window_battery
        - sensor.office_motion_battery
        - sensor.office_north_window_battery
        - sensor.se_basement_window_battery
        - sensor.sw_basement_window_battery
      below: 10
    action:
      - service: persistent_notification.create
      data_template:
        title: Low Battery
        message: "Battery {{  trigger.from_state.attributes.friendly_name }} is below 10%"
        notification_id: low-battery-alert
      - service: notify.all
      data_template:
        message: >-
          Battery '{{ trigger.from_state.attributes.friendly_name }}' is below 10%.

########################
# Binary Sensors
########################
binary_sensor:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  battery_status:
    name: Battery Status
    entities:
      - sensor.arrival_sensor_battery
      - sensor.basement_door_battery
      - sensor.bathroom_battery
      - sensor.deck_door_battery
      - sensor.downstairs_motion_battery
      - sensor.ene_window_battery
      - sensor.ese_window_battery
      - sensor.front_door_battery
      - sensor.guest_room_button_battery
      - sensor.guest_room_battery
      - sensor.hallway_motion_battery
      - sensor.living_room_battery
      - sensor.living_room_button_battery
      - sensor.master_bedroom_battery
      - sensor.master_bedroom_motion_battery
      - sensor.motion_sensor_battery
      - sensor.north_kitchen_sink_window_battery
      - sensor.north_master_bedroom_window_battery
      - sensor.nne_window_battery
      - sensor.nw_basement_window_battery
      - sensor.office_motion_battery
      - sensor.office_north_window_battery
      - sensor.se_basement_window_battery
      - sensor.sw_basement_window_battery

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
