################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "TO_CHANGE"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Climate
    ################################################

    ################################################
    ## Covers
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ##  Notify
    ################################################

    ################################################
    ##  Octoprint
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Weather
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Climate
########################
climate:

########################
# Covers
########################
cover:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input DateTime
########################
input_datetime:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# MQTT
########################
mqtt:
  - sensor:
      - name: "Garden Birds"
        state_topic: "birdpi/apprise"
        json_attributes_topic: "birdpi/apprise"
        value_template: "{{ value_json.common_name }}"

########################
# Notify
########################
notify:

########################
# Octoprint
########################
# YAML Deprecated 2022.2
# octoprint:

########################
# Plant
########################
plant:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: rest
    name: Top 50 Bird Species
    resource: https://app.birdweather.com/api/v1/stations/v13SVjSLeUURwbirfciJoN71/species/?period=day&limit=50

    value_template: "{{ value_json.species[0].commonName }}"
    json_attributes:
      - species

  - platform: rest
    name: Latest Bird Detection
    resource: https://app.birdweather.com/api/v1/stations/v13SVjSLeUURwbirfciJoN71/detections/?limit=1
    value_template: >
      {% if value_json.detections and value_json.detections | length > 0 %}
        {{ value_json.detections[0].species.commonName }}
      {% else %}
        No detections
      {% endif %}
    json_attributes:
      - detections

########################
# Switch
########################
switch:

########################
# Template
########################
template:
  - image:
      - name: Bird-Pi Photo
        verify_ssl: false
        url: "{{ state_attr('sensor.garden_birds','image') }}"
########################
# Weather
########################
weather:

########################
# Zone
########################
zone:
