################################################################
## Packages / Camera
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.basement_motion_sensor:
      <<: *customize
      device_class: motion
      friendly_name: "Basement Camera Motion"

    binary_sensor.livingroom_motion_sensor:
      <<: *customize
      device_class: motion
      friendly_name: "Living Room Camera Motion"

    ################################################
    ## Cameras
    ################################################
    camera.basement:
      <<: *customize
      friendly_name: "Basement Camera"
      icon: mdi:cctv

    camera.livingroom:
      <<: *customize
      friendly_name: "Living Room Camera"
      icon: mdi:cctv
      
    camera.livingroom_motion_snapshot:
      <<: *customize
      friendly_name: "Living Room Motion Snapshot"
      icon: mdi:cctv

    camera.basement_motion_snapshot:
      <<: *customize
      friendly_name: "Basement Motion Snapshot"
      icon: mdi:cctv

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################
    group.all_cameras:
      <<: *customize
      friendly_name: All Camera Info
    
    group.basement_camera_status:
      <<: *customize
      friendly_name: Basement Camera Status
      
    group.livingroom_camera_status:
      <<: *customize
      friendly_name: Living Room Camera Status

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################
    switch.basement_blue_led:
      <<: *customize
      friendly_name: "Basement Blue LED"

    switch.basement_h264_rtsp_server:
      <<: *customize
      friendly_name: "Basement RTSP H264"

    switch.basement_ir_filter:
      <<: *customize
      friendly_name: "Basement IR Filter"
      
    switch.basement_ir_led:
      <<: *customize
      friendly_name: "Basement IR LED"

    switch.basement_mjpeg_rtsp_server:
      <<: *customize
      friendly_name: "Basement RTSP MJPEG"
    
    switch.basement_motion_detection:
      <<: *customize
      friendly_name: "Basement Motion Detection"
      
    switch.basement_motion_tracking:
      <<: *customize
      friendly_name: "Basement Motion Tracking"
      
    switch.basement_night_mode:
      <<: *customize
      friendly_name: "Basement Night Mode"
      
    switch.basement_night_mode_auto:
      <<: *customize
      friendly_name: "Basement Auto Night Mode"

    switch.basement_yellow_led:
      <<: *customize
      friendly_name: "Basement Yellow LED"
      
    switch.livingroom_blue_led:
      <<: *customize
      friendly_name: "Living Room Blue LED"
    
    switch.livingroom_h264_rtsp_server:
      <<: *customize
      friendly_name: "Living Room RTSP H264"
      
    switch.livingroom_mjpeg_rtsp_server:
      <<: *customize
      friendly_name: "Living Room RTSP MJPEG"
      
    switch.livingroom_ir_filter:
      <<: *customize
      friendly_name: "Living Room IR Filter"
      
    switch.livingroom_ir_led:
      <<: *customize
      friendly_name: "Living Room IR LED"
      
    switch.livingroom_motion_detection:
      <<: *customize
      friendly_name: "Living Room Motion Detection"
      
    switch.livingroom_motion_tracking:
      <<: *customize
      friendly_name: "Living Room Motion Tracking"
      
    switch.livingroom_night_mode:
      <<: *customize
      friendly_name: "Living Room Night Mode"
      
    switch.livingroom_night_mode_auto:
      <<: *customize
      friendly_name: "Living Room Auto Night Mode"

    switch.livingroom_yellow_led:
      <<: *customize
      friendly_name: "Living Room Yellow LED"


    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:
  - platform: ffmpeg
    name: basement
    input: -rtsp_transport tcp -i rtsp://basementcam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    
  - platform: ffmpeg
    name: livingroom
    input: -rtsp_transport tcp -i rtsp://livingroomcam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:
  all_cameras:
    entities:
      - group.livingroom_camera_status
      - camera.livingroom
      - group.basement_camera_status
      - camera.basement
      - camera.livingroom_motion_snapshot
      - camera.basement_motion_snapshot
      
  basement_camera_status:
    entities:
      - switch.basement_motion_detection
      - switch.basement_motion_tracking
      - switch.basement_night_mode
      - switch.basement_night_mode_auto
      - switch.basement_ir_filter
      - switch.basement_ir_led
      - switch.basement_mjpeg_rtsp_server
      - switch.basement_h264_rtsp_server
      - switch.basement_blue_led
      - switch.basement_yellow_led
      - cover.basement_move_leftright
      - cover.basement_move_updown
      
  livingroom_camera_status:
    entities:
      - switch.livingroom_motion_detection
      - switch.livingroom_motion_tracking
      - switch.livingroom_night_mode
      - switch.livingroom_night_mode_auto
      - switch.livingroom_ir_filter
      - switch.livingroom_ir_led
      - switch.livingroom_mjpeg_rtsp_server
      - switch.livingroom_h264_rtsp_server
      - switch.livingroom_blue_led
      - switch.livingroom_yellow_led
      - cover.livingroom_move_leftright
      - cover.livingroom_move_updown

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switches
########################
switch:
    
########################
# Zone
########################
zone: