################################################################
## Packages / Camera
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.basement_cam_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Basement Camera Motion"

    binary_sensor.living_room_cam_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Living Room Camera Motion"

    ################################################
    ## Cameras
    ################################################
    camera.basement_cam:
      <<: *customize
      friendly_name: "Basement Camera"
      icon: mdi:cctv

    camera.living_room_cam:
      <<: *customize
      friendly_name: "Living Room Camera"
      icon: mdi:cctv
      
    camera.living_room_cam_motion_detection_image:
      <<: *customize
      friendly_name: "Living Room Motion"
      icon: mdi:cctv

    camera.basement_cam_motion_detection_image:
      <<: *customize
      friendly_name: "Basement Motion"
      icon: mdi:cctv

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################
    group.all_cameras:
      <<: *customize
      friendly_name: All Camera Info
    group.basement_camera_status:
      <<: *customize
      friendly_name: Basement Camera Status
    group.living_room_camera_status:
      <<: *customize
      friendly_name: Living Room Camera Status

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################
    switch.basement_cam_blue_led:
      <<: *customize
      friendly_name: "Basement Blue LED"

    switch.basement_cam_motion_detection:
      <<: *customize
      friendly_name: "Basement Motion Detection"

    switch.basement_cam_yellow_led:
      <<: *customize
      friendly_name: "Basement Yellow LED"
      
    switch.basement_cam_RTSP_H264:
      <<: *customize
      friendly_name: "Basement RTSP H264"
      
    switch.basement_cam_RTSP_MJPEG:
      <<: *customize
      friendly_name: "Basement RTSP MJPEG"
      
    switch.living_room_cam_blue_led:
      <<: *customize
      friendly_name: "Living Room Blue LED"
      
    switch.living_room_cam_motion_detection:
      <<: *customize
      friendly_name: "Living Room Motion Detection"
    
    switch.living_room_cam_yellow_led:
      <<: *customize
      friendly_name: "Living Room Yellow LED"
      
    switch.living_room_cam_RTSP_H264:
      <<: *customize
      friendly_name: "Living Room RTSP H264"
      
    switch.living_room_cam_RTSP_MJPEG:
      <<: *customize
      friendly_name: "Living Room RTSP MJPEG"

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:
  - platform: mqtt
    name: basement_cam_motion
    state_topic: "topic/basement_cam/motion"
    payload_on: "ON"
    payload_off: "OFF"
    
  - platform: mqtt
    name: living_room_cam_motion
    state_topic: "topic/livingroom_cam/motion"
    payload_on: "ON"
    payload_off: "OFF"


########################
# Cameras
########################
camera:
  - platform: ffmpeg
    name: basement_cam
    input: -rtsp_transport tcp -i rtsp://basement_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    
  - platform: ffmpeg
    name: living_room_cam
    input: -rtsp_transport tcp -i rtsp://livingroom_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    
  - platform: mqtt
    name: living_room_cam_motion_detection_image
    topic: "topic/livingroom_cam/motion_snapshots"

  - platform: mqtt
    name: basement_cam_motion_detection_image
    topic: "topic/basement_cam/motion_snapshots"


########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:
  all_cameras:
    entities:
      - group.living_room_camera_status
      - camera.living_room_cam
      - group.basement_camera_status
      - camera.basement_cam
      - camera.living_room_cam_motion_detection_image
      - camera.basement_cam_motion_detection_image
      
  basement_camera_status:
    entities:
      - switch.basement_cam_blue_led
      - switch.basement_cam_yellow_led
      - switch.basement_cam_motion_detection
      - switch.basement_cam_RTSP_H264
      - switch.basement_cam_RTSP_MJPEG
      
  living_room_camera_status:
    entities:
      - switch.living_room_cam_blue_led
      - switch.living_room_cam_yellow_led
      - switch.living_room_cam_motion_detection
      - switch.living_room_cam_RTSP_H264
      - switch.living_room_cam_RTSP_MJPEG

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switches
########################
switch:
  - platform: mqtt
    name: basement_cam_blue_led
    state_topic: "topic/basement_cam/leds/blue"
    command_topic: "topic/basement_cam/leds/blue/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: basement_cam_motion_detection
    state_topic: "topic/basement_cam/motion/detection"
    command_topic: "topic/basement_cam/motion/detection/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    
  - platform: mqtt
    name: basement_cam_yellow_led
    state_topic: "topic/basement_cam/leds/yellow"
    command_topic: "topic/basement_cam/leds/yellow/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: basement_cam_RTSP_H264
    state_topic: "topic/basement_cam/rtsp_server"
    command_topic: "topic/basement_cam/rtsp_server/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: basement_cam_RTSP_MJPEG
    state_topic: "topic/basement_cam/rtsp_server"
    command_topic: "topic/basement_cam/rtsp_server/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    
  - platform: mqtt
    name: living_room_cam_blue_led
    state_topic: "topic/livingroom_cam/leds/blue"
    command_topic: "topic/livingroom_cam/leds/blue/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    

  - platform: mqtt
    name: living_room_cam_motion_detection
    state_topic: "topic/livingroom_cam/motion/detection"
    command_topic: "topic/livingroom_cam/motion/detection/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: living_room_cam_yellow_led
    state_topic: "topic/livingroom_cam/leds/yellow"
    command_topic: "topic/livingroom_cam/leds/yellow/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: living_room_cam_RTSP_H264
    state_topic: "topic/livingroom_cam/rtsp_server"
    command_topic: "topic/livingroom_cam/rtsp_server/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

  - platform: mqtt
    name: living_room_cam_RTSP_MJPEG
    state_topic: "topic/livingroom_cam/rtsp_server"
    command_topic: "topic/livingroom_cam/rtsp_server/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    
########################
# Zone
########################
zone: