################################################################
## Packages / Camera
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################
    camera.basement_cam:
      <<: *customize
      friendly_name: "Basement Camera"
      icon: mdi:cctv

    camera.livingroom_cam:
      <<: *customize
      friendly_name: "Living Room Camera"
      icon: mdi:cctv

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:
  - platform: ffmpeg
    name: basement_cam
    input: -rtsp_transport tcp -i rtsp://basement_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    
  - platform: ffmpeg
    name: livingroom_cam
    input: -rtsp_transport tcp -i rtsp://livingroom_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:
  all_cameras:
    entities:
      - camera.livingroom_cam
      - camera.basement_cam

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Zone
########################
zone: