################################################################
## Packages / Camera
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################
    camera.basement_cam:
      <<: *customize
      friendly_name: "Basement Camera"
      icon: mdi:cctv

    camera.livingroom_cam:
      <<: *customize
      friendly_name: "Living Room Camera"
      icon: mdi:cctv

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################
    group.all_cameras:
      <<: *customize
      friendly_name: All Camera Info
    group.basement_camera_status:
      <<: *customize
      friendly_name: Basement Camera Status
    group.livingroom_camera_status:
      <<: *customize
      friendly_name: Living Room Camera Status

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################
    switch.basement_cam_blue_led:
      <<: *customize
      friendly_name: "Basement Blue LED"
      
    switch.basement_cam_yellow_led:
      <<: *customize
      friendly_name: "Basement Yellow LED"
      
    switch.basement_cam_RTSP_H264:
      <<: *customize
      friendly_name: "Basement RTSP H264"
      
    switch.basement_cam_RTSP_MJPEG:
      <<: *customize
      friendly_name: "Basement RTSP MJPEG"
      
    switch.livingroom_cam_blue_led:
      <<: *customize
      friendly_name: "Living Room Blue LED"
      
    switch.livingroom_cam_yellow_led:
      <<: *customize
      friendly_name: "Living Room Yellow LED"
      
    switch.livingroom_cam_RTSP_H264:
      <<: *customize
      friendly_name: "Living Room RTSP H264"
      
    switch.livingroom_cam_RTSP_MJPEG:
      <<: *customize
      friendly_name: "Living Room RTSP MJPEG"

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:
  - platform: ffmpeg
    name: basement_cam
    input: -rtsp_transport tcp -i rtsp://basement_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg
    
  - platform: ffmpeg
    name: livingroom_cam
    input: -rtsp_transport tcp -i rtsp://livingroom_cam.lan:8554/unicast
    ffmpeg_bin: /usr/local/bin/ffmpeg

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:
  all_cameras:
    entities:
      - group.livingroom_camera_status
      - camera.livingroom_cam
      - group.basement_camera_status
      - camera.basement_cam
      
  basement_camera_status:
    entities:
      - switch.basement_cam_blue_led
      - switch.basement_cam_yellow_led
      - switch.basement_cam_RTSP_H264
      - switch.basement_cam_RTSP_MJPEG
      
  livingroom_camera_status:
    entities:
      - switch.basement_cam_blue_led
      - switch.basement_cam_yellow_led
      - switch.basement_cam_RTSP_H264
      - switch.basement_cam_RTSP_MJPEG

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switches
########################
switch:
  - platform: mqtt
    name: basement_cam_blue_led
    state_topic: "topic/basement_cam/status"
    value_template: '{{ value_json["LEDs"]["Blue"] }}'
    command_topic: "topic/basement_cam/Blue_LED/set"
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    
  - platform: mqtt
    name: basement_cam_yellow_led
    state_topic: "topic/basement_cam/status"
    value_template: '{{ value_json["LEDs"]["Yellow"] }}'
    command_topic: "topic/basement_cam/Yellow_LED/set"
    payload_on: "on"
    payload_off: "off"
    optimistic: false

  - platform: mqtt
    name: basement_cam_RTSP_H264
    state_topic: "topic/basement_cam/status"
    value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}h264_start{% else %}rtsp_stop{% endif %}"
    command_topic: "topic/basement_cam/set"
    payload_on: "h264_start"
    payload_off: "rtsp_stop"
    optimistic: false

  - platform: mqtt
    name: basement_cam_RTSP_MJPEG
    state_topic: "topic/basement_cam/status"
    value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}mjpeg_start{% else %}rtsp_stop{% endif %}"
    command_topic: "topic/basement_cam/set"
    payload_on: "mjpeg_start"
    payload_off: "rtsp_stop"
    optimistic: false
    
  - platform: mqtt
    name: livingroom_cam_blue_led
    state_topic: "topic/livingroom_cam/status"
    value_template: '{{ value_json["LEDs"]["Blue"] }}'
    command_topic: "topic/basement_cam/Blue_LED/set"
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    
  - platform: mqtt
    name: livingroom_cam_yellow_led
    state_topic: "topic/livingroom_cam/status"
    value_template: '{{ value_json["LEDs"]["Yellow"] }}'
    command_topic: "topic/basement_cam/Yellow_LED/set"
    payload_on: "on"
    payload_off: "off"
    optimistic: false

  - platform: mqtt
    name: livingroom_cam_RTSP_H264
    state_topic: "topic/livingroom_cam/status"
    value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}h264_start{% else %}rtsp_stop{% endif %}"
    command_topic: "topic/livingroom_cam/set"
    payload_on: "h264_start"
    payload_off: "rtsp_stop"
    optimistic: false

  - platform: mqtt
    name: livingroom_cam_RTSP_MJPEG
    state_topic: "topic/livingroom_cam/status"
    value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}mjpeg_start{% else %}rtsp_stop{% endif %}"
    command_topic: "topic/livingroom_cam/set"
    payload_on: "mjpeg_start"
    payload_off: "rtsp_stop"
    optimistic: false
    
########################
# Zone
########################
zone: