################################################################
## Packages / Car
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "car"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Cover
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.car_in_motion:
      <<: *customize
      icon: mdi:car
      class: motion

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

################################################
## Thermostats
################################################

################################################
## Zone
################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: turn_on_max_range_charge
    alias: turn_on_max_range_charge
    # TODO replace this with a AppDaemon app that looks at the distance to the location
    # and decides whether to turn on max range or not.
    trigger:
      - platform: state
        entity_id: binary_sensor.trip_in_six_hours
        from: "off"
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.ice_maxrange_switch
      - service: persistent_notification.create
        data_template:
          title: Max Charge
          message: "Long-range trip soon. Charging to the EXTREME!"
          notification_id: low-battery-alert
      - service: notify.all
        data_template:
          message: >-
            "Long-range trip soon. Charging to the EXTREME!"

  - id: garage_door_reminder
    alias: Close forgotten garage door
    trigger:
      - platform: state
        entity_id: cover.garage_door_opener
        to: open
    condition:
      - condition: time
        after: "23:30:00"
    action:
      - service: notify.all
        data:
          message: Close the garage door.

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      trip_in_six_hours:
        value_template: >-
          {% if 
            (now() >= ((state_attr("calendar.ryan_claussen", "start_time") | as_datetime|as_local) - (timedelta(hours=8)))) 
          or 
            (now() >= ((state_attr("calendar.work_trip",     "start_time") | as_datetime|as_local) - (timedelta(hours=8))))
          and
            (states("sensor.waze_next_trip_distance")|int > 45)
          %}
            true
          {% else %}
            false
          {% endif %}

########################
# Cameras
########################
camera:

########################
# Cover
########################
cover:
  # Removed and moved to UI config
  # - platform: myq
  #   username: !secret myq_user
  #   password: !secret myq_password
  #   type: chamberlain

########################
# Device Trackers
########################
device_tracker:
  - platform: traccar
    host: !secret traccar_ip
    port: 80
    username: !secret traccar_user
    password: !secret traccar_password
    monitored_conditions: ["dirOfTravel"]
    event: ["ignition_on", "ignition_off"]
    scan_interval: 10

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  car_in_motion:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: waze_travel_time
    name: "Waze Next trip distance"
    origin: device_tracker.bayesian_zeke_home
    destination: sensor.calendar_destination
    region: "US"

  - platform: template
    sensors:
      calendar_destination:
        friendly_name: "Next Calendar Destination"
        value_template: >-
          {% set personal_meeting_time = (state_attr("calendar.ryan_claussen", "start_time") | as_datetime|as_local) %}
          {% set work_meeting_time = (state_attr("calendar.work_trip", "start_time") | as_datetime|as_local) %}
          {% if "-" in ((personal_meeting_time - work_meeting_time)|string) %}
            {{ state_attr("calendar.ryan_claussen", "location") }}
          {% else %}
            {{ state_attr("calendar.work_trip", "location") }}
          {% endif %}

      next_trip_distance:
        friendly_name: "Distance to next destination"
        unit_of_measurement: "mi"
        value_template: >-
          {{ state_attr("sensor.waze_next_trip_distance", "distance") | int }}
########################
# Zone
########################
zone:
