################################################################
## Packages / Car
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "car"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Cover
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.car_in_motion:
      <<: *customize
      icon: mdi:car
      class: motion


    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
#    sensor.honda_fit_gas_level:
#      <<: *customize
#      icon: mdi:gas-station
#      unit_of_measurement: '%'
################################################
## Thermostats
################################################

################################################
## Zone
################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: send_notification_gas_level
    alias: send_notification_gas_level
    trigger:
      - platform: numeric_state
        entity_id: sensor.honda_fit_gas_level
        below: 25
    action:
      - service: persistent_notification.create
        data_template:
          title: Gas Low
          message: "Honda Fit gas at {{ trigger.to_state.state }}% full"
          notification_id: low-battery-alert
      - service: notify.all
        data_template:
          message: >-
            "Honda Fit gas at {{ trigger.to_state.state }}% full"

  - id: garage_door_reminder
    alias: Close forgotten garage door
    trigger:
      - platform: state
        entity_id: cover.garage_door_opener
        to: open
    condition:
      - condition: time
        after: "23:30:00"
    action:
      - service: notify.all
        data:
          message: Close the garage door.

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Cover
########################
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain

########################
# Device Trackers
########################
device_tracker:
  - platform: traccar
    host: !secret traccar_ip
    port: 80
    username: !secret traccar_user
    password: !secret traccar_password
    monitored_conditions: ["dirOfTravel"]
    event: ["ignition_on", "ignition_off"]
    scan_interval: 10

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  car_in_motion:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
#  - platform: template
#    sensors:
#      honda_fit_gas_level:
#        value_template: >-
#          {{ state_attr('device_tracker.honda_fit', 'fuel_level') }}

########################
# Zone
########################
zone:
