################################################################
## Packages / Christmas
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "christmas"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    automation.christmas_tree_on:
      <<: *customize
      friendly_name: "Turn on Christmas Tree"

    automation.christmas_tree_off_midnight:
      <<: *customize
      friendly_name: "Turn off Christmas Tree"

    automation.christmas_lights_off_bedroom_off:
      <<: *customize
      friendly_name: "Turn off Christmas Tree if bedroom lights turned off"

    automation.toggle_christmas_automations_on_season_change:
      <<: *customize
      friendly_name: "Display Christmas tab"

    automation.toggle_christmas_tab:
      <<: *customize
      friendly_name: "Display Christmas tab"

    ################################################
    ## Binary Sensors
    ################################################

    binary_sensor.christmas_season:
      <<: *customize
      friendly_name: "Christmas Season"
      icon: mdi:calendar

    ################################################
    ## Groups
    ################################################

    group.christmas_lights:
      <<: *customize
      friendly_name: "Christmas Sensors"

    group.christmas_automations:
      <<: *customize
      friendly_name: "Christmas Automations"

    ################################################
    ## Scripts
    ################################################
    script.toggle_christmas_automation_during_christmas_season:
      <<: *customize
      friendly_name: "Toggle Christmas Automation Based on Boolean Sensor"

    ################################################
    ## Switches
    ################################################
    switch.christmas_tree:
      <<: *customize
      friendly_name: "Christmas Tree"
      icon: mdi:pine-tree

########################
# Automations
########################
automation:
  - id: christmas_tree_on
    alias: christmas_tree_on
    initial_state: false
    trigger:
      - platform: sun
        event: sunset
        offset: -00:45:00
    action:
      - service: switch.turn_on
        entity_id: switch.christmas_tree
      - service: light.turn_on
        entity_id: light.christmas_lights
      - service: notify.all
        data:
          message: Turning on Christmas Tree.

  - id: christmas_tree_off_midnight
    alias: christmas_tree_off_midnight
    initial_state: false
    trigger:
      - platform: time
        at: 00:00:00
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_tree
      - service: light.turn_off
        entity_id: light.christmas_lights
      - service: notify.all
        data:
          message: Turning off Christmas Tree.

  - id: christmas_lights_off_bedroom_off
    alias: christmas_lights_off_bedroom_off
    initial_state: false
    trigger:
      - platform: state
        entity_id: light.bedroom_lamp, light.bedroom_lamp_2
        to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_tree
      - service: light.turn_off
        entity_id: light.christmas_lights

  - id: christmas_outside_light_loop_1
    alias: christmas_outside_light_loop_1
    # initial_state: false
    trigger:
      - platform: sun
        event: sunset
        offset: -00:45:00
      - platform: time_pattern
        minutes: "/1"
    condition:
      - alias: "Christmas-time"
        condition: state
        entity_id: binary_sensor.christmas_season
        state: "on"
      - condition: or
        conditions:
          - alias: "Sunset"
            condition: sun
            after: sunset
            after_offset: -00:45:00
          - alias: "Sunrise"
            condition: sun
            before: sunrise
            before_offset: 00:45:00
    action:
      - service: scene.turn_on
        data_template:
          transition: 30
          entity_id: scene.scene_christmas_outdoors_{{ now().minute % 4 + 1 | int }}
          # toggle between christmas scenes 1-4

  - id: toggle_christmas_automations_on_season_change
    alias: toggle_christmas_automations_on_season_change
    trigger:
      - platform: state
        entity_id: binary_sensor.christmas_season
      - platform: homeassistant
        event: start
    condition:
      - alias: "It's christmas"
        condition: state
        entity_id: binary_sensor.christmas_season
        state: "on"
    action:
      - service: script.toggle_christmas_automation_during_christmas_season
        data:
          entity_id: automation.christmas_tree_on
      - service: script.toggle_christmas_automation_during_christmas_season
        data:
          entity_id: automation.christmas_tree_off_midnight
      - service: script.toggle_christmas_automation_during_christmas_season
        data:
          entity_id: automation.christmas_lights_off_bedroom_off
      - service: script.toggle_christmas_automation_during_christmas_season
        data:
          entity_id: automation.outside_light_loop_1

  # - id: toggle_christmas_tab
  #   alias: toggle_christmas_tab
  #   trigger:
  #   - platform: state
  #     entity_id: binary_sensor.christmas_season
  #   - platform: homeassistant
  #     event: start
  #   condition: []
  #   action:
  #   - delay: '00:00:{{ (range(1,60)|random|int) }}'
  #   - service: script.toggle_view
  #     data_template:
  #       view_id: christmas
  #       visible: >-
  #         {{ is_state("binary_sensor.christmas_season", 'on') | lower }}

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      christmas_season:
        value_template: >-
          {{ now().strftime("%m") |int in [12] }}

########################
# Groups
########################
group:
  christmas_lights:
    entities:
      - switch.christmas_tree
      - light.christmas_lights
  christmas_automations:
    entities:
      - automation.christmas_tree_on
      - automation.christmas_tree_off_midnight
      - automation.christmas_lights_off_bedroom_off

########################
# Light
########################
light:
  # - platform: switch
  #   name: Christmas Lights
  #   entity_id: switch.christmas_lights

########################
# Scenes
########################
scene:
  - name: scene_christmas_outdoors_1
    entities:
      light.outside_front_door:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
      light.outside_north_west_garage:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
      light.outside_south_west_garage:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
  - name: scene_christmas_outdoors_2
    entities:
      light.outside_front_door:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
      light.outside_north_west_garage:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
      light.outside_south_west_garage:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
  - name: scene_christmas_outdoors_3
    entities:
      light.outside_front_door:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
      light.outside_north_west_garage:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
      light.outside_south_west_garage:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
  - name: scene_christmas_outdoors_4
    entities:
      light.outside_front_door:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
      light.outside_north_west_garage:
        state: "on"
        rgb_color: [0, 255, 0] # Green
        brightness: 255
      light.outside_south_west_garage:
        state: "on"
        rgb_color: [255, 0, 0] # Red
        brightness: 255
########################
# Scripts
########################
script:
  toggle_christmas_automation_during_christmas_season:
    sequence:
      - service: >-
          {% if is_state("binary_sensor.christmas_season", 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: "{{ entity_id }}"
