
########################
# Automations
########################
automation:
  - id: christmas_tree_on
    alias: Turn on Christmas Tree
    initial_state: false
    trigger:
    - platform: sun
      event: sunset
      offset: -00:45:00
    action:
    - service: homeassistant.turn_on
      entity_id: switch.christmas_tree, light.christmas_lights
    - service: notify.telegram
      data:
        message: Turning on Christmas Tree.
  - id: christmas_tree_off_midnight
    alias: Turn off Christmas Tree
    initial_state: false
    trigger:
    - platform: time
      at: 00:00:00
    action:
    - service: homeassistant.turn_off
      entity_id: switch.christmas_tree, light.christmas_lights
    - service: notify.telegram
      data:
        message: Turning off Christmas Tree.
  - id: christmas_lights_off_bedroom_off
    alias: Turn off Christmas Tree if bedroom lights turned off.
    initial_state: false
    trigger:
    - platform: state
      entity_id: light.bedroom_lamp, light.bedroom_lamp_2
      to: 'off'
    action:
    - service: homeassistant.turn_off
      entity_id: switch.christmas_tree, light.christmas_lights
