################################################################
## Packages / Cleaning
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "cleaning"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.dishwasher:
      <<: *customize
      icon: mdi:dishwasher
      device_class: vibration
      friendly_name: "Dishwasher Vibration"

    binary_sensor.dishwasher_running:
      <<: *customize
      icon: mdi:dishwasher
      device_class: vibration
      friendly_name: "Dishwasher Running"

    binary_sensor.dryer:
      <<: *customize
      icon: mdi:tumble-dryer
      device_class: vibration
      friendly_name: "Dryer Vibration"

    binary_sensor.dryer_running:
      <<: *customize
      icon: mdi:tumble-dryer
      device_class: vibration
      friendly_name: "Dryer Running"

    binary_sensor.washer:
      <<: *customize
      icon: mdi:washing-machine
      device_class: vibration
      friendly_name: "Washer Vibration"

    binary_sensor.washer_door:
      <<: *customize
      icon: mdi:washing-machine
      device_class: door
      friendly_name: "Washer Door"

    binary_sensor.washing_machine_running:
      <<: *customize
      icon: mdi:washing-machine
      device_class: vibration
      friendly_name: "Washer Running"

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.dishwasher:
      <<: *customize
      icon: mdi:dishwasher
      friendly_name: "Dishwasher Vibration"

    sensor.washer:
      <<: *customize
      icon: mdi:washer
      friendly_name: "Washer Vibration"

    sensor.dryer:
      <<: *customize
      icon: mdi:tumble-dryer
      friendly_name: "Dryer Vibration"

    sensor.washer_state:
      <<: *customize
      icon: mdi:washer
      friendly_name: "Washing Machine"


    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: washer_reminder
    alias: washer_reminder
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_door
        to: "off"
        for:
          hours: 18
    action:
      - service: notify.all
        data:
          message: "Clothes still in washing machine.  Get them out before they turn musty! \U0001F9FA"

  - id: empty_vacuum_on_thursday
    alias: empty_vacuum_on_thursday
    trigger:
      - platform: zone
        entity_id: person.ryan
        zone: zone.home
        event: enter
      - platform: state
        entity_id: person.ryan
        to: "home"
    condition:
      condition: time
      weekday:
        - thu
    action:
      - delay: 00:10:00
      - service: vacuum.send_command
        entity_id: vacuum.xiaomi_vacuum_cleaner
        data:
          command: "go_to"
          params:
            spot_id: "Garbage"

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      dishwasher_running:
        #friendly_name: "Washing Machine"
        delay_off:
          minutes: 10
        delay_on:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.dishwasher', 'on') }}

  - platform: template
    sensors:
      dryer_running:
        #friendly_name: "Washing Machine"
        delay_off:
          minutes: 10
        delay_on:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.dryer', 'on') }}

  - platform: template
    sensors:
      washing_machine_running:
        #friendly_name: "Washing Machine"
        delay_off:
          minutes: 10
        delay_on:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.washer', 'on') }}

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:
  washer_state:
    name: Washer State
    options:
      - IDLE
      - CLEANING
      - CLEAN
      - MUSTY
    icon: mdi:washing-machine
########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    name: xiaomi_map
    value_template: "OK"
    scan_interval: 5

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
