################################################################
## Packages / Cleaning
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "cleaning"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.dishwasher:
      <<: *customize
      icon: mdi:dishwasher
      device_class: vibration
      friendly_name: "Dishwasher Vibration"

    binary_sensor.dishwasher_running:
      <<: *customize
      icon: mdi:dishwasher
      device_class: vibration
      friendly_name: "Dishwasher Running"

    binary_sensor.dryer_running:
      <<: *customize
      icon: mdi:tumble-dryer
      device_class: vibration
      friendly_name: "Dryer Running"

    binary_sensor.washer:
      <<: *customize
      icon: mdi:washing-machine
      device_class: vibration
      friendly_name: "Washer Vibration"

    binary_sensor.washer_door:
      <<: *customize
      icon: mdi:washing-machine
      device_class: door
      friendly_name: "Washer Door"

    binary_sensor.washing_machine_running:
      <<: *customize
      icon: mdi:washing-machine
      device_class: vibration
      friendly_name: "Washer Running"

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.dishwasher:
      <<: *customize
      icon: mdi:dishwasher
      friendly_name: "Dishwasher Vibration"

    sensor.washer:
      <<: *customize
      icon: mdi:washer
      friendly_name: "Washer Vibration"

    sensor.washer_state:
      <<: *customize
      icon: mdi:washer
      friendly_name: "Washing Machine"

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel: []

########################
## Automation
########################
automation:
  - id: wash_finished
    alias: wash_finished
    trigger:
      - trigger: state
        # entity_id: binary_sensor.washer_door
        # to: "off"
        entity_id: binary_sensor.front_load_washer_wash_completed
        to: "on"
    action:
      - action: notify.all
        data:
          message: "Washing machine finished! \U0001F9FA"

  - id: washer_reminder
    alias: washer_reminder
    trigger:
      - trigger: state
        # entity_id: binary_sensor.washer_door
        # to: "off"
        entity_id: binary_sensor.front_load_washer_wash_completed
        to: "on"
        for:
          hours: 18
    action:
      - action: notify.all
        data:
          message: "Items still in washing machine.  Get them out before they turn musty! \U0001F9FA"

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Cameras
########################
camera: []

########################
# Device Trackers
########################
device_tracker: []

########################
# Frontend
########################
frontend: []

########################
# Groups
########################
group: []

########################
# Input Booleans
########################
input_boolean: []

########################
# Input Numbers
########################
input_number: []

########################
# Input Select
########################
input_select:
  washer_state:
    name: Washer State
    options:
      - IDLE
      - CLEANING
      - CLEAN
      - MUSTY
    icon: mdi:washing-machine
########################
# iOS
########################
ios: []

########################
# Light
########################
light: []

########################
# Media Player
########################
media_player: []

########################
# Plant
########################
plant: []

########################
# Scenes
########################
scene: []

########################
# Scripts
########################
script: []

########################
# Sensor
########################
sensor: []

########################
# Switch
########################
switch: []

########################
# Template
########################
template:
  - binary_sensor:
      - delay_off: 0:10:00
        delay_on: 0:05:00
        default_entity_id: binary_sensor.dishwasher_running
        state: "{{ is_state('binary_sensor.dishwasher', 'on') }}"
        name: dishwasher_running
      - delay_off: 0:10:00
        delay_on: 0:05:00
        default_entity_id: binary_sensor.dryer_running
        state: "{{ is_state('binary_sensor.dryer', 'on') }}"
        name: dryer_running
      - delay_off: 0:10:00
        delay_on: 0:05:00
        default_entity_id: binary_sensor.washing_machine_running
        state: "{{ is_state('binary_sensor.washer', 'on') }}"
        name: washing_machine_running
  - trigger:
      - trigger: state
        entity_id:
          - vacuum.valetudo_upstairs_vacuum
          - vacuum.valetudo_mainlevel
          - vacuum.valetudo_den
        to: "cleaning"
    sensor:
      - name: "Vacuum last ran"
        state_class: measurement
        device_class: timestamp
        state: >-
          {{now()}}

########################
# Zone
########################
zone: []
