################################################################
## Packages / Climate
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "climate"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.turn_off_nest_when_windows_open:
      <<: *customize
      friendly_name: "Turn Off Nest When Egress Open"
      icon: mdi:window-open

    automation.turn_on_nest_when_windows_closed:
      <<: *customize
      friendly_name: "Turn On Nest When All Egresses Close"
      icon: mdi:window-closed

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.fresh_air_open:
      <<: *customize
      friendly_name: "Window open"
      device_class: opening
      #icon: mdi:window-open

    binary_sensor.ecobee_home:
      <<: *customize
      friendly_name: "Ecobee Home/Away/Sleep Mode"
      device_class: presence

    binary_sensor.pressure_falling:
      <<: *customize
      friendly_name: "Pressure Falling"
      device_class: pressure

    binary_sensor.pressure_falling_quickly:
      <<: *customize
      friendly_name: "Pressure Falling Quickly"
      device_class: pressure

    binary_sensor.pressure_falling_slowly:
      <<: *customize
      friendly_name: "Pressure Falling Slowly"
      device_class: pressure

    binary_sensor.pressure_falling_v_rapidly:
      <<: *customize
      friendly_name: "Pressure Falling Very Rapidly"
      device_class: pressure

    binary_sensor.pressure_rising:
      <<: *customize
      friendly_name: "Pressure Rising"
      device_class: pressure

    binary_sensor.pressure_rising_quickly:
      <<: *customize
      friendly_name: "Pressure Rising Quickly"
      device_class: pressure

    binary_sensor.pressure_rising_slowly:
      <<: *customize
      friendly_name: "Pressure Rising Slowly"
      device_class: pressure

    binary_sensor.pressure_rising_v_rapidly:
      <<: *customize
      friendly_name: "Pressure Rising Very Rapidly"
      device_class: pressure
    ################################################
    ## Groups
    ################################################
    group.vacation_climate:
      <<: *customize
      friendly_name: "Overall Climate"

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.basement_humidity:
      <<: *customize
      device_class: humidity

    sensor.garage_humidity:
      <<: *customize
      device_class: humidity

    sensor.hallway_thermostat_glycol_humidity:
      <<: *customize
      device_class: humidity

    sensor.average_house_temp:
      <<: *customize
      friendly_name: "Average House Temperature"
      device_class: temperature
      icon: mdi:thermometer

    sensor.average_house_humidity:
      <<: *customize
      friendly_name: "Average House Humidity"
      device_class: humidity
      icon: mdi:water-percent

    sensor.average_house_pressure:
      <<: *customize
      friendly_name: "Average House Pressure"
      device_class: pressure
      icon: mdi:gauge

    ################################################
    ## Thermostats
    ################################################
    thermostat.hallwayglycol:
      <<: *customize
      friendly_name: "Nest Thermostat"
      icon: mdi:air-conditioner

################################################
## Automation
################################################
automation:
  - id: buy_more_air_filters
    alias: buy_more_air_filters
    trigger:
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Home Depot"
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Menards"
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Lowes"
    condition:
      - alias: "Salt Bag Inventory Low"
        condition: numeric_state
        entity_id: input_number.air_filters_at_home
        below: 1
    action:
      - service: notify.mobile_app_wethop
        data:
          title: "Buy Air Filters"
          message: >-
            "You only have {{states("input_number.air_filters_at_home")| int}} 16x25 air filters at home. How many did you buy?"
          data:
            actions:
              - action: "BOUGHT_AIR_FILTERS"
                title: "Purchased air filters"
                activationMode: background
                authenticationRequired: false
                destructive: false
                behavior: textInput
                textInputButtonTitle: Number of filters
                textInputPlaceholder: 2
                icon: sfsymbols:bag.badge.questionmark

  - id: air_filters_purchased
    alias: air_filters_purchased
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: BOUGHT_AIR_FILTERS
    condition: []
    action:
      - alias: Increase Number of air filters in inventory
        service: input_number.set_value
        entity_id: input_number.air_filters_at_home
        data:
          value: >-
            {{(states("input_number.air_filters_at_home")|int) + (trigger.event.data.reply_text | int)}}

  - id: turn_on_bathroom_fan_when_humidity_high
    alias: turn_on_bathroom_fan_when_humidity_high
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_humidity_high
        to: "on"
        for:
          seconds: 20
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.bathroom_light_fan_switch

  - id: turn_off_bathroom_fan_when_humidity_normal
    alias: turn_off_bathroom_fan_when_humidity_normal
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_humidity_high
        to: "off"
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.bathroom_light_fan_switch

# Implemented in Schedy
# - id: turn_off_nest_when_windows_open
#   alias: turn_off_nest_when_windows_open
#   trigger:
#   - platform: state
#     entity_id:
#       - binary_sensor.ene_window_contact
#       - binary_sensor.ese_window_contact
#       - binary_sensor.nne_window_contact
#       - binary_sensor.north_kitchen_sink_window_contact
#       - binary_sensor.north_master_bedroom_window_contact
#       - binary_sensor.office_north_window_contact
#       - binary_sensor.se_basement_window_contact
#       - binary_sensor.sse_window_contact
#       - binary_sensor.sw_basement_window_contact
#     from: 'off'
#     to: 'on'
#     for:
#       minutes:  1
#   condition:
#   - condition: state
#     entity_id: binary_sensor.bayesian_zeke_home
#     state: 'on'
#   action:
#   - service: climate.turn_off
#     data:
#       entity_id: climate.my_ecobee

# Implemented in Schedy
# - id: turn_on_nest_when_windows_closed
#   alias: turn_on_nest_when_windows_closed
#   trigger:
#   - platform: state
#     entity_id: group.egress_points
#     from: 'on'
#     to: 'off'
#     for:
#       minutes: 5
#   condition:
#     condition: and
#     conditions:
#     - condition: state
#       entity_id: climate.my_ecobee
#       state: 'off'
#     - condition: state
#       entity_id: binary_sensor.bayesian_zeke_home
#       state: 'on'
#   action:
#   - service: climate.set_hvac_mode
#     data:
#       entity_id: climate.my_ecobee
#       operation_mode: eco

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      bathroom_humidity_high:
        value_template: >-
          {% if
              (states('sensor.bathroom_humidity')|float(default=0)) > (states('sensor.average_house_humidity')|float(default=0) + 10)
          %} True
          {% else %}
            False
          {% endif %}

      ecobee_home:
        value_template: >-
          {% if
              is_state_attr('climate.my_ecobee', 'preset_mode', 'Away')
                or
              is_state_attr('climate.my_ecobee', 'preset_mode', 'Away and Eco')
          %} False
          {% else %}
            True
          {% endif %}

      fresh_air_open:
        value_template: >-
          {{
            is_state('binary_sensor.ene_window_contact', 'on')
            or is_state('binary_sensor.ese_window_contact', 'on')
            or is_state('binary_sensor.nne_window_contact', 'on')
            or is_state('binary_sensor.north_kitchen_sink_window_contact', 'on')
            or is_state('binary_sensor.north_master_bedroom_window_contact', 'on')
            or is_state('binary_sensor.office_north_window_contact', 'on')
            or is_state('binary_sensor.se_basement_window_contact', 'on')
            or is_state('binary_sensor.sse_window_contact', 'on')
            or is_state('binary_sensor.sw_basement_window_contact', 'on')
          }}

  - platform: trend
    sensors:
      pressure_falling_v_rapidly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00055

      pressure_rising_v_rapidly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00055

      pressure_falling_quickly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00033

      pressure_rising_quickly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00033

      pressure_falling:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00015

      pressure_rising:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00015

      pressure_falling_slowly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.000009

      pressure_rising_slowly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.000009

########################
# Climate
########################
climate:
  - platform: generic_thermostat
    name: Tiki Room
    heater: switch.tiki_room_heater
    target_sensor: sensor.tiki_room_tph_temperature
    min_temp: 45
    max_temp: 90
    ac_mode: false
    target_temp: 60
    cold_tolerance: 3
    hot_tolerance: 1
    min_cycle_duration:
      minutes: 30
    away_temp: 50
    precision: 1

  # - platform: nest
########################
# Groups
########################
group:
  average_house_climate:
    name: Average Climate
    entities:
      - sensor.average_house_temp
      - sensor.average_house_humidity
      - sensor.average_house_pressure

  pressure_trends:
    name: Pressure Trends
    entities:
      - binary_sensor.pressure_rising_v_rapidly
      - binary_sensor.pressure_rising_quickly
      - binary_sensor.pressure_rising
      - binary_sensor.pressure_rising_slowly
      - binary_sensor.pressure_falling_slowly
      - binary_sensor.pressure_falling
      - binary_sensor.pressure_falling_quickly
      - binary_sensor.pressure_falling_v_rapidly

  climate:
    name: Climate at a Glance
    entities:
      # Nest Thermostat
      - climate.my_ecobee
      - sensor.my_ecobee_temperature
      - sensor.my_ecobee_humidity
      - sensor.hallway_thermostat_glycol_target
      - sensor.hallway_thermostat_glycol_operation_mode
      - climate.tiki_room
      - sensor.basement_temperature

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:
  air_filters_at_home:
    name: Air Filter Inventory at Home
    icon: mdi:shaker-outline
    min: 0
    max: 20
    mode: box
    step: 1

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative default House Temp Change

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 5-5 minutes House Temp Change
    round: 5
    time_window: "00:5:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 2.5-5 minutes House Temp Change
    round: 5
    time_window: "00:02:30"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 10-10 minutes House Temp Change
    round: 5
    time_window: "00:10:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 5-10 minutes House Temp Change
    round: 5
    time_window: "00:05:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 30 minutes House Temp Change
    round: 5
    time_window: "00:15:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 60 minutes House Temp Change
    round: 5
    time_window: "00:30:00"

  - platform: min_max
    name: average_house_temp
    type: mean
    entity_ids:
      - sensor.basement_temperature
      - sensor.basement_closet_tph_temperature
      - sensor.bedroom_temperature
      - sensor.den_temperature
      - sensor.guest_room_temperature
      - sensor.guest_room_tph_temperature
      - sensor.my_ecobee_current_temperature
      - sensor.office_temperature
      - sensor.office_tph_temperature
      - sensor.owner_suite_bathroom_tph_temperature
      - sensor.owner_suite_tph_temperature
      - sensor.tiki_room_tph_temperature
      - sensor.upstairs_closet_tph_temperature

  - platform: min_max
    name: average_house_humidity
    #unit_of_measurement: "%"
    type: mean
    entity_ids:
      - sensor.basement_closet_tph_humidity
      - sensor.guest_room_tph_humidity
      - sensor.office_tph_humidity
      - sensor.my_ecobee_current_humidity
      - sensor.owner_suite_bathroom_tph_humidity
      - sensor.owner_suite_tph_humidity
      - sensor.tiki_room_tph_humidity
      - sensor.upstairs_closet_tph_humidity

  - platform: min_max
    name: average_house_pressure
    #unit_of_measurement: "mbar"
    type: mean
    entity_ids:
      - sensor.basement_closet_tph_pressure
      - sensor.guest_room_tph_pressure
      - sensor.office_tph_pressure
      - sensor.owner_suite_bathroom_tph_pressure
      - sensor.owner_suite_tph_pressure
      - sensor.tiki_room_tph_pressure
      - sensor.upstairs_closet_tph_pressure

  - platform: template
    sensors:
      ecobee_temperature:
        unit_of_measurement: "°F"
        availability_template: >-
          {{ states("climate.my_ecobee") != None }}
        value_template: >-
          {{ state_attr('climate.my_ecobee', 'current_temperature') }}

      rate_of_house_temp_change_5m:
        unit_of_measurement: "°F/5 minute"
        availability_template: >-
          {{ states("sensor.rate_of_house_temp_change_5m", "change_rate") != None }}
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_5m', 'change_rate')  |float(default=0)}}

      rate_of_house_temp_change_10m:
        unit_of_measurement: "°F/5 minute"
        availability_template: >-
          {{ states("sensor.rate_of_house_temp_change_10m", "change_rate") != None }}
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_10m', 'change_rate')|float(default=0) * 60.0 * 5.0 |float(default=0)}}

      rate_of_house_temp_change_1h:
        availability_template: >-
          {{ states("sensor.house_temperature_stats_1h", "change_rate") != None }}
        unit_of_measurement: "°F/5 minute"
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_1h', 'change_rate') * 60.0 * 5.0 |float(default=0)}}

      rate_of_house_temp_change_30m:
        unit_of_measurement: "°F/5 minute"
        availability_template: >-
          {{ states("sensor.house_temperature_stats_30m", "change_rate") != None }}
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_30m', 'change_rate') * 60.0 * 5.0 |float(default=0)}}

  - platform: statistics
    name: min_rate_of_house_temp_change_10m
    entity_id: sensor.rate_of_house_temp_change_10m
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12

  - platform: statistics
    name: min_rate_of_house_temp_change_1h
    entity_id: sensor.rate_of_house_temp_change_1h
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12

  - platform: statistics
    name: min_rate_of_house_temp_change_30m
    entity_id: sensor.rate_of_house_temp_change_30m
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12

  - platform: statistics
    name: house_temperature_stats_5m
    entity_id: sensor.average_house_temp
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12
    max_age:
      minutes: 5
    precision: 8

  - platform: statistics
    name: house_temperature_stats_10m
    entity_id: sensor.average_house_temp
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12
    max_age:
      minutes: 10
    precision: 10

  - platform: statistics
    name: house_temperature_stats_30m
    entity_id: sensor.average_house_temp
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12
    max_age:
      minutes: 30
    precision: 8

  - platform: statistics
    name: house_temperature_stats_1h
    entity_id: sensor.average_house_temp
    state_characteristic: mean
    sampling_size: 20 # TODO Remove after 2022.12
    max_age:
      hours: 1
    precision: 8
