################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'climate'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.nest_home:
      <<: *customize
      friendly_name: 'Nest Home/Away Mode'
      device_class: presence

    ################################################
    ## Groups
    ################################################
    group.vacation_climate:
      <<: *customize
      friendly_name: "Overall Climate"
      
    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.basement_humidity:
      <<: *customize
      icon: mdi:water-percent
      
    sensor.garage_humidity:
      <<: *customize
      icon: mdi:water-percent
      
    sensor.hallway_thermostat_glycol_humidity:
      <<: *customize
      icon: mdi:water-percent

    sensor.average_house_temp:
      <<: *customize
      friendly_name: "Average House Temperature"
      icon_template: mdi:thermometer

    sensor.average_house_humidity:
      <<: *customize
      friendly_name: "Average House Humidity"
      icon_template: mdi:water-percent

    sensor.average_house_pressure:
      <<: *customize
      friendly_name: "Average House Pressure"
      icon_template: mdi:gauge
      
    ################################################
    ## Thermostats
    ################################################
    thermostat.hallwayglycol:
      <<: *customize
      friendly_name: "Nest Thermostat"
      icon: mdi:air-conditioner
      
################################################
## Automation
################################################
automation:
  - id: turn_off_nest_when_windows_open
    alias: turn_off_nest_when_windows_open
    trigger: 
    - platform: state
      entity_id: 
        - binary_sensor.ene_window_contact
        - binary_sensor.ese_window_contact
        - binary_sensor.nne_window_contact
        - binary_sensor.north_kitchen_sink_window_contact
        - binary_sensor.north_master_bedroom_window_contact
        - binary_sensor.office_north_window_contact
        - binary_sensor.se_basement_window_contact
        - binary_sensor.sse_window_contact
        - binary_sensor.sw_basement_window_contact
      from: 'off'
      to: 'on'
      for:
        minutes:  1
    condition:
    - condition: state
      entity_id: binary_sensor.bayesian_zeke_home
      state: 'on'
    action: 
    - service: climate.turn_off
      data:
        entity_id: climate.hallway_glycol

  - id: turn_on_nest_when_windows_closed
    alias: turn_on_nest_when_windows_closed
    trigger: 
    - platform: state
      entity_id: group.egress_points
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: climate.hallway_glycol
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bayesian_zeke_home
        state: 'on'
    action: 
    - service: climate.turn_on
      data:
        entity_id: climate.hallway_glycol
        
        
        
########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      nest_home:
        value_template: >-
          {% if 
              is_state_attr('climate.hallway_glycol', 'away_mode', 'on') 
          %} False 
          {% else %} 
             True  
          {% endif %}

########################
# Groups
########################
group:
  average_house_climate:
    name: Average Climate
    entities:
      - sensor.average_house_temp
      - sensor.average_house_humidity
      - sensor.average_house_pressure
      
########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  Climate:
    entities:
      - climate.hallway_glycol
      - sensor.hallway_thermostat_glycol_temperature
      - sensor.hallway_thermostat_glycol_humidity
      - sensor.hallway_thermostat_glycol_target
      - sensor.hallway_thermostat_glycol_operation_mode

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  - platform: mqtt
    state_topic: "sensor/basement_humidity"
    name: "Basement Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/basement_temperature"
    name: "Basement Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/humidity"
    name: "Garage Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
    
  - platform: mqtt
    state_topic: "sensor/temperature"
    name: "Garage Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true

  - platform: template
    sensors:
      turn_off_time:
        entity_id:
          - input_number.random_hour
          - input_number.random_minute
        value_template: >-
          {{ states("input_number.random_hour")|int }}:{{states("input_number.random_minute")|int}}
      average_house_temp:
        unit_of_measurement: "°F"
        entity_id:
          - sensor.living_room_temperature
          - sensor.master_bedroom_temperature
          - sensor.guest_room_temperature
          - sensor.bathroom_temperature
          - sensor.motion_sensor_temperature
          - sensor.hallway_thermostat_glycol_temperature
        value_template: >-
          {{ (( states("sensor.living_room_temperature")|float +
          states("sensor.master_bedroom_temperature")|float +
          states("sensor.guest_room_temperature")|float +
          states("sensor.bathroom_temperature")|float +
          states("sensor.motion_sensor_temperature")|float )
          / 5.0) |round(2)}}

      average_house_humidity:
        unit_of_measurement: "%"
        entity_id:
          - sensor.living_room_humidity
          - sensor.master_bedroom_humidity
          - sensor.guest_room_humidity
          - sensor.bathroom_humidity
          - sensor.hallway_thermostat_glycol_humidity
        value_template: >-
          {{ ( states("sensor.living_room_humidity")|float +
          states("sensor.master_bedroom_humidity")|float +
          states("sensor.guest_room_humidity")|float +
          states("sensor.bathroom_humidity")|float +
          states("sensor.hallway_thermostat_glycol_humidity")|float )
          / 5.0 |round}}

      average_house_pressure:
        unit_of_measurement: "inHg"
        entity_id:
          - sensor.living_room_pressure
          - sensor.master_bedroom_pressure
          - sensor.guest_room_pressure
          - sensor.bathroom_pressure
        value_template: >-
          {{ ( states("sensor.living_room_humidity")|float +
          states("sensor.master_bedroom_humidity")|float +
          states("sensor.guest_room_humidity")|float +
          states("sensor.bathroom_humidity")|float )
          / 4.0 |round}}
