################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'climate'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.nest_home:
      <<: *customize
      friendly_name: 'Nest Home/Away Mode'
      device_class: presence

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.basement_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.garage_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.hallway_thermostat_glycol_humidity:
      <<: *customize
      icon: mdi:water-percent

    ################################################
    ## Thermostats
    ################################################
    thermostat.hallwayglycol:
      <<: *customize
      friendly_name: "Nest Thermostat"
      icon: mdi:air-conditioner
      
################################################
## Automation
################################################
automation:
  - id: turn_off_nest_when_windows_open
    alias: turn_off_nest_when_windows_open
    trigger: 
    - platform: state
      entity_id: 
        - binary_sensor.ene_window_contact
        - binary_sensor.ese_window_contact
        - binary_sensor.nne_window_contact
        - binary_sensor.north_kitchen_sink_window_contact
        - binary_sensor.north_master_bedroom_window_contact
        - binary_sensor.office_north_window_contact
        - binary_sensor.se_basement_window_contact
        - binary_sensor.sse_window_contact
        - binary_sensor.sw_basement_window_contact
      from: 'off'
      to: 'on'
      for:
        minutes:  1
    condition:
    - condition: state
      entity_id: binary_sensor.bayesian_zeke_home
      state: 'on'
    action: 
    - service: climate.turn_off
      data:
        entity_id: climate.hallway_glycol

  - id: turn_on_nest_when_windows_closed
    alias: turn_on_nest_when_windows_closed
    trigger: 
    - platform: state
      entity_id: 
        - binary_sensor.ene_window_contact
        - binary_sensor.ese_window_contact
        - binary_sensor.nne_window_contact
        - binary_sensor.north_kitchen_sink_window_contact
        - binary_sensor.north_master_bedroom_window_contact
        - binary_sensor.office_north_window_contact
        - binary_sensor.se_basement_window_contact
        - binary_sensor.sse_window_contact
        - binary_sensor.sw_basement_window_contact
      from: 'on'
      to: 'off'
      for:
        minutes: 30
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.ene_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.ese_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.nne_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.north_kitchen_sink_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.north_master_bedroom_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.office_north_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.se_basement_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sse_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sw_basement_window_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bayesian_zeke_home
        state: 'on'
    action: 
    - service: climate.turn_on
      data:
        entity_id: climate.hallway_glycol
        
        
        
########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      nest_home:
        value_template: >-
          {% if 
              is_state_attr('climate.hallway_glycol', 'away_mode', 'on') 
          %} False 
          {% else %} 
             True  
          {% endif %}

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  Climate:
    entities:
      - climate.hallway_glycol
      - sensor.hallway_thermostat_glycol_temperature
      - sensor.hallway_thermostat_glycol_humidity
      - sensor.hallway_thermostat_glycol_target
      - sensor.hallway_thermostat_glycol_operation_mode

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  - platform: mqtt
    state_topic: "sensor/basement_humidity"
    name: "Basement Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/basement_temperature"
    name: "Basement Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/humidity"
    name: "Garage Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
    
  - platform: mqtt
    state_topic: "sensor/temperature"
    name: "Garage Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true
