################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'climate'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.bathroom_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.basement_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.garage_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.guest_room_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.hallway_thermostat_glycol_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.living_room_humidity:
      <<: *customize
      icon: mdi:water-percent
    sensor.master_bedroom_humidity:
      <<: *customize
      icon: mdi:water-percent

    ################################################
    ## Thermostats
    ################################################
    thermostat.hallwayglycol:
      <<: *customize
      friendly_name: "Nest Thermostat"
      icon: mdi:air-conditioner
      
################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      nest_home:
        friendly_name: 'Nest Home/Away Mode'
        device_class: presence
        value_template: >-
          {% if 
              is_state_attr('climate.hallway_glycol', 'away_mode', 'on') 
          %} False 
          {% else %} 
             True  
          {% endif %}

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  Climate:
    entities:
      - climate.hallway_glycol
      - sensor.hallway_thermostat_glycol_temperature
      - sensor.hallway_thermostat_glycol_humidity
      - sensor.hallway_thermostat_glycol_target
      - sensor.hallway_thermostat_glycol_operation_mode

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  - platform: mqtt
    state_topic: "smartthings/Bathroom/humidity"
    name: "Bathroom Humidity"
    retain: true
    unit_of_measurement: "%"
    force_update: true
  
  - platform: mqtt
    state_topic: "smartthings/Bathroom/temperature"
    name: "Bathroom Temperature"
    unit_of_measurement: "°F"
    retain: true
    force_update: true
  
  - platform: mqtt
    state_topic: "sensor/basement_humidity"
    name: "Basement Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/basement_temperature"
    name: "Basement Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true
  
  - platform: mqtt
    state_topic: "sensor/humidity"
    name: "Garage Humidity"
    unit_of_measurement: "%"
    force_update: true
    retain: true
    
  - platform: mqtt
    state_topic: "sensor/temperature"
    name: "Garage Temperature"
    unit_of_measurement: "°F"
    force_update: true
    retain: true
    
  - platform: mqtt
    state_topic: "smartthings/Guest/humidity"
    name: "Guest Room Humidity"
    retain: true
    unit_of_measurement: "%"
    force_update: true
  
  - platform: mqtt
    state_topic: "smartthings/Guest/temperature"
    name: "Guest Room Temperature"
    retain: true
    unit_of_measurement: "°F"
    force_update: true
    
  - platform: mqtt
    state_topic: "smartthings/Livingroom/humidity"
    name: "Living Room Humidity"
    retain: true
    unit_of_measurement: "%"
    force_update: true
  
  - platform: mqtt
    state_topic: "smartthings/Livingroom/temperature"
    name: "Living Room Temperature"
    retain: true
    unit_of_measurement: "°F"
    force_update: true
    
  - platform: mqtt
    state_topic: "smartthings/Master/humidity"
    name: "Master Bedroom Humidity"
    retain: true
    unit_of_measurement: "%"
    force_update: true
  
  - platform: mqtt
    state_topic: "smartthings/Master/temperature"
    name: "Master Bedroom Temperature"
    unit_of_measurement: "°F"
    retain: true
    force_update: true
