################################################################
## Packages / Climate
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "climate"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.turn_off_nest_when_windows_open:
      <<: *customize
      friendly_name: "Turn Off Nest When Egress Open"
      icon: mdi:window-open

    automation.turn_on_nest_when_windows_closed:
      <<: *customize
      friendly_name: "Turn On Nest When All Egresses Close"
      icon: mdi:window-closed

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.fresh_air_open:
      <<: *customize
      friendly_name: "Window open"
      device_class: opening
      #icon: mdi:window-open

    binary_sensor.nest_home:
      <<: *customize
      friendly_name: "Nest Home/Away Mode"
      device_class: presence

    binary_sensor.pressure_falling:
      <<: *customize
      friendly_name: "Pressure Falling"
      device_class: pressure

    binary_sensor.pressure_falling_quickly:
      <<: *customize
      friendly_name: "Pressure Falling Quickly"
      device_class: pressure

    binary_sensor.pressure_falling_slowly:
      <<: *customize
      friendly_name: "Pressure Falling Slowly"
      device_class: pressure

    binary_sensor.pressure_falling_v_rapidly:
      <<: *customize
      friendly_name: "Pressure Falling Very Rapidly"
      device_class: pressure

    binary_sensor.pressure_rising:
      <<: *customize
      friendly_name: "Pressure Rising"
      device_class: pressure

    binary_sensor.pressure_rising_quickly:
      <<: *customize
      friendly_name: "Pressure Rising Quickly"
      device_class: pressure

    binary_sensor.pressure_rising_slowly:
      <<: *customize
      friendly_name: "Pressure Rising Slowly"
      device_class: pressure

    binary_sensor.pressure_rising_v_rapidly:
      <<: *customize
      friendly_name: "Pressure Rising Very Rapidly"
      device_class: pressure
    ################################################
    ## Groups
    ################################################
    group.vacation_climate:
      <<: *customize
      friendly_name: "Overall Climate"

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.basement_humidity:
      <<: *customize
      device_class: humidity

    sensor.garage_humidity:
      <<: *customize
      device_class: humidity

    sensor.hallway_thermostat_glycol_humidity:
      <<: *customize
      device_class: humidity

    sensor.average_house_temp:
      <<: *customize
      friendly_name: "Average House Temperature"
      device_class: temperature
      icon: mdi:thermometer

    sensor.average_house_humidity:
      <<: *customize
      friendly_name: "Average House Humidity"
      device_class: humidity
      icon: mdi:water-percent

    sensor.average_house_pressure:
      <<: *customize
      friendly_name: "Average House Pressure"
      device_class: pressure
      icon: mdi:gauge

    ################################################
    ## Thermostats
    ################################################
    thermostat.hallwayglycol:
      <<: *customize
      friendly_name: "Nest Thermostat"
      icon: mdi:air-conditioner

################################################
## Automation
################################################
automation:
  - id: turn_on_bathroom_fan_when_humidity_high
    alias: turn_on_bathroom_fan_when_humidity_high
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_humidity_high
        to: "on"
        for:
          seconds: 20
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.bathroom_light_fan_switch

  - id: turn_off_bathroom_fan_when_humidity_normal
    alias: turn_off_bathroom_fan_when_humidity_normal
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_humidity_high
        to: "off"
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.bathroom_light_fan_switch

# Implemented in Schedy
# - id: turn_off_nest_when_windows_open
#   alias: turn_off_nest_when_windows_open
#   trigger:
#   - platform: state
#     entity_id:
#       - binary_sensor.ene_window_contact
#       - binary_sensor.ese_window_contact
#       - binary_sensor.nne_window_contact
#       - binary_sensor.north_kitchen_sink_window_contact
#       - binary_sensor.north_master_bedroom_window_contact
#       - binary_sensor.office_north_window_contact
#       - binary_sensor.se_basement_window_contact
#       - binary_sensor.sse_window_contact
#       - binary_sensor.sw_basement_window_contact
#     from: 'off'
#     to: 'on'
#     for:
#       minutes:  1
#   condition:
#   - condition: state
#     entity_id: binary_sensor.bayesian_zeke_home
#     state: 'on'
#   action:
#   - service: climate.turn_off
#     data:
#       entity_id: climate.hallway_glycol

# Implemented in Schedy
# - id: turn_on_nest_when_windows_closed
#   alias: turn_on_nest_when_windows_closed
#   trigger:
#   - platform: state
#     entity_id: group.egress_points
#     from: 'on'
#     to: 'off'
#     for:
#       minutes: 5
#   condition:
#     condition: and
#     conditions:
#     - condition: state
#       entity_id: climate.hallway_glycol
#       state: 'off'
#     - condition: state
#       entity_id: binary_sensor.bayesian_zeke_home
#       state: 'on'
#   action:
#   - service: climate.set_hvac_mode
#     data:
#       entity_id: climate.hallway_glycol
#       operation_mode: eco

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      bathroom_humidity_high:
        value_template: >-
          {% if
              (states('sensor.bathroom_humidity')|float) > (states('sensor.average_house_humidity')|float + 10)
          %} True
          {% else %}
             False
          {% endif %}

      nest_home:
        value_template: >-
          {% if
              is_state_attr('climate.hallway_glycol', 'preset_mode', 'away')
                or
              is_state_attr('climate.hallway_glycol', 'preset_mode', 'Away and Eco')
          %} False
          {% else %}
             True
          {% endif %}

      fresh_air_open:
        value_template: >-
          {{
            is_state('binary_sensor.ene_window_contact', 'on')
            or is_state('binary_sensor.ese_window_contact', 'on')
            or is_state('binary_sensor.nne_window_contact', 'on')
            or is_state('binary_sensor.north_kitchen_sink_window_contact', 'on')
            or is_state('binary_sensor.north_master_bedroom_window_contact', 'on')
            or is_state('binary_sensor.office_north_window_contact', 'on')
            or is_state('binary_sensor.se_basement_window_contact', 'on')
            or is_state('binary_sensor.sse_window_contact', 'on')
            or is_state('binary_sensor.sw_basement_window_contact', 'on')
          }}

  - platform: trend
    sensors:
      pressure_falling_v_rapidly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00055

      pressure_rising_v_rapidly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00055

      pressure_falling_quickly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00033

      pressure_rising_quickly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00033

      pressure_falling:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.00015

      pressure_rising:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.00015

      pressure_falling_slowly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: -0.000009

      pressure_rising_slowly:
        entity_id: sensor.average_house_pressure
        sample_duration: 10800
        min_gradient: 0.000009

########################
# Climate
########################
climate:
  - platform: generic_thermostat
    name: Basement
    heater: switch.basement_heater
    target_sensor: sensor.basement_temperature
    min_temp: 45
    max_temp: 90
    ac_mode: false
    target_temp: 60
    cold_tolerance: 3
    hot_tolerance: 1
    min_cycle_duration:
      minutes: 15
    away_temp: 45
    precision: 1

  - platform: nest
########################
# Groups
########################
group:
  average_house_climate:
    name: Average Climate
    entities:
      - sensor.average_house_temp
      - sensor.average_house_humidity
      - sensor.average_house_pressure

  pressure_trends:
    name: Pressure Trends
    entities:
      - binary_sensor.pressure_rising_v_rapidly
      - binary_sensor.pressure_rising_quickly
      - binary_sensor.pressure_rising
      - binary_sensor.pressure_rising_slowly
      - binary_sensor.pressure_falling_slowly
      - binary_sensor.pressure_falling
      - binary_sensor.pressure_falling_quickly
      - binary_sensor.pressure_falling_v_rapidly

  climate:
    name: Climate at a Glance
    entities:
      - climate.glycol_thermostat
      - sensor.glycol_thermostat_temperature
      - sensor.hallway_thermostat_glycol_humidity
      - sensor.hallway_thermostat_glycol_target
      - sensor.hallway_thermostat_glycol_operation_mode
      - climate.basement
      - sensor.basement_temperature

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative default House Temp Change

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 5-5 minutes House Temp Change
    round: 5
    time_window: "00:5:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 2.5-5 minutes House Temp Change
    round: 5
    time_window: "00:02:30"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 10-10 minutes House Temp Change
    round: 5
    time_window: "00:10:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 5-10 minutes House Temp Change
    round: 5
    time_window: "00:05:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 30 minutes House Temp Change
    round: 5
    time_window: "00:15:00"

  - platform: derivative
    source: sensor.average_house_temp
    # source: sensor.glycol_thermostat_temperature
    name: Derivative 60 minutes House Temp Change
    round: 5
    time_window: "00:30:00"

  - platform: season
    type: meteorological

  - platform: min_max
    name: average_house_temp
    type: mean
    entity_ids:
      - sensor.living_room_temperature
      - sensor.master_bedroom_temperature
      - sensor.guest_room_temperature
      - sensor.bathroom_temperature
      - sensor.kitchen_temperature
      #- sensor.motion_sensor_temperature
      #- sensor.hallway_thermostat_glycol_temperature

  - platform: min_max
    name: average_house_humidity
    #unit_of_measurement: "%"
    type: mean
    entity_ids:
      - sensor.living_room_humidity
      - sensor.master_bedroom_humidity
      - sensor.guest_room_humidity
      - sensor.bathroom_humidity
      - sensor.hallway_thermostat_glycol_humidity

  - platform: min_max
    name: average_house_pressure
    #unit_of_measurement: "mbar"
    type: mean
    entity_ids:
      - sensor.living_room_pressure
      - sensor.master_bedroom_pressure
      - sensor.guest_room_pressure
      - sensor.bathroom_pressure
      - sensor.kitchen_pressure

  - platform: template
    sensors:
      # I don't think this is actually used for anything except to display the vacation off time in the UI...
      # turn_off_time:
      #   entity_id:
      #     - input_number.random_hour
      #     - input_number.random_minute
      #   value_template: >-
      #     {{ states("input_number.random_hour")|int }}:{{states("input_number.random_minute")|int}}

      rate_of_house_temp_change_5m:
        entity_id:
          - sensor.house_temperature_stats_5m
        unit_of_measurement: "째F/5 minute"
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_5m', 'change_rate')  |float}}

      rate_of_house_temp_change_10m:
        entity_id:
          - sensor.house_temperature_stats_10m
        unit_of_measurement: "째F/5 minute"
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_10m', 'change_rate')|float * 60.0 * 5.0 |float}}

      rate_of_house_temp_change_1h:
        entity_id:
          - sensor.house_temperature_stats_1h
        unit_of_measurement: "째F/5 minute"
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_1h', 'change_rate') * 60.0 * 5.0 |float}}

      rate_of_house_temp_change_30m:
        entity_id:
          - sensor.house_temperature_stats_30m
        unit_of_measurement: "째F/5 minute"
        value_template: >-
          {{ state_attr('sensor.house_temperature_stats_30m', 'change_rate') * 60.0 * 5.0 |float}}

  - platform: statistics
    name: min_rate_of_house_temp_change_10m
    entity_id: sensor.rate_of_house_temp_change_10m

  - platform: statistics
    name: min_rate_of_house_temp_change_1h
    entity_id: sensor.rate_of_house_temp_change_1h

  - platform: statistics
    name: min_rate_of_house_temp_change_30m
    entity_id: sensor.rate_of_house_temp_change_30m

  - platform: statistics
    name: house_temperature_stats_5m
    entity_id: sensor.average_house_temp
    max_age:
      minutes: 5
    precision: 8

  - platform: statistics
    name: house_temperature_stats_10m
    entity_id: sensor.average_house_temp
    max_age:
      minutes: 10
    precision: 10

  - platform: statistics
    name: house_temperature_stats_30m
    entity_id: sensor.average_house_temp
    max_age:
      minutes: 30
    precision: 8

  - platform: statistics
    name: house_temperature_stats_1h
    entity_id: sensor.average_house_temp
    max_age:
      minutes: 60
    precision: 8
