################################################################
## Packages / Curling
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "curling"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    # automation.leave_home_for_curling:
    #   <<: *customize
    #   friendly_name: "Leave home for curling"
    #   icon: mdi:curling

    automation.return_home_from_OCC:
      <<: *customize
      friendly_name: "Return home from OCC"
      icon: mdi:curling

    automation.return_home_from_spcc:
      <<: *customize
      friendly_name: "Return home from SPCC"
      icon: mdi:curling

    automation.display_curling_tab:
      <<: *customize
      friendly_name: "Display Curling tab"
      icon: mdi:curling

    automation.toggle_curling_automations_on_season_change:
      <<: *customize
      friendly_name: "Toggle Curling season automations"
      icon: mdi:curling

    automation.toggle_curling_tab:
      <<: *customize
      friendly_name: "Toggle Curling tab"
      icon: mdi:curling

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.curling_season:
      <<: *customize
      friendly_name: "Curling Season"
      icon: mdi:calendar

    ################################################
    ## Group
    ################################################

    group.curling_sensors:
      <<: *customize
      friendly_name: "Curling Sensors"

    group.curling_automations:
      <<: *customize
      friendly_name: "Curling Automations"

    ################################################
    ## Scripts
    ################################################
    script.toggle_curling_automation_on_curling_season:
      <<: *customize
      friendly_name: "Toggle Curling Automation Based on Boolean Sensor"

    ################################################
    ## Sensors
    ################################################

    sensor.occ_time:
      <<: *customize
      friendly_name: "Last change in OCC Dir"
      icon: mdi:clock

    sensor.spcc_time:
      <<: *customize
      friendly_name: "Last Change in SPCC Dir"
      icon: mdi:clock

    sensor.spcc_distance:
      <<: *customize
      friendly_name: "Distance to SPCC"
      icon: mdi:curling

    sensor.heading_spcc:
      <<: *customize
      friendly_name: "Direction of SPCC"
      icon: mdi:curling

    sensor.heading_occ:
      <<: *customize
      friendly_name: "Direction of OCC"
      icon: mdi:curling

########################
# Automations
########################
automation:
  - id: leave_home_for_curling
    alias: leave_home_for_curling
    trigger:
      - platform: zone
        entity_id: device_tracker.bayesian_zeke_home
        zone: zone.home
        event: leave
    condition:
      condition: and
      conditions:
        - condition: time
          after: "16:00:00"
          before: "20:10:00"
          weekday:
            - mon
            - tue
            - wed
        - condition: state
          entity_id: input_boolean.guest_mode
          state: "off"
        - condition: state
          entity_id:
            - binary_sensor.curling_season
          state: "on"
    action:
      - alias: Start Vacuums
        service: vacuum.start
        target:
          entity_id: all
      - service: climate.set_preset_mode
        entity_id: climate.my_ecobee
        data:
          preset_mode: "Away"
      - data:
          message: Good Curling!
        service: notify.all

  - id: return_home_from_occ
    alias: return_home_from_occ
    trigger:
      - platform: zone
        entity_id: device_tracker.bayesian_zeke_home
        zone: zone.occ
        event: leave
    condition:
      condition: state
      entity_id:
        - binary_sensor.curling_season
      state: "on"
    action:
      - service: climate.set_preset_mode
        entity_id: climate.my_ecobee
        data:
          preset_mode: "Home"
      - service: notify.all
        data_template:
          message: >-
            Turning off Ecobee Away mode while driving home from OCC

  - id: return_home_from_spcc
    alias: return_home_from_spcc
    trigger:
      - platform: zone
        entity_id: device_tracker.bayesian_zeke_home
        zone: zone.spcc
        event: leave
    condition:
      condition: state
      entity_id:
        - binary_sensor.curling_season
      state: "on"
    action:
      - service: climate.set_preset_mode
        entity_id: climate.my_ecobee
        data:
          preset_mode: "Home"
      - service: notify.all
        data_template:
          message: >-
            Turning off Ecobee away mode while driving home from SPCC

  - id: toggle_curling_automations_on_season_change
    alias: toggle_curling_automations_on_season_change
    trigger:
      - platform: state
        entity_id: binary_sensor.curling_season
      - platform: homeassistant
        event: start
    action:
      - service: script.toggle_curling_automation_on_curling_season
        data:
          entity_id: automation.return_home_from_OCC
      # - service: script.toggle_curling_automation_on_curling_season
      #   data:
      #     entity_id: automation.leave_home_for_curling
      - service: script.toggle_curling_automation_on_curling_season
        data:
          entity_id: automation.return_home_from_spcc

  # - id: toggle_curling_tab
  #   alias: toggle_curling_tab
  #   trigger:
  #   - platform: state
  #     entity_id: binary_sensor.curling_season
  #   - platform: homeassistant
  #     event: start
  #   condition: []
  #   action:
  #   - delay: '00:00:{{ (range(1,60)|random|int) }}'
  #   - service: script.toggle_view
  #     data_template:
  #       view_id: curling
  #       visible: >-
  #         {{ is_state("binary_sensor.curling_season", 'on') | lower }}

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      curling_season:
        value_template: >-
          {{ now().strftime("%m") |int in [1,2,3,4,10,11,12] }}

########################
# Groups
########################
group:
  curling_sensors:
    entities:
      - binary_sensor.curling_season
      - sensor.occ_time
      - sensor.heading_occ
      - sensor.spcc_time
      - sensor.spcc_distance
      - sensor.heading_spcc
  curling_automations:
    entities:
      - automation.leave_home_for_curling
      - automation.return_home_from_occ
      - automation.return_home_from_spcc

########################
# Scripts
########################
script:
  toggle_curling_automation_on_curling_season:
    sequence:
      - service: >-
          {% if is_state("binary_sensor.curling_season", 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: "{{ entity_id }}"

########################
# Sensors
########################
sensor:
  - platform: template
    sensors:
      occ_distance:
        value_template: >-
          {{ states('proximity.occ') }}
        unit_of_measurement: "m"
      occ_time:
        value_template: >-
          {% if states.sensor.heading_occ.last_changed is defined %}
            {{ (as_timestamp(now(), default=now()) - as_timestamp(states.sensor.heading_occ.last_changed, default=now())) | int //60 }}
          {% else %}
            {{now()}}
          {% endif %}
        unit_of_measurement: "minutes"
      spcc_time:
        value_template: >-
          {% if states.sensor.heading_spcc.last_changed is defined %}
             {{ (as_timestamp(now(), default=now()) - as_timestamp(states.sensor.heading_spcc.last_changed, default=now())) | int //60 }}
          {% else %}
            {{now()}}
          {% endif %}
        unit_of_measurement: "minutes"
      spcc_distance:
        value_template: >-
          {{ states('proximity.spcc') }}
        unit_of_measurement: "m"
      heading_spcc:
        value_template: >-
          {{ state_attr('proximity.spcc','dir_of_travel') |default("unknown") }}
      heading_occ:
        value_template: >-
          {{ state_attr('proximity.occ','dir_of_travel') |default("unknown") }}
