################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "TO_CHANGE"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################
    ################################################
    ## Automations
    ################################################
    ################################################
    ## Binary Sensors
    ################################################
    ################################################
    ## Cameras
    ################################################
    ################################################
    ## Device Trackers
    ################################################
    ################################################
    ## Frontend
    ################################################
    ################################################
    ## Groups
    ################################################
    ################################################
    ## Input Boolean
    ################################################
    ################################################
    ## Input Numbers
    ################################################
    ################################################
    ## Input Select
    ################################################
    ################################################
    ## iOS
    ################################################
    ################################################
    ## Light
    ################################################
    ################################################
    ## Media Player
    ################################################
    ################################################
    ## Plant
    ################################################
    ################################################
    ## Proximity
    ################################################
    ################################################
    ## Scripts
    ################################################
    ################################################
    ## Sensors
    ################################################
    ################################################
    ## Thermostats
    ################################################
    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - alias: turn_on_fan_if_living_room_occupied
    id: turn_on_fan_if_living_room_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: "on"
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          #speed: smart

  - alias: turn_off_fan_if_living_room_occupied
    id: turn_off_fan_if_living_room_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: "off"
        for: "00:30:00"
    action:
      - service: fan.turn_off
        data:
          entity_id: fan.living_room_fan

  - alias: turn_on_fan_if_bedroom_occupied
    id: turn_on_fan_if_bedroom_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_occupancy
        to: "on"
      - platform: state
        entity_id: binary_sensor.master_bed_occupancy
        to: "on"
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_fan
          speed: high
          #speed: smart

  - alias: turn_off_fan_if_bedroom_occupied
    id: turn_off_fan_if_bedroom_occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_occupancy
        to: "off"
        for: "00:10:00"
    condition:
      - condition: state
        entity_id: binary_sensor.master_bed_occupancy
        state: "off"
    action:
      - service: fan.turn_off
        data:
          entity_id: fan.master_bedroom_fan

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
