################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "fans"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################
    ################################################
    ## Automations
    ################################################
    ################################################
    ## Binary Sensors
    ################################################
    ################################################
    ## Cameras
    ################################################
    ################################################
    ## Device Trackers
    ################################################
    ################################################
    ## Frontend
    ################################################
    ################################################
    ## Groups
    ################################################
    ################################################
    ## Input Boolean
    ################################################
    ################################################
    ## Input Numbers
    ################################################
    ################################################
    ## Input Select
    ################################################
    ################################################
    ## iOS
    ################################################
    ################################################
    ## Light
    ################################################
    ################################################
    ## Media Player
    ################################################
    ################################################
    ## Plant
    ################################################
    ################################################
    ## Proximity
    ################################################
    ################################################
    ## Scripts
    ################################################
    ################################################
    ## Sensors
    ################################################
    ################################################
    ## Thermostats
    ################################################
    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - alias: den_fan_control
    id: den_fan_control
    trigger:
      - trigger: state
        entity_id: binary_sensor.den_occupancy
        to: "on"
        id: den-occupied
      - trigger: state
        entity_id: binary_sensor.den_occupancy
        to: "off"
        for:
          minutes: 30
        id: den-unoccupied
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: den-occupied
            sequence:
              - action: fan.turn_on
                data:
                  entity_id: fan.den_ceiling
                  #speed: smart
          - conditions:
              - condition: trigger
                id: den-unoccupied
            sequence:
              - action: fan.turn_off
                data:
                  entity_id: fan.den_ceiling

  # - alias: turn_off_fan_if_den_unoccupied
  #   id: turn_off_fan_if_den_unoccupied
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.den_occupancy
  #       to: "off"
  #       for: "00:30:00"
  #   action:
  #     - action: fan.turn_off
  #       data:
  #         entity_id: fan.den_ceiling

  - alias: bedroom_fan_control
    id: bedroom_fan_control
    trigger:
      - trigger: state
        entity_id: binary_sensor.bedroom_occupancy
        to: "on"
        id: bedroom-occupied
      - trigger: state
        entity_id: binary_sensor.bedroom_occupancy
        to: "off"
        for:
          minutes: 10
        id: bedroom-unoccupied
    condition:
      - condition: state
        entity_id:
          - binary_sensor.bayesian_bed_occupancy
        # entity_id: input_boolean.chatgpt_bed_occupied
        state: "off"
        # enabled: false
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: bedroom-occupied
            sequence:
              - action: fan.turn_on
                data:
                  entity_id: fan.owner_suite
                  percentage: 67
                  #speed: "medium"  # TODO have this change depending on the season: low in winter, medium spring/fall, high in summer
                  #speed: smart
          - conditions:
              - condition: trigger
                id: bedroom-unoccupied
            sequence:
              - action: fan.turn_off
                data:
                  entity_id: fan.owner_suite
                  #speed: "medium"  # TODO have this change depending on the season: low in winter, medium spring/fall, high in summer
                  #speed: smart

  # - alias: turn_off_fan_if_bedroom_unoccupied
  #   id: turn_off_fan_if_bedroom_unoccupied
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.bedroom_occupancy
  #       to: "off"
  #       for: "00:10:00"
  #   condition:
  #     - condition: state
  #       entity_id: binary_sensor.bayesian_bed_occupancy
  #       state: "off"
  #       # enabled: false
  #   action:
  #     - action: fan.turn_off
  #       data:
  #         entity_id: fan.owner_suite

  - alias: toggle_office_fan
    id: toggle_office_fan
    trigger:
      - trigger: state
        entity_id: binary_sensor.office_occupancy
        to: "on"
        id: office-occupied
        enabled: false
      - trigger: state
        entity_id: binary_sensor.office_motion_occupancy
        to: "on"
        id: office-occupied
        enabled: false
      - trigger: state
        entity_id: binary_sensor.office_occupancy
        to: "off"
        for:
          minutes: 30
        id: office-unoccupied
        enabled: false
      - trigger: state
        entity_id: binary_sensor.office_motion_occupancy
        to: "off"
        for:
          minutes: 30
        id: office-unoccupied
        enabled: false
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: office-occupied
            sequence:
              - action: fan.turn_on
                data:
                  entity_id: fan.office_ceiling_fan
      - choose:
          - conditions:
              - condition: trigger
                id: office-unoccupied
            sequence:
              - action: fan.turn_off
                data:
                  entity_id: fan.office_ceiling_fan

  # - alias: turn_off_fan_if_office_unoccupied
  #   id: turn_off_fan_if_office_unoccupied
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.office_occupancy
  #       to: "off"
  #       for: "00:30:00"
  #     - platform: state
  #       entity_id: binary_sensor.office_motion_occupancy
  #       to: "off"
  #       for: "00:30:00"
  #   action:
  #     - action: fan.turn_off
  #       data:
  #         entity_id: fan.office_ceiling_fan

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Plant
########################
plant:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
