################################################################
## Packages / Guest
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "guest"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account-alert
      #persistent: true

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: turn_off_guest_mode_when_guest_wifi_active
    alias: turn_off_guest_mode_when_guest_wifi_active
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_on_wifi
        to: "off"
        for: "16:00:00"
    # condition:
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
      - service: notify.all
        data:
          message: Guest Mode Deactivated
      - service: media_player.join
        target:
          entity_id:
            - media_player.bedroom
        data:
          group_members:
            - media_player.bathroom
            - media_player.office
            - media_player.den_1

  - id: turn_on_guest_mode_when_guest_wifi_active
    alias: turn_on_guest_mode_when_guest_wifi_active
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_on_wifi
        to: "on"
        for: "00:45:00"
    #condition:
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
      - service: notify.all
        data:
          message: Guest Mode Activated
      - service: media_player.unjoin
        target:
          entity_id:
            - media_player.bedroom
            - media_player.bathroom
            - media_player.office
            - media_player.den_1
      - service: media_player.join
        target:
          entity_id:
            - media_player.bedroom
        data:
          group_members:
            - media_player.bathroom
      - service: media_player.join
        target:
          entity_id:
            - media_player.office
        data:
          group_members:
            - media_player.den_1

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      guest_on_wifi:
        value_template: >-
          {{ (states.device_tracker | selectattr('state','eq','home') | selectattr("attributes.is_guest", 'defined') | selectattr("attributes.is_guest", 'eq', True) | list| count) > 0 }}

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  guest_mode:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: template
    sensors:
      guests_on_wifi:
        value_template: >-
          {{ (states.device_tracker | selectattr('state','eq','home') | selectattr('attributes.is_guest', 'eq', true) | list) }}
########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
