################################################################
## Packages / Guest
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "guest"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account-alert
      #persistent: true

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: turn_off_guest_mode_when_guest_wifi_inactive
    alias: turn_off_guest_mode_when_guest_wifi_inactive
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_on_wifi
        to: "off"
        for:
          hours: 16
    # condition:
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
      - service: notify.all
        data:
          message: Guest Mode Deactivated
      - service: media_player.join
        target:
          entity_id:
            - media_player.bedroom_sonos
        data:
          group_members:
            - media_player.bathroom_sonos
            - media_player.office_sonos
            - media_player.den_sonos

  - id: turn_on_guest_mode_when_guest_wifi_active
    alias: turn_on_guest_mode_when_guest_wifi_active
    trigger:
      - platform: state
        entity_id: binary_sensor.guest_on_wifi
        to: "on"
        for:
          minutes: 10
    #condition:
    action:
      - service: notify.mobile_app_wethop
        data:
          title: "Guest Mode Activated"
          message: "Leave enabled?"
          data:
            actions:
              - action: "ENABLE_GUEST"
                title: "Yes"
                activationMode: background
                authenticationRequired: false
                destructive: false
                behavior: default
              - action: "DISABLE_GUEST"
                title: "No"
                activationMode: background
                authenticationRequired: false
                destructive: false
                behavior: default
      - wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            id: enable_guest
            event_data:
              action: ENABLE_GUEST
        timeout:
          hours: 1
        continue_on_timeout: false
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
      - service: media_player.unjoin
        target:
          entity_id:
            - media_player.bedroom_sonos
            - media_player.bathroom_sonos
            - media_player.office_sonos
            - media_player.den_sonos
      - service: media_player.join
        target:
          entity_id:
            - media_player.bedroom_sonos
        data:
          group_members:
            - media_player.bathroom_sonos
      # - service: media_player.join
      #   target:
      #     entity_id:
      #       - media_player.office
      #   data:
      #     group_members:
      #       - media_player.den

  - id: climate_guest_mode_day
    alias: climate_guest_mode_day
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: "on"
        for:
          seconds: 20
      - platform: time
        at: 07:00:00
    condition:
      - condition: time
        after: "06:00:00"
        before: "00:00:00"
      - condition: state
        entity_id:
          - input_boolean.guest_mode
        state: "on"
    action:
      - service: climate.set_preset_mode
        data:
          preset_mode: "Guest Day"
        target:
          entity_id: climate.my_ecobee

  - id: climate_guest_mode_night
    alias: climate_guest_mode_night
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        to: "on"
        for:
          seconds: 20
      - platform: time
        at: 00:00:00
    condition:
      - condition: time
        after: "00:00:00"
        before: "07:00:00"
      - condition: state
        entity_id:
          - input_boolean.guest_mode
        state: "on"
    action:
      - service: climate.set_preset_mode
        data:
          preset_mode: "Guest Sleep"
        target:
          entity_id: climate.my_ecobee

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      guest_on_wifi:
        value_template: >-
          {% set state = states('sensor.barley_guest') %}
          {% if is_number(state) and state | float >= 1 %}
            true
          {% else %}
            false
          {% endif %}

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  guest_mode:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Plant
########################
plant:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: template
    sensors:
      guests_on_wifi:
        value_template: >-
          {{ (states.device_tracker | selectattr('state','eq','home') | selectattr('attributes.is_guest', 'eq', true) | list) }}
########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
