################################################################
## Packages / Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.deck_light_auto_off:
      <<: *customize
      friendly_name: "Turn off deck lights automatically"
      icon: mdi:nature-people

    automation.deck_light_auto_on:
      <<: *customize
      friendly_name: "Turn on deck lights automatically"
      icon: mdi:nature-people

    automation.front_door_light_auto_off:
      <<: *customize
      friendly_name: "Turn off front door light automatically"
      icon: mdi:home

    automation.front_door_light_auto_on:
      <<: *customize
      friendly_name: "Turn on front door light automatically"
      icon: mdi:home

    automation.hallway_light_on_at_night:
      <<: *customize
      friendly_name: "Turn on hallway light automatically at night"
      icon: mdi:ceiling-light

    automation.hallway_light_off_at_night:
      <<: *customize
      friendly_name: "Turn off hallway light automatically"
      icon: mdi:ceiling-light

    automation.master_bedroom_light_auto_on:
      <<: *customize
      friendly_name: "Turn on master bedroom lights automatically"
      icon: mdi:ceiling-light
      
    automation.master_bedroom_light_auto_off:
      <<: *customize
      friendly_name: "Turn off master bedroom lights automatically"
      icon: mdi:ceiling-light
      
    automation.toggle_living_room:
      <<: *customize
      friendly_name: "Toggle Living Room"
      
    automation.reset_living_room:
      <<: *customize
      friendly_name: "Reset Living Room"

    automation.turn_off_all_lights_when_bed_off:
      <<: *customize
      friendly_name: "Turn off all lights when bedroom lights turn off"
      icon: mdi:hotel
    
    automation.turn_on_bedroom_light_at_night:
      <<: *customize
      friendly_name: "Turn on bedroom lights at night"
      icon: mdi:hotel

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.deck_auto_on:
      <<: *customize
      friendly_name: "Deck Light Automatically Turned on"
      icon: mdi:nature-people
      hidden: true

    input_boolean.front_door_auto_on:
      <<: *customize
      friendly_name: "Front Door Light Automatically Turned on"
      icon: mdi:home
      hidden: true
      
    input_boolean.master_bedroom_auto_on:
      <<: *customize
      friendly_name: "Master Bedroom Light Automatically Turned on"
      icon: mdi:hotel
      hidden: true

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################
    light.bedroom_lamp:
      <<: *customize
      friendly_name: "Bedroom Lamp"
      icon: mdi:hotel

    light.bedroom_lamp_2:
      <<: *customize
      friendly_name: "Bedroom Lamp"
      icon: mdi:hotel

    light.christmas_lights:
      <<: *customize
      friendly_name: "Christmas Lights"
      icon: mdi:led-on

    light.front_door:
      <<: *customize
      friendly_name: "Front Door"
      icon: mdi:home
    
    light.hallway_light:
      <<: *customize
      friendly_name: "Hallway"
      icon: mdi:ceiling-light

    light.kitchen_table:
      <<: *customize
      friendly_name: "Kitchen Table"
      icon: mdi:ceiling-light

    light.left_lamp:
      <<: *customize
      friendly_name: "Living Room Left"
      icon: mdi:lamp

    light.living_room_all:
      <<: *customize
      friendly_name: "Living Room Lights"
      icon: mdi:television
      
    light.living_room_all_except_tv:
      <<: *customize
      friendly_name: "Living Room Lights except TV Bias"
      icon: mdi:television

    light.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"
      icon: mdi:hotel

    light.office:
      <<: *customize
      friendly_name: "Office"
      icon: mdi:desktop-tower

    light.office_lamp:
      <<: *customize
      friendly_name: "Office Lamp"
      icon: mdi:desktop-tower

    light.pendant_lamp:
      <<: *customize
      friendly_name: "Pendant Lamp"
      icon: mdi:ceiling-light

    light.right_lamp:
      <<: *customize
      friendly_name: "Living Room Right"
      icon: mdi:lamp

    light.tv:
      <<: *customize
      friendly_name: "TV Bias"
      icon: mdi:television

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.fade_in:
      <<: *customize
      friendly_name: "Fade In Light"
      icon: mdi:lamp

    ################################################
    ## Sensors
    ################################################
    
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:
  - id: deck_light_auto_off
    alias: deck_light_auto_off
    trigger:
      - platform: state
        entity_id: binary_sensor.deck_door_contact
        to: "off"
        for:
          seconds: 30
    condition:
      condition: state
      entity_id: input_boolean.deck_auto_on
      state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: 
            - switch.deck
            - switch.deck_led_lights
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.deck_auto_on

  - id: deck_light_auto_on
    alias: deck_light_auto_on
    trigger:
      - platform: state
        entity_id: binary_sensor.deck_door_contact
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: state
          entity_id: switch.deck
          state: "off"
        - condition: state
          entity_id: switch.deck_led_lights
          state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: 
            - switch.deck
            - switch.deck_led_lights
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.deck_auto_on

  - id: front_door_light_auto_off
    alias: front_door_light_auto_off
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_contact
        to: "off"
        for:
          seconds: 30
    condition:
      condition: state
      entity_id: input_boolean.front_door_auto_on
      state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: switch.front_door
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.front_door_auto_on

  - id: front_door_light_auto_on
    alias: front_door_light_auto_on
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_contact
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: state
          entity_id: switch.front_door
          state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.front_door
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.front_door_auto_on

  - id: hallway_light_on_at_night
    alias: hallway_light_on_at_night
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "on"
    condition:
      condition: sun
      before: sunrise
      after_offset: "-0:30:00"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.hallway_light
          brightness: 1

  - id: hallway_light_off_at_night
    alias: hallway_light_off_at_night
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "off"
    condition:
      condition: sun
      before: sunrise
      after_offset: "-0:30:00"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: light.hallway_light

  - id: master_bedroom_light_auto_off
    alias: master_bedroom_light_auto_off
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: sun
          before: sunrise
          before_offset: "0:30:00"
        - condition: state
          entity_id: input_boolean.master_bedroom_auto_on
          state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: light.master_bedroom
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.master_bedroom_auto_on

  - id: master_bedroom_light_auto_on
    alias: master_bedroom_light_auto_on
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          before: sunrise
          before_offset: "0:30:00"
        - condition: state
          entity_id: light.master_bedroom
          state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.master_bedroom
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.master_bedroom_auto_on
          brightness: 1

  - alias: toggle_living_room
    id: toggle_living_room
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.living_room_button_push
    action:
    - service: light.toggle
      entity_id: light.living_room_all

  - alias: toggle_kitchen
    id: toggle_kitchen
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.kitchen_button
    action:
    - service: light.toggle
      entity_id: light.kitchen_table
      
  - alias: toggle_office
    id: toggle_office
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.office_button
    action:
    - service: light.toggle
      entity_id: light.office_lamp

  - alias: reset_living_room
    id: reset_living_room
    trigger:
    - platform: state
      entity_id: 
        - binary_sensor.living_room_button_hold
    action:
    - service: scene.turn_on
      entity_id: scene.reset_living_room
    - service: switch.turn_off
      entity_id: switch.flux

  - id: turn_off_all_lights_when_bed_off
    alias: turn_off_all_lights_when_bed_off
    trigger:
    - platform: state
      entity_id: light.master_bedroom
      to: 'off'
    condition:
      condition: time
      after: '22:00:00'
      before: '06:00:00'
    action:
    - service: scene.turn_on
      entity_id: scene.leave_home

  - id: turn_on_bedroom_light_at_night
    alias: turn_on_bedroom_light_at_night
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: 'on'
    condition:
      condition: time
      after: '22:00:00'
      before: '01:00:00'
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.master_bedroom
          brightness: 1

########################
# Binary Sensors
########################
binary_sensor:

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  deck_auto_on:
  front_door_auto_on:
  master_bedroom_auto_on:
########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:
  - platform: group
    name: living_room_all
    entities:
      - light.right_lamp
      - light.left_lamp
      - light.tv
      - light.pendant_lamp

  - platform: group
    name: living_room_all_except_tv
    entities:
      - light.right_lamp
      - light.left_lamp
      - light.pendant_lamp

  - platform: group
    name: master_bedroom
    entities:
      - light.bedroom_lamp
      - light.bedroom_lamp_2
      
########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switch
########################
switch:
  - platform: flux
    lights:
    - light.living_room_all_except_tv
  
########################
# Zone
########################
zone: