################################################################
## Packages / Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################
    light.all_living_room:
      <<: *customize
      friendly_name: All Living Room
      icon: mdi:television

    light.bedroom_lamp:
      <<: *customize
      friendly_name: Bedroom Lamp
      icon: mdi:hotel

    light.bedroom_lamp_2:
      <<: *customize
      friendly_name: Bedroom Lamp

    light.christmas_lights:
      <<: *customize
      friendly_name: Christmas Lights
      icon: mdi:led-on

    light.front_door:
      <<: *customize
      friendly_name: Front Door
      icon: mdi:home

    light.kitchen_table:
      <<: *customize
      friendly_name: Kitchen Table
      icon: mdi:ceiling-light

    light.left_lamp:
      <<: *customize
      friendly_name: Living Room Left
      icon: mdi:lamp

    light.master_bedroom:
      <<: *customize
      friendly_name: Master Bedroom
      icon: mdi:hotel

    light.office:
      <<: *customize
      friendly_name: Office
      icon: mdi:desktop-tower

    light.office_lamp:
      <<: *customize
      friendly_name: Office Lamp
      icon: mdi:desktop-tower

    light.pendant_lamp:
      <<: *customize
      friendly_name: Pendant Lamp
      icon: mdi:ceiling-light

    light.right_lamp:
      <<: *customize
      friendly_name: Living Room Right
      icon: mdi:lamp

    light.tv:
      <<: *customize
      friendly_name: TV Backlight
      icon: mdi:television

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:
  - platform: group
    name: all_living_room
    entities:
      - light.right_lamp
      - light.left_lamp
      - light.tv
      - light.pendant_lamp
  
  - platform: group
    name: master_bedroom
    entities:
      - light.bedroom_lamp
      - light.bedroom_lamp_2
      
########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Zone
########################
zone: