################################################################
## Packages / Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.deck_light_auto_off:
      <<: *customize
      friendly_name: "Turn off deck light automatically"
      icon: mdi:nature-people

    automation.deck_light_auto_on:
      <<: *customize
      friendly_name: "Turn on deck light automatically"
      icon: mdi:nature-people

    automation.front_door_light_auto_off:
      <<: *customize
      friendly_name: "Turn off front door light automatically"
      icon: mdi:home

    automation.front_door_light_auto_on:
      <<: *customize
      friendly_name: "Turn on front door light automatically"
      icon: mdi:home

    automatically.hallway_light_on_at_night:
      <<: *customize
      friendly_name: "Turn on hallway light automatically"
      icon: mdi:ceiling

    automatically.hallway_light_off_at_night:
      <<: *customize
      friendly_name: "Turn off hallway light automatically"
      icon: mdi:ceiling

    automation.turn_off_all_lights_when_bed_off:
      <<: *customize
      friendly_name: "Turn off all lights when bedroom lights turn off"
      icon: mdi:hotel

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.deck_auto_on:
      <<: *customize
      friendly_name: "Deck Light Automatically Turned on"
      icon: mdi:nature-people
      hidden: true

    input_boolean.front_door_auto_on:
      <<: *customize
      friendly_name: "Front Door LightAutomatically Turned on"
      icon: mdi:home
      hidden: true

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Light
    ################################################
    light.all_living_room:
      <<: *customize
      friendly_name: "Living Room Lights"
      icon: mdi:television

    light.bedroom_lamp:
      <<: *customize
      friendly_name: "Bedroom Lamp"
      icon: mdi:hotel

    light.bedroom_lamp_2:
      <<: *customize
      friendly_name: "Bedroom Lamp"

    light.christmas_lights:
      <<: *customize
      friendly_name: "Christmas Lights"
      icon: mdi:led-on

    light.front_door:
      <<: *customize
      friendly_name: "Front Door"
      icon: mdi:home
    
    light.hallway:
      <<: *customize
      friendly_name: "Hallway"
      icon: mdi:ceiling-light

    light.kitchen_table:
      <<: *customize
      friendly_name: "Kitchen Table"
      icon: mdi:ceiling-light

    light.left_lamp:
      <<: *customize
      friendly_name: "Living Room Left"
      icon: mdi:lamp

    light.master_bedroom:
      <<: *customize
      friendly_name: "Master Bedroom"
      icon: mdi:hotel

    light.office:
      <<: *customize
      friendly_name: "Office"
      icon: mdi:desktop-tower

    light.office_lamp:
      <<: *customize
      friendly_name: "Office Lamp"
      icon: mdi:desktop-tower

    light.pendant_lamp:
      <<: *customize
      friendly_name: "Pendant Lamp"
      icon: mdi:ceiling-light

    light.right_lamp:
      <<: *customize
      friendly_name: "Living Room Right"
      icon: mdi:lamp

    light.tv:
      <<: *customize
      friendly_name: "TV Bias"
      icon: mdi:television

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################
    script.fade_in:
      <<: *customize
      friendly_name: "Fade In Light"
      icon: mdi:lamp

    ################################################
    ## Sensors
    ################################################
    
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:
  - id: deck_light_auto_off
    alias: deck_light_auto_off
    trigger:
      - platform: state
        entity_id: binary_sensor.deck_door_contact
        to: "off"
        for:
          seconds: 30
    condition:
      condition: state
      entity_id: input_boolean.deck_auto_on
      state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: switch.deck
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.deck_auto_on

  - id: deck_light_auto_on
    alias: deck_light_auto_on
    trigger:
      - platform: state
        entity_id: binary_sensor.deck_door_contact
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: state
          entity_id: switch.deck
          state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.deck
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.deck_auto_on

  - id: front_door_light_auto_off
    alias: front_door_light_auto_off
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_contact
        to: "off"
        for:
          seconds: 30
    condition:
      condition: state
      entity_id: input_boolean.front_door_auto_on
      state: "on"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.front_door
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.front_door_auto_on

  - id: front_door_light_auto_on
    alias: front_door_light_auto_on
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_contact
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: state
          entity_id: switch.front_door
          state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.front_door
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.front_door_auto_on

  - id: hallway_light_on_at_night
    alias: hallway_light_on_at_night
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "on"
    condition:
      condition: sun
      before: sunrise
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: light.hallway
          brightness_pct: 5
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.deck_auto_on

  - id: hallway_light_off_at_night
    alias: hallway_light_off_at_night
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion
        to: "off"
        for:
          seconds: 10
    condition:
      condition: sun
      before: sunrise
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: light.hallway

  - id: turn_off_all_lights_when_bed_off
    alias: turn_off_all_lights_when_bed_off
    trigger:
    - platform: state
      entity_id: light.master_bedroom
      to: 'off'
    condition:
      condition: time
      after: '22:00:00'
      before: '06:00:00'
    action:
    - service: scene.turn_on
      entity_id: scene.leave_home

########################
# Binary Sensors
########################
binary_sensor:

########################
# Device Trackers
########################
device_tracker:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:
  deck_auto_on:
  front_door_auto_on:

########################
# Input Numbers
########################
input_number:

########################
# Light
########################
light:
  - platform: group
    name: all_living_room
    entities:
      - light.right_lamp
      - light.left_lamp
      - light.tv
      - light.pendant_lamp
  
  - platform: group
    name: master_bedroom
    entities:
      - light.bedroom_lamp
      - light.bedroom_lamp_2
      
########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Zone
########################
zone: