---
#-------------------------------------------
#  Realtime Debugging Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "logger"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.log_level:
      <<: *customize
      friendly_name: "Log Level"
      icon: mdi:bug

  customize_glob:
    "input_select.log_*":
      icon: mdi:bug
      hidden: False

########################
# Input Select
########################
input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

###################################
##  Dynamically set the log levels without having to restart HASS or edit configuration.yaml
#- Thanks @VDRainer
###################################
automation:
  - id: log_level
    alias: log_level
    trigger:
      platform: state
      entity_id:
        - input_select.log_level
    action:
      - action: logger.set_level
        data_template:
          homeassistant.components: "{{ states.input_select.log_level.state }}"
