################################################################
## Packages / Plants
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plants'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################
    
    ################################################
    ## Frontend
    ################################################
    
    ################################################
    ## Groups
    ################################################
    group.east_hanging_nepenthes:
      <<: *customize
      friendly_name: "East Hanging Nepenthes"

    group.four_inch_nepenthes:
      <<: *customize
      friendly_name: "Four Inch Potted Nepenthes"

    group.west_hanging_nepenthes:
      <<: *customize
      friendly_name: "West Hanging Nepenthes"
    
    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.east_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Battery"
      device_class: battery

    sensor.east_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.east_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.east_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.east_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Temperature"
      device_class: temperature

    sensor.four_inch_nepenthes_battery:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Battery"
      device_class: battery

    sensor.four_inch_nepenthes_conductivity:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Conductivity"
      icon: mdi:flash

    sensor.four_inch_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Light Intensity"
      device_class: illuminance

    sensor.four_inch_nepenthes_moisture:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Moisture"
      device_class: humidity

    sensor.four_inch_nepenthes_temperature:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Temperature"
      device_class: temperature

    sensor.west_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Battery"
      device_class: battery

    sensor.west_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.west_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.west_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.west_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Temperature"
      device_class: temperature

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:
  east_hanging_nepenthes:
    entities:
      - sensor.east_hanging_nepenthes_battery
      - sensor.east_hanging_nepenthes_conductivity
      - sensor.east_hanging_nepenthes_light_intensity
      - sensor.east_hanging_nepenthes_moisture
      - sensor.east_hanging_nepenthes_temperature

  four_inch_nepenthes:
    entities:
      - sensor.four_inch_nepenthes_battery
      - sensor.four_inch_nepenthes_conductivity
      - sensor.four_inch_nepenthes_light_intensity
      - sensor.four_inch_nepenthes_moisture
      - sensor.four_inch_nepenthes_temperature

  west_hanging_nepenthes:
    entities:
      - sensor.west_hanging_nepenthes_battery
      - sensor.west_hanging_nepenthes_conductivity
      - sensor.west_hanging_nepenthes_light_intensity
      - sensor.west_hanging_nepenthes_moisture
      - sensor.west_hanging_nepenthes_temperature


########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: miflora
    name: east_hanging_nepenthes
    mac: 'C4:7C:8D:66:4C:51'
    median: 5

  - platform: miflora
    name: west_hanging_nepenthes
    mac: 'C4:7C:8D:66:4E:57'
    median: 5
    
  - platform: miflora
    name: four_inch_nepenthes
    mac: 'C4:7C:8D:66:4E:B3'
    median: 5


########################
# Switch
########################
switch:

########################
# Zone
########################
zone: