################################################################
## Packages / Plants
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "plants"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Plant
    ################################################
    plant.east_hanging_nepenthes:
      <<: *customize
      friendly_name: "East Hanging Nepenthes"

    plant.four_inch_nepenthes:
      <<: *customize
      friendly_name: "Four Inch Potted Nepenthes"

    plant.monstera:
      <<: *customize
      friendly_name: "Monstera"

    plant.west_hanging_nepenthes:
      <<: *customize
      friendly_name: "West Hanging Nepenthes"

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.east_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Battery"
      device_class: battery

    sensor.east_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.east_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.east_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.east_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Temperature"
      device_class: temperature

    sensor.four_inch_nepenthes_battery:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Battery"
      device_class: battery

    sensor.four_inch_nepenthes_conductivity:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Conductivity"
      icon: mdi:flash

    sensor.four_inch_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Light Intensity"
      device_class: illuminance

    sensor.four_inch_nepenthes_moisture:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Moisture"
      device_class: humidity

    sensor.four_inch_nepenthes_temperature:
      <<: *customize
      friendly_name: "Four Inch Nepenthes Temperature"
      device_class: temperature

    sensor.monstera_battery:
      <<: *customize
      friendly_name: "Monstera Battery"
      device_class: battery

    sensor.monstera_conductivity:
      <<: *customize
      friendly_name: "Monstera Conductivity"
      icon: mdi:flash

    sensor.monstera_light_intensity:
      <<: *customize
      friendly_name: "Monstera Light Intensity"
      device_class: illuminance

    sensor.monstera_moisture:
      <<: *customize
      friendly_name: "Monstera Moisture"
      device_class: humidity

    sensor.monstera_temperature:
      <<: *customize
      friendly_name: "Monstera Temperature"
      device_class: temperature

    sensor.west_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Battery"
      device_class: battery

    sensor.west_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.west_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.west_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.west_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Temperature"
      device_class: temperature

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: carnivorous_plants_off
    alias: carnivorous_plants_off
    trigger:
      - platform: time
        at: "20:30:00"
    action:
      - service: switch.turn_off
        entity_id: switch.carnivorous_plants_light

  - id: carnivorous_plants_on
    alias: carnivorous_plants_on
    trigger:
      - platform: time
        at: "06:30:00"
    action:
      - service: switch.turn_on
        entity_id: switch.carnivorous_plants_light
########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Plant
########################
plant:
  # https://raw.githubusercontent.com/khronimo/MiFloraDB/master/PlantDB_5335_U0.csv
  east_hanging_nepenthes:
    sensors:
      battery: sensor.east_hanging_nepenthes_battery
      conductivity: sensor.east_hanging_nepenthes_conductivity
      brightness: sensor.east_hanging_nepenthes_light_intensity
      moisture: sensor.east_hanging_nepenthes_moisture
      temperature: sensor.east_hanging_nepenthes_temperature
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

  four_inch_nepenthes:
    sensors:
      battery: sensor.four_inch_nepenthes_battery
      conductivity: sensor.four_inch_nepenthes_conductivity
      brightness: sensor.four_inch_nepenthes_light_intensity
      moisture: sensor.four_inch_nepenthes_moisture
      temperature: sensor.four_inch_nepenthes_temperature
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

  monstera:
    sensors:
      battery: sensor.monstera_battery
      conductivity: sensor.monstera_conductivity
      brightness: sensor.monstera_light_intensity
      moisture: sensor.monstera_moisture
      temperature: sensor.monstera_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 54
    max_temperature: 90
    min_brightness: 800
    max_brightness: 15000
    min_battery: 10

  terrarium:
    sensors:
      battery: sensor.terrarium_battery
      conductivity: sensor.terrarium_conductivity
      brightness: sensor.terrarium_light_intensity
      moisture: sensor.terrarium_moisture
      temperature: sensor.terrarium_temperature

  west_hanging_nepenthes:
    sensors:
      battery: sensor.west_hanging_nepenthes_battery
      conductivity: sensor.west_hanging_nepenthes_conductivity
      brightness: sensor.west_hanging_nepenthes_light_intensity
      moisture: sensor.west_hanging_nepenthes_moisture
      temperature: sensor.west_hanging_nepenthes_temperature
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: mqtt
    name: east_hanging_nepenthes_battery
    state_topic: haplants/sensor/east_hanging_nepenthes_battery/state
    unit_of_measurement: "%"
    device_class: battery

  - platform: mqtt
    name: east_hanging_nepenthes_conductivity
    state_topic: haplants/sensor/east_hanging_nepenthes_conductivity/state
    unit_of_measurement: "\u00b5S/cm"
    icon: mdi:flash-circle

  - platform: mqtt
    name: east_hanging_nepenthes_light_intensity
    state_topic: haplants/sensor/east_hanging_nepenthes_light_intensity/state
    unit_of_measurement: "lx"
    device_class: illuminance

  - platform: mqtt
    name: east_hanging_nepenthes_moisture
    state_topic: haplants/sensor/east_hanging_nepenthes_moisture/state
    unit_of_measurement: "%"
    icon: mdi:water-percent

  - platform: mqtt
    name: east_hanging_nepenthes_temperature
    state_topic: haplants/sensor/east_hanging_nepenthes_temperature/state
    unit_of_measurement: "\u00b0F"
    device_class: temperature

  - platform: mqtt
    name: four_inch_nepenthes_battery
    state_topic: haplants/sensor/four_inch_nepenthes_battery/state
    unit_of_measurement: "%"
    device_class: battery

  - platform: mqtt
    name: four_inch_nepenthes_conductivity
    state_topic: haplants/sensor/four_inch_nepenthes_conductivity/state
    unit_of_measurement: "\u00b5S/cm"
    icon: mdi:flash-circle

  - platform: mqtt
    name: four_inch_nepenthes_light_intensity
    state_topic: haplants/sensor/four_inch_nepenthes_light_intensity/state
    unit_of_measurement: "lx"
    device_class: illuminance

  - platform: mqtt
    name: four_inch_nepenthes_moisture
    state_topic: haplants/sensor/four_inch_nepenthes_moisture/state
    unit_of_measurement: "%"
    icon: mdi:water-percent

  - platform: mqtt
    name: four_inch_nepenthes_temperature
    state_topic: haplants/sensor/four_inch_nepenthes_temperature/state
    unit_of_measurement: "\u00b0F"
    device_class: temperature

  - platform: mqtt
    name: monstera_battery
    state_topic: haplants/sensor/monstera_battery/state
    unit_of_measurement: "%"
    device_class: battery

  - platform: mqtt
    name: monstera_conductivity
    state_topic: haplants/sensor/monstera_conductivity/state
    unit_of_measurement: "\u00b5S/cm"
    icon: mdi:flash-circle

  - platform: mqtt
    name: monstera_light_intensity
    state_topic: haplants/sensor/monstera_light_intensity/state
    unit_of_measurement: "lx"
    device_class: illuminance

  - platform: mqtt
    name: monstera_moisture
    state_topic: haplants/sensor/monstera_moisture/state
    unit_of_measurement: "%"
    icon: mdi:water-percent

  - platform: mqtt
    name: monstera_temperature
    state_topic: haplants/sensor/monstera_temperature/state
    unit_of_measurement: "\u00b0F"
    device_class: temperature

  - platform: mqtt
    name: west_hanging_nepenthes_battery
    state_topic: haplants/sensor/west_hanging_nepenthes_battery/state
    unit_of_measurement: "%"
    device_class: battery

  - platform: mqtt
    name: terrarium_battery
    state_topic: haplants/sensor/terrarium_battery/state
    unit_of_measurement: "%"
    device_class: battery

  - platform: mqtt
    name: terrarium_conductivity
    state_topic: haplants/sensor/terrarium_conductivity/state
    unit_of_measurement: "\u00b5S/cm"
    icon: mdi:flash-circle

  - platform: mqtt
    name: terrarium_light_intensity
    state_topic: haplants/sensor/terrarium_light_intensity/state
    unit_of_measurement: "lx"
    device_class: illuminance

  - platform: mqtt
    name: terrarium_moisture
    state_topic: haplants/sensor/terrarium_moisture/state
    unit_of_measurement: "%"
    icon: mdi:water-percent

  - platform: mqtt
    name: terrarium_temperature
    state_topic: haplants/sensor/terrarium_temperature/state
    unit_of_measurement: "\u00b0F"
    device_class: temperature

  - platform: mqtt
    name: west_hanging_nepenthes_conductivity
    state_topic: haplants/sensor/west_hanging_nepenthes_conductivity/state
    unit_of_measurement: "\u00b5S/cm"
    icon: mdi:flash-circle

  - platform: mqtt
    name: west_hanging_nepenthes_light_intensity
    state_topic: haplants/sensor/west_hanging_nepenthes_light_intensity/state
    unit_of_measurement: "lx"
    device_class: illuminance
    #icon:

  - platform: mqtt
    name: west_hanging_nepenthes_moisture
    state_topic: haplants/sensor/west_hanging_nepenthes_moisture/state
    unit_of_measurement: "%"
    #device_class: moisture
    icon: mdi:water-percent

  - platform: mqtt
    name: west_hanging_nepenthes_temperature
    state_topic: haplants/sensor/west_hanging_nepenthes_temperature/state
    unit_of_measurement: "\u00b0F"
    device_class: temperature
    #icon:

#   - platform: miflora
#     name: east_hanging_nepenthes
#     mac: 'C4:7C:8D:66:4C:51'
#     median: 7

#   - platform: miflora
#     name: west_hanging_nepenthes
#     mac: 'C4:7C:8D:66:4E:57'
#     median: 7

#   - platform: miflora
#     name: four_inch_nepenthes
#     mac: 'C4:7C:8D:66:4E:B3'
#     median: 7

#   - platform: miflora
#     name: monstera
#     mac: 'C4:7C:8D:66:47:C0'
#     median: 7

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
