################################################################
## Packages / Plants
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "plants"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Plant
    ################################################
    plant.east_hanging_nepenthes:
      <<: *customize
      friendly_name: "East Hanging Nepenthes"

    plant.four_inch_nepenthes:
      <<: *customize
      friendly_name: "Four Inch Potted Nepenthes"

    plant.monstera:
      <<: *customize
      friendly_name: "Monstera"

    plant.west_hanging_nepenthes:
      <<: *customize
      friendly_name: "West Hanging Nepenthes"

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.east_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Battery"
      device_class: battery

    sensor.east_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.east_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.east_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.east_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "East Hanging Nepenthes Temperature"
      device_class: temperature

    sensor.monstera_battery:
      <<: *customize
      friendly_name: "Monstera Battery"
      device_class: battery

    sensor.monstera_conductivity:
      <<: *customize
      friendly_name: "Monstera Conductivity"
      icon: mdi:flash

    sensor.monstera_light_intensity:
      <<: *customize
      friendly_name: "Monstera Light Intensity"
      device_class: illuminance

    sensor.monstera_moisture:
      <<: *customize
      friendly_name: "Monstera Moisture"
      device_class: humidity

    sensor.monstera_temperature:
      <<: *customize
      friendly_name: "Monstera Temperature"
      device_class: temperature

    sensor.west_hanging_nepenthes_battery:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Battery"
      device_class: battery

    sensor.west_hanging_nepenthes_conductivity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Conductivity"
      icon: mdi:flash

    sensor.west_hanging_nepenthes_light_intensity:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Light Intensity"
      device_class: illuminance

    sensor.west_hanging_nepenthes_moisture:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Moisture"
      device_class: humidity

    sensor.west_hanging_nepenthes_temperature:
      <<: *customize
      friendly_name: "West Hanging Nepenthes Temperature"
      device_class: temperature

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel: []

########################
## Automation
########################
automation:
  - id: carnivorous_plants_off
    alias: carnivorous_plants_off
    trigger:
      - trigger: time
        at: "20:30:00"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.carnivorous_plants_light

  - id: carnivorous_plants_on
    alias: carnivorous_plants_on
    trigger:
      - trigger: time
        at: "06:30:00"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.carnivorous_plants_light

  - id: water_notification
    alias: water_notification
    trigger:
      - trigger: time
        at: "12:15:00"
    condition:
      - alias: "condition alias (name)"
        condition: template
        value_template: >-
          {{states.plant| selectattr('state', 'eq', 'problem')| list | length > 0}}
    action:
      - action: notify.all
        data:
          data:
            url: "/ryan-new-mushroom/plants"
          message: >-
            {%- for plant in states.plant -%}
              {%- set data = namespace(problems=[]) -%}
                {%- for problem in plant.attributes.problem.split(', ') if ((problem not in ['none','brightness low', 'conductivity low'])) -%}
                  {%- set data.problems = data.problems + [problem] -%}
                {%- endfor -%}
                {%- if data.problems | length > 0 -%}
                      {{- plant.attributes.friendly_name -}}
                  {%- if 'moisture low' in data.problems -%}
                    {{- ' - moisture: ' -}}{{- states[plant.attributes.sensors.moisture].state_with_unit -}}
                  {%- endif -%}
                  {%- if 'battery unavailable' in data.problems -%}
                    {{- ', battery likely dead' }}
                  {%- endif -%}
                {% endif %}
            {% endfor -%}

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Cameras
########################
camera: []

########################
# Device Trackers
########################
device_tracker: []

########################
# Frontend
########################
frontend: {}

########################
# Groups
########################
group: {}

########################
# Input Booleans
########################
input_boolean: {}

########################
# Input Numbers
########################
input_number: {}

########################
# Input Select
########################
input_select: {}

########################
# iOS
########################
ios: {}

########################
# Light
########################
light: []

########################
# MQTT
########################
mqtt:
  sensor:
    - name: east_hanging_nepenthes_battery
      state_topic: haplants/sensor/east_hanging_nepenthes_battery/state
      unit_of_measurement: "%"
      device_class: battery

    - name: east_hanging_nepenthes_conductivity
      state_topic: haplants/sensor/east_hanging_nepenthes_conductivity/state
      unit_of_measurement: "\u00b5S/cm"
      icon: mdi:flash-circle

    - name: east_hanging_nepenthes_light_intensity
      state_topic: haplants/sensor/east_hanging_nepenthes_light_intensity/state
      unit_of_measurement: "lx"
      device_class: illuminance

    - name: east_hanging_nepenthes_moisture
      state_topic: haplants/sensor/east_hanging_nepenthes_moisture/state
      unit_of_measurement: "%"
      icon: mdi:water-percent

    #
    - name: elkhorn_battery
      state_topic: haplants/sensor/elkhorn_battery/state
      unit_of_measurement: "%"
      device_class: battery

    - name: elkhorn_conductivity
      state_topic: haplants/sensor/elkhorn_conductivity/state
      unit_of_measurement: "\u00b5S/cm"
      icon: mdi:flash-circle

    - name: elkhorn_light_intensity
      state_topic: haplants/sensor/elkhorn_illuminance/state
      unit_of_measurement: "lx"
      device_class: illuminance

    - name: elkhorn_moisture
      state_topic: haplants/sensor/elkhorn_moisture/state
      unit_of_measurement: "%"
      icon: mdi:water-percent

    - name: elkhorn_temperature
      state_topic: haplants/sensor/elkhorn_temperature/state
      unit_of_measurement: "\u00b0F"
      device_class: temperature
    #

    - name: east_hanging_nepenthes_temperature
      state_topic: haplants/sensor/east_hanging_nepenthes_temperature/state
      unit_of_measurement: "\u00b0F"
      device_class: temperature

    - name: west_hanging_nepenthes_battery
      state_topic: haplants/sensor/west_hanging_nepenthes_battery/state
      unit_of_measurement: "%"
      device_class: battery

    - name: terrarium_battery
      state_topic: haplants/sensor/terrarium_battery/state
      unit_of_measurement: "%"
      device_class: battery

    - name: terrarium_conductivity
      state_topic: haplants/sensor/terrarium_conductivity/state
      unit_of_measurement: "\u00b5S/cm"
      icon: mdi:flash-circle

    - name: terrarium_light_intensity
      state_topic: haplants/sensor/terrarium_light_intensity/state
      unit_of_measurement: "lx"
      device_class: illuminance

    - name: terrarium_moisture
      state_topic: haplants/sensor/terrarium_moisture/state
      unit_of_measurement: "%"
      icon: mdi:water-percent

    - name: terrarium_temperature
      state_topic: haplants/sensor/terrarium_temperature/state
      unit_of_measurement: "\u00b0F"
      device_class: temperature

    - name: west_hanging_nepenthes_conductivity
      state_topic: haplants/sensor/west_hanging_nepenthes_conductivity/state
      unit_of_measurement: "\u00b5S/cm"
      icon: mdi:flash-circle

    - name: west_hanging_nepenthes_light_intensity
      state_topic: haplants/sensor/west_hanging_nepenthes_light_intensity/state
      unit_of_measurement: "lx"
      device_class: illuminance
      #icon:

    - name: west_hanging_nepenthes_moisture
      state_topic: haplants/sensor/west_hanging_nepenthes_moisture/state
      unit_of_measurement: "%"
      #device_class: moisture
      icon: mdi:water-percent

    - name: west_hanging_nepenthes_temperature
      state_topic: haplants/sensor/west_hanging_nepenthes_temperature/state
      unit_of_measurement: "\u00b0F"
      device_class: temperature
########################
# Plant
########################
plant:
  # https://raw.githubusercontent.com/khronimo/MiFloraDB/master/PlantDB_5335_U0.csv
  bird_of_paradise:
    sensors:
      battery: sensor.bird_of_paradise_battery
      conductivity: sensor.bird_of_paradise_conductivity
      brightness: sensor.bird_of_paradise_illuminance
      moisture: sensor.bird_of_paradise_moisture
      temperature: sensor.bird_of_paradise_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 4000
    max_brightness: 000
    min_temperature: 5
    max_temperature: 35
    min_battery: 10

  birds_nest_fern:
    sensors:
      battery: sensor.bird_nest_fern_battery
      conductivity: sensor.bird_nest_fern_conductivity
      brightness: sensor.bird_nest_fern_illuminance
      moisture: sensor.bird_nest_fern_moisture
      temperature: sensor.bird_nest_fern_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_brightness: 500
    max_brightness: 12000
    min_temperature: 50
    max_temperature: 95
    min_battery: 10

  bromeliad:
    sensors:
      battery: sensor.bromeliad_battery
      conductivity: sensor.bromeliad_conductivity
      brightness: sensor.bromeliad_illuminance
      moisture: sensor.bromeliad_moisture
      temperature: sensor.bromeliad_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 300
    max_conductivity: 1000
    min_brightness: 800
    max_brightness: 27000
    min_temperature: 50
    max_temperature: 99
    min_battery: 10

  elkhorn:
    sensors:
      battery: sensor.elkhorn_fern_battery
      conductivity: sensor.elkhorn_fern_conductivity
      brightness: sensor.elkhorn_fern_illuminance
      moisture: sensor.elkhorn_fern_moisture
      temperature: sensor.elkhorn_fern_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 1500
    min_brightness: 300
    max_brightness: 4000
    min_temperature: 50
    max_temperature: 90
    min_battery: 10

  monstera:
    sensors:
      battery: sensor.monstera_battery
      conductivity: sensor.monstera_conductivity
      brightness: sensor.monstera_illuminance
      moisture: sensor.monstera_moisture
      temperature: sensor.monstera_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 53
    max_temperature: 89
    min_brightness: 800
    max_brightness: 15000
    min_battery: 10

  north_hanging_nepenthes:
    sensors:
      battery: sensor.n_nepenthes_battery
      conductivity: sensor.n_nepenthes_conductivity
      brightness: sensor.n_nepenthes_illuminance
      moisture: sensor.n_nepenthes_moisture
      temperature: sensor.n_nepenthes_temperature
    min_brightness: 1500
    max_brightness: 35000
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

  rubber_plant:
    sensors:
      battery: sensor.rubber_plant_battery
      conductivity: sensor.rubber_plant_conductivity
      brightness: sensor.rubber_plant_illuminance
      moisture: sensor.rubber_plant_moisture
      temperature: sensor.rubber_plant_temperature
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 50
    max_temperature: 90
    min_brightness: 1000
    max_brightness: 30000
    min_battery: 10

  four_inch_nepenthes:
    sensors:
      battery: sensor.4in_nepenthes_battery
      conductivity: sensor.4in_nepenthes_conductivity
      brightness: sensor.4in_nepenthes_illuminance
      moisture: sensor.4in_nepenthe_moisture
      temperature: sensor.4in_nepenthes_temperature
    min_brightness: 1500
    max_brightness: 35000
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

  terrarium:
    sensors:
      battery: sensor.terrarium_battery
      conductivity: sensor.terrarium_conductivity
      brightness: sensor.terrarium_light_intensity
      moisture: sensor.terrarium_moisture
      temperature: sensor.terrarium_temperature

  sansevieria_victoria:
    sensors:
      battery: sensor.sanservia_victoria_battery
      conductivity: sensor.sanservia_victoria_conductivity
      brightness: sensor.sanservia_victoria_illuminance
      moisture: sensor.sanservia_victoria_moisture
      temperature: sensor.sanservia_victoria_temperature
    min_brightness: 1500
    max_brightness: 60000
    min_moisture: 7
    max_moisture: 50
    min_conductivity: 300
    max_conductivity: 1000
    min_temperature: 50
    max_temperature: 90
    min_battery: 10

  south_hanging_nepenthes:
    sensors:
      battery: sensor.s_nepenthes_battery
      conductivity: sensor.s_nepenthes_conductivity
      brightness: sensor.s_nepenthes_illuminance
      moisture: sensor.s_nepenthes_moisture
      temperature: sensor.s_nepenthes_temperature
    min_brightness: 1500
    max_brightness: 35000
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 50
    max_conductivity: 1500
    min_temperature: 54
    max_temperature: 95
    min_battery: 10

  zz_plant:
    sensors:
      battery: sensor.zz_plant_battery
      conductivity: sensor.zz_plant_conductivity
      brightness: sensor.zz_plant_illuminance
      moisture: sensor.zz_plant_moisture
      temperature: sensor.zz_plant_temperature
    min_brightness: 600
    max_brightness: 20000
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 50
    max_temperature: 89
    min_battery: 10

########################
# Scenes
########################
scene: {}

########################
# Scripts
########################
script: {}

########################
# Sensor
########################
sensor: []

########################
# Switch
########################
switch: {}

########################
# Zone
########################
zone: {}
