################################################################
## Packages / SmartThings
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "smartthings"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.basement_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Basement Door"

    binary_sensor.se_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South East Basement Window"

    binary_sensor.sw_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South West Basement Window"

    binary_sensor.deck_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Deck Door"

    binary_sensor.downstairs_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Downstairs Motion"

    binary_sensor.ene_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "East North East Window"

    binary_sensor.ese_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "East South East Window"

    binary_sensor.front_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Front Door"

    binary_sensor.master_bedroom_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Master Bedroom Motion"

    binary_sensor.nne_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "North North East Window"

    binary_sensor.north_kitchen_sink_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Kitchen Sink Window"

    binary_sensor.north_master_bedroom_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Master Bedroom Window"

    binary_sensor.nw_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Master Bedroom Window"

    binary_sensor.office_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Office Motion"

    binary_sensor.office_north_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Office Window"

    binary_sensor.sse_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South South East Living Room Window"

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.arrival_sensor_battery:
      <<: *customize
      friendly_name: "Arrival Sensor Battery"
      icon: mdi:battery

    sensor.basement_door_battery:
      <<: *customize
      friendly_name: "Basement Door Battery"
      icon: mdi:battery

    sensor.bathroom_battery:
      <<: *customize
      friendly_name: "Bathroom Battery"
      icon: mdi:battery

    sensor.bathroom_humidity:
      <<: *customize
      friendly_name: "Bathroom Humidity"
      icon: mdi:water-percent

    sensor.bathroom_temperature:
      <<: *customize
      friendly_name: "Bathroom Temperature"

    sensor.deck_door_battery:
      <<: *customize
      friendly_name: "Deck Door Battery"
      icon: mdi:battery

    sensor.downstairs_illumination:
      <<: *customize
      friendly_name: "Downstairs Illumination"
      icon: mdi:brightness-6

    sensor.downstairs_motion_battery:
      <<: *customize
      friendly_name: "Downstairs Motion Battery"
      icon: mdi:battery

    sensor.ene_window_battery:
      <<: *customize
      friendly_name: "East North East Window Battery"
      icon: mdi:battery

    sensor.ese_window_battery:
      <<: *customize
      friendly_name: "East South East Window Battery"
      icon: mdi:battery

    sensor.front_door_battery:
      <<: *customize
      friendly_name: "Front Door Battery"
      icon: mdi:battery

    sensor.guest_room_battery:
      <<: *customize
      friendly_name: "Guest Room Battery"
      icon: mdi:battery

    sensor.guest_room_button_battery:
      <<: *customize
      friendly_name: "Guest Room Button Battery"
      icon: mdi:battery

    sensor.guest_room_humidity:
      <<: *customize
      friendly_name: "Guest Room Humidity"
      icon: mdi:water-percent

    sensor.guest_room_temperature:
      <<: *customize
      friendly_name: "Guest Room Temperature"

    sensor.living_room_battery:
      <<: *customize
      friendly_name: "Living Room Battery"
      icon: mdi:battery

    sensor.living_room_button_battery:
      <<: *customize
      friendly_name: "Living Room Button Battery"
      icon: mdi:battery

    sensor.living_room_humidity:
      <<: *customize
      friendly_name: "Living Room Humidity"
      icon: mdi:water-percent

    sensor.living_room_temperature:
      <<: *customize
      friendly_name: "Living Room Temperature"

    sensor.master_bedroom_battery:
      <<: *customize
      friendly_name: "Master Bedroom Battery"
      icon: mdi:battery

    sensor.master_bedroom_humidity:
      <<: *customize
      friendly_name: "Master Bedroom Humidity"
      icon: mdi:water-percent

    sensor.master_bedroom_illumination:
      <<: *customize
      friendly_name: "Master Bedroom Illumination"
      icon: mdi:brightness-6

    sensor.master_bedroom_motion_battery:
      <<: *customize
      friendly_name: "Master Bedroom Motion Sensor Battery"
      icon: mdi:battery

    sensor.master_bedroom_temperature:
      <<: *customize
      friendly_name: "Master Bedroom Temperature"

    sensor.motion_sensor_battery:
      <<: *customize
      friendly_name: "Living Room Motion Sensor Battery"
      icon: mdi:battery

    sensor.north_kitchen_sink_window_battery:
      <<: *customize
      friendly_name: "North Kitchen Sink Window Battery"
      icon: mdi:battery

    sensor.north_master_bedroom_window_battery:
      <<: *customize
      friendly_name: "North Master Bedroom Window Battery"
      icon: mdi:battery

    sensor.nne_window_battery:
      <<: *customize
      friendly_name: "North North East Window Battery"
      icon: mdi:battery

    sensor.nw_basement_window_battery:
      <<: *customize
      friendly_name: "North West Basement Window Battery"
      icon: mdi:battery

    sensor.office_motion_battery:
      <<: *customize
      friendly_name: "Office Motion Sensor Battery"
      icon: mdi:battery

    sensor.office_illumination:
      <<: *customize
      friendly_name: "Office Illumination"
      icon: mdi:brightness-6

    sensor.office_north_window_battery:
      <<: *customize
      friendly_name: "Office North Window Battery"
      icon: mdi:battery

    sensor.se_basement_window_battery:
      <<: *customize
      friendly_name: "South East Basement Window Battery"
      icon: mdi:battery

    sensor.sse_window_battery:
      <<: *customize
      friendly_name: "South South East Window Battery"
      icon: mdi:battery

    sensor.sw_basement_window_battery:
      <<: *customize
      friendly_name: "South West Basement Window Battery"
      icon: mdi:battery

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:

########################
# Binary Sensors
########################
binary_sensor:
  - platform: mqtt
    name: basement_door_contact
    state_topic: "smartthings/Basement Door Sensor/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: deck_door_contact
    state_topic: "smartthings/Deck Door/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: downstairs_motion
    state_topic: "smartthings/Downstairs Motion Sensor/motion/state"
    payload_on: "active"
    payload_off: "inactive"
    retain: true
    force_update: true

  - platform: mqtt
    name: ene_window_contact
    state_topic: "smartthings/East North East Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: ese_window_contact
    state_topic: "smartthings/East South East/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: front_door_contact
    state_topic: "smartthings/Front Door Sensor/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: guest_room_button
    state_topic: "smartthings/Guest Room Button/button/state"
    payload_on: "pushed"
    payload_off: "released"
    retain: true
    force_update: true

  - platform: mqtt
    name: living_room_button
    state_topic: "smartthings/Living Room Button/button/state"
    payload_on: "pushed"
    payload_off: "released"
    retain: true
    force_update: true

  - platform: mqtt
    name: master_bedroom_motion
    state_topic: "smartthings/Master Bedroom Motion Sensor/motion/state"
    payload_on: "active"
    payload_off: "inactive"
    retain: true
    force_update: true

  - platform: mqtt
    name: north_kitchen_sink_window_contact
    state_topic: "smartthings/North Kitchen Sink Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: north_master_bedroom_window_contact
    state_topic: "smartthings/North Master Bedroom Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: nne_window_contact
    state_topic: "smartthings/North North East Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: nw_basement_window_contact
    state_topic: "smartthings/North West Basement Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: office_motion
    state_topic: "smartthings/Office Motion Sensor/motion/state"
    payload_on: "active"
    payload_off: "inactive"
    retain: true
    force_update: true

  - platform: mqtt
    name: office_north_window_contact
    state_topic: "smartthings/Office North Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: se_basement_window_contact
    state_topic: "smartthings/Basement South East Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: sse_window_contact
    state_topic: "smartthings/South South East Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

  - platform: mqtt
    name: sw_basement_window_contact
    state_topic: "smartthings/Basement South West Window/contact/state"
    payload_on: "open"
    payload_off: "closed"
    retain: true
    force_update: true

########################
# Device Trackers
########################
device_tracker:
  - platform: mqtt
    devices:
      arrival_sensor: "smartthings/Arrival Sensor/presence/state"

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: mqtt
    name: arrival_sensor_battery
    state_topic: "smartthings/Arrival Sensor/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: basement_door_battery
    state_topic: "smartthings/Basement Door Sensor/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "smartthings/Bathroom/battery/state"
    name: bathroom_battery
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "smartthings/Bathroom/humidity/state"
    name: bathroom_humidity
    retain: true
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Bathroom/temperature/state"
    name: bathroom_temperature
    unit_of_measurement: "째F"
    retain: true
    force_update: true

  - platform: mqtt
    name: deck_door_battery
    state_topic: "smartthings/Deck Door/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: downstairs_illumination
    state_topic: "smartthings/Downstairs Motion Sensor/illumination/state"
    unit_of_measurement: "lux"
    retain: true
    force_update: true

  - platform: mqtt
    name: downstairs_motion_battery
    state_topic: "smartthings/Downstairs Motion Sensor/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: ene_window_battery
    state_topic: "smartthings/East North East Window/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: ese_window_battery
    state_topic: "smartthings/East South East Window/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: front_door_battery
    state_topic: "smartthings/Front Door Sensor/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "smartthings/Guest/battery/state"
    name: guest_room_battery
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: guest_room_button_battery
    state_topic: "smartthings/Guest Room Button/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "smartthings/Guest/humidity/state"
    name: guest_room_humidity
    retain: true
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Guest/temperature/state"
    name: guest_room_temperature
    retain: true
    unit_of_measurement: "째F"
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Livingroom/battery/state"
    name: living_room_battery
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: living_room_button_battery
    state_topic: "smartthings/Living Room Button/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "smartthings/Livingroom/humidity/state"
    name: living_room_humidity
    retain: true
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Livingroom/temperature/state"
    name: living_room_temperature
    retain: true
    unit_of_measurement: "째F"
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Master/battery/state"
    name: master_bedroom_battery
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: master_bedroom_humidity
    state_topic: "smartthings/Master/humidity/state"
    retain: true
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    name: master_bedroom_illumination
    state_topic: "smartthings/Master Bedroom Motion Sensor/illumination/state"
    unit_of_measurement: "lux"
    retain: true
    force_update: true

  - platform: mqtt
    name: master_bedroom_motion_battery
    state_topic: "smartthings/Master Bedroom Motion Sensor/battery/state"
    retain: true
    unit_of_measurement: "%"
    force_update: true

  - platform: mqtt
    name: master_bedroom_temperature
    state_topic: "smartthings/Master/temperature/state"
    unit_of_measurement: "째F"
    retain: true
    force_update: true

  - platform: template
    sensors:
      motion_sensor_battery:
        value_template: "{{ states.binary_sensor.motion_sensor_motion.attributes.battery_level |int}}"
        entity_id: binary_sensor.motion_sensor_motion
        unit_of_measurement: "%"

  - platform: mqtt
    name: north_kitchen_sink_window_battery
    state_topic: "smartthings/North Kitchen Sink Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: north_master_bedroom_window_battery
    state_topic: "smartthings/North Master Bedroom Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: nne_window_battery
    state_topic: "smartthings/North North East Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: nw_basement_window_battery
    state_topic: "smartthings/North West Basement Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: office_motion_battery
    state_topic: "smartthings/Office Motion Sensor/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: office_illumination
    state_topic: "smartthings/Office Motion Sensor/illumination/state"
    unit_of_measurement: "lux"
    retain: true
    force_update: true

  - platform: mqtt
    name: office_north_window_battery
    state_topic: "smartthings/Office North Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    state_topic: "smartthings/Basement South East Window/battery/state"
    name: se_basement_window_battery
    retain: true
    force_update: true
    unit_of_measurement: "%"

  - platform: mqtt
    name: sse_window_battery
    state_topic: "smartthings/South South East Window/battery/state"
    unit_of_measurement: "%"
    retain: true
    force_update: true

  - platform: mqtt
    name: sw_basement_window_battery
    state_topic: "smartthings/Basement South West Window/battery/state"
    retain: true
    force_update: true
    unit_of_measurement: "%"

########################
# Zone
########################
zone:
