# Template package scaffold for creating new domain packages.
# This file is mostly a structured starting point rather than active house logic; copy it when adding a new package and replace the placeholders.

################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "TO_CHANGE"

      tracked_devices: &tracked_devices
        <<: *customize
        devices:
          - device_tracker.bayesian_zeke_home

      track_ios: &track_ios
        <<: *customize
        track_ios: true

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Climate
    ################################################

    ################################################
    ## Covers
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## Input Datetime
    ################################################

    ################################################
    ## Input Text
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ##  Notify
    ################################################

    ################################################
    ##  Octoprint
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scenes
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Weather
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel: []

########################
## Automation
########################
automation: []

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Cameras
########################
camera: []

########################
# Climate
########################
climate: []

########################
# Covers
########################
cover: []

########################
# Device Trackers
########################
device_tracker: []

########################
# Fans
########################
fan: []

########################
# Frontend
########################
frontend: {}

########################
# Groups
########################
group: {}

########################
# Input Booleans
########################
input_boolean: {}

########################
# Input DateTime
########################
input_datetime: {}

########################
# Input Numbers
########################
input_number: {}

########################
# Input Select
########################
input_select: {}

########################
# Input Text
########################
input_text: {}

########################
# iOS
########################
ios: {}

########################
# Light
########################
light: []

########################
# Media Player
########################
media_player: []

########################
# Notify
########################
notify: []

########################
# Octoprint
########################
# YAML Deprecated 2022.2
# octoprint:

########################
# Plant
########################
plant: {}

########################
# Scenes
########################
scene: []

########################
# Scripts
########################
script: {}

########################
# Sensor
########################
sensor: []

########################
# Switch
########################
switch: []

########################
# Template
########################
template: []

########################
# Weather
########################
weather: []

########################
# Zone
########################
zone: {}

########################
# Calendar
########################
calendar: []

########################
# Counter
########################
counter: {}

########################
# Lock
########################
lock: []

########################
# MQTT
########################
mqtt: {}

########################
# Rest
########################
rest: []

########################
# Rest Command
########################
rest_command: {}

########################
# Timer
########################
timer: {}

########################
# Utility Meter
########################
utility_meter: {}

########################
# Vacuum
########################
vacuum: []
