################################################################
## Packages / Themes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "themes"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################
    automation.automatic_theme_change:
      <<: *customize
      friendly_name: "Change theme at sunset and sunrise"
    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel: []

########################
## Automation
########################
automation:
  - alias: automatic_theme_change
    id: automatic_theme_change
    trigger:
      - trigger: homeassistant
        event: start
      - trigger: state
        entity_id: sun.sun
        to: above_horizon
      - trigger: state
        entity_id: sun.sun
        to: below_horizon
    action:
      - action: frontend.set_theme
        data:
          name: >-
            {% if states.sun.sun.state == "above_horizon" %}
              ios-light-mode-dark-green
            {% else %}
              {{ ["ios-dark-mode-dark-green", "midnight_blue", "noctis-solarized", "oxfordblue", "slate_red", "synthwave"] | random }}
            {% endif %}
          # mode: dark

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Cameras
########################
camera: []

########################
# Device Trackers
########################
device_tracker: []

########################
# Frontend
########################
frontend: {}

########################
# Groups
########################
group: {}

########################
# Input Booleans
########################
input_boolean: {}

########################
# Input Numbers
########################
input_number: {}

########################
# Input Select
########################
input_select: {}

########################
# iOS
########################
ios: {}

########################
# Light
########################
light: []

########################
# Scenes
########################
scene: []

########################
# Scripts
########################
script: {}

########################
# Sensor
########################
sensor: []

########################
# Zone
########################
zone: {}
