################################################################
## Packages / Todoist
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "todoist"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false


    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel: []

########################
## Automation
########################
automation: []

########################
# Binary Sensors
########################
binary_sensor: []

########################
# Calendar
########################
calendar: []
  # - platform: todoist
  #   token: !secret todoist_api_token
  #   custom_projects:
  #     - name: due_today
  #       due_date_days: 0

########################
# Cameras
########################
camera: []

########################
# Device Trackers
########################
device_tracker: []

########################
# Groups
########################
group: {}

########################
# Input Booleans
########################
input_boolean: {}

########################
# Input Numbers
########################
input_number: {}

########################
# iOS
########################
ios: {}

########################
# Light
########################
light: []

########################
# Scenes
########################
scene: []

########################
# Scripts
########################
script: []

########################
# Sensor
########################
sensor: []

########################
# Zone
########################
zone: {}
