################################################################
## Packages / utilities
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "utilities"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Climate
    ################################################

    ################################################
    ## Covers
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ##  Notify
    ################################################

    ################################################
    ##  Octoprint
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Switches
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Utility Meters
    ################################################

    ################################################
    ## Weather
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: switch_electrical_tariff
    alias: switch_electrical_tariff
    trigger:
      - platform: template
        value_template: >-
          {{ now().month == 6 and now().day == 1}}
        id: summer_rate
      - platform: template
        value_template: >-
          {{ now().month == 10 and now().day == 1}}
        id: nonsummer_rate
      # - platform: time
      #   at: input_datetime.summer_energy
      #   id: summer
      # - platform: time
      #   at: input_datetime.non_summer_energy
      #   id: nonsummer
    action:
      - service: utility_meter.next_tariff
        target:
          entity_id: utility_meter.hourly_electricity
      - service: utility_meter.next_tariff
        target:
          entity_id: utility_meter.daily_electricity
      - service: utility_meter.next_tariff
        target:
          entity_id: utility_meter.monthly_electricity
      - service: input_number.set_value
        target:
          entity_id: input_number.electrical_rate
        data:
          value: >-
            {% if trigger.id == "nonsummer_rate" %}
              .12812
            {% else %}
              .10726
            {% endif %}

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Climate
########################
climate:

########################
# Covers
########################
cover:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input DateTime
########################
input_datetime:
  summer_energy:
    has_date: true
    has_time: false
  non_summer_energy:
    has_date: true
    has_time: false

########################
# Input Numbers
########################
input_number:
  electrical_rate:
    name: Electrical Rate
    min: .00008
    max: .20000
    step: 0.00001
    mode: box
    # TODO update the unit of measure
    unit_of_measurement: EUR/kWh

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Notify
########################
notify:

########################
# Octoprint
########################
octoprint:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:

########################
# Switch
########################
switch:

########################
# Utility Meter
########################
utility_meter:
  hourly_electricity:
    source: sensor.house_electrical_meter
    cycle: hourly
    tariffs:
      - non-summer
      - summer
  daily_electricity:
    source: sensor.house_electrical_meter
    cycle: daily
    tariffs:
      - non-summer
      - summer
  monthly_electricity:
    source: sensor.house_electrical_meter
    cycle: monthly
    tariffs:
      - non-summer
      - summer

########################
# Weather
########################
weather:

########################
# Zone
########################
zone:
