################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "water_softener"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: notify_refill_salt
    alias: Notify Salt Low
    trigger:
      - platform: time
        at: "16:00:00"
    condition:
      - alias: "Salt Level Low"
        condition: numeric_state
        entity_id: sensor.water_softener_salt_level
        above: 400
    action:
      - alias: "Notify"
        service: notify.all
        data_template:
          message: >-
            Water softener salt is low at {{states('sensor.water_softener_salt_level')}} mm.

  - id: buy_more_salt
    alias: buy_more_salt
    trigger:
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Home Depot"
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Menards"
      - platform: state
        entity_id: sensor.zeke_place
        attribute: place_name
        to: "Lowes"
    condition:
      - alias: "Salt Bag Inventory Low"
        condition: numeric_state
        entity_id: input_number.bags_of_salt_at_home
        below: 2
    action:
      - service: notify.mobile_app_wethop
        data:
          title: "Buy Softener Salt"
          message: >-
            "You only have {{states("input_number.bags_of_salt_at_home")| int}} salt bags at home. How many did you buy?"
          data:
            actions:
              - action: "BOUGHT_SALT"
                title: "Purchased salt"
                activationMode: background
                authenticationRequired: false
                destructive: false
                behavior: textInput
                textInputButtonTitle: Number of bags
                textInputPlaceholder: 3
                icon: sfsymbols:bag.badge.questionmark

  - id: salt_purchased
    alias: salt_purchased
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: BOUGHT_SALT
    condition: []
    action:
      - alias: Increase Number of salt bags in inventory
        service: input_number.set_value
        entity_id: input_number.bags_of_salt_at_home
        data:
          value: >-
            {{(states("input_number.bags_of_salt_at_home")|int) + (trigger.event.data.reply_text | int)}}

  - id: temp_notify_place_name
    alias: temp_notify_place_name
    trigger:
      - platform: state
        entity_id: sensor.zeke_place
        to:
    condition: []
    action:
      - alias: "Notify"
        service: notify.all
        data_template:
          message: >-
            At place_name: {{states("sensor.zeke_place", "place_name")}}
            At place: {{states("sensor.zeke_place", "place")}}
            At named place: {{states("sensor.zeke_place", "name")}}

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Counter
########################
counter:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:
  bags_of_salt_at_home:
    name: Bags of Softener Salt at Home
    icon: mdi:shaker-outline
    min: 0
    max: 20
    mode: box
    step: 1

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: filter
    entity_id: sensor.my_water_softener_vl53l0x_sensor
    name: "Water Softener Salt Level"
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 0
      - filter: time_simple_moving_average
        window_size: "6:00"
        precision: 0

  - platform: derivative
    source: sensor.water_softener_salt_level
    name: Water Softener Level (dt=24hrs)
    round: 2
    unit_time: d
    time_window: "24:00:00" # we look at the change over the last day

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
