################################################################
## Packages / TEMPLATE
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "water_softener"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Alarm Panels
    ################################################

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Cameras
    ################################################

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Fans
    ############

    ################################################
    ## Frontend
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Input Select
    ################################################

    ################################################
    ## iOS
    ################################################

    ################################################
    ## Light
    ################################################

    ################################################
    ## Media Player
    ################################################

    ################################################
    ## Plant
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

########################
# Alarm Panel
########################
alarm_control_panel:

########################
## Automation
########################
automation:
  - id: notify_refill_salt
    alias: Notify Salt Low
    trigger:
      - platform: time
        at: "16:00:00"
    condition:
      - alias: "Salt Level Low"
        condition: numeric_state
        entity_id: sensor.water_softener_salt_level
        above: 400
    action:
      - alias: "Notify"
        service: notify.all
        data_template:
          message: >-
            Water softener salt is low at {{states('sensor.water_softener_salt_level')}} mm.

########################
# Binary Sensors
########################
binary_sensor:

########################
# Cameras
########################
camera:

########################
# Device Trackers
########################
device_tracker:

########################
# Fans
########################
fan:

########################
# Frontend
########################
frontend:

########################
# Groups
########################
group:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Input Select
########################
input_select:

########################
# iOS
########################
ios:

########################
# Light
########################
light:

########################
# Media Player
########################
media_player:

########################
# Plant
########################
plant:

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: filter
    entity_id: sensor.my_water_softener_vl53l0x_sensor
    name: "Water Softener Salt Level"
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 0
      - filter: time_simple_moving_average
        window_size: "6:00"
        precision: 0

  - platform: derivative
    source: sensor.water_softener_salt_level
    name: Water Softener Level (dt=24hrs)
    round: 2
    unit_time: d
    time_window: "24:00:00" # we look at the change over the last day

########################
# Switch
########################
switch:

########################
# Zone
########################
zone:
