################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.alert_car_windows_open_pressure_dropping:
      <<: *customize
      friendly_name: 'Close car window rain alert'
      icon: mdi:window-closed
      
    automation.alert_house_windows_open_pressure_dropping:
      <<: *customize
      friendly_name: 'Close house window rain alert'
      icon: mdi:window-closed
      
    automation.notify_tornado_warning_alert:
      <<: *customize
      friendly_name: Tornado Warning
      icon: mdi:alert

    automation.notify_weather_alert:
      <<: *customize
      friendly_name: Weather Alerts
      icon: mdi:alert-outline

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Groups
    ################################################

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.precip_next_6h:
      <<: *customize
      friendly_name: Precipitation % in next 6 hours
      icon: mdi:weather-pouring
    sensor.dark_sky_temperature:
      <<: *customize
      friendly_name: Outside Temperature
    sensor.dark_sky_precip:
      <<: *customize
      friendly_name: Precipitation Type
      icon: mdi:weather-hail
    sensor.dark_sky_precip_intensity:
      <<: *customize
      friendly_name: Precipitation Intensity
      icon: mdi:weather-pouring
    sensor.dark_sky_cloud_coverage:
      <<: *customize
      friendly_name: Cloud Cover
      icon: mdi:weather-cloudy
    sensor.dark_sky_humidity:
      <<: *customize
      friendly_name: Humidity
      icon: mdi:thermometer-lines

################################################
## Automation
################################################
automation:
  - id: alert_car_windows_open_pressure_dropping
    alias: alert_car_windows_open_pressure_dropping
    trigger: 
    - platform: state
      entity_id: 
        - binary_sensor.pressure_falling_v_rapidly
      from: 'off'
      to: 'on'
      for:
        minutes: 30
    condition:
      condition: and
      conditions:
      - condition: template
        value_template: >-
          {{ states.sensor.dark_sky_precip_probability_1h | int > 50 }}
      - condition: template
        value_template: >-
          {{ not is_state('sensor.season', 'winter') }}
    action: 
    - service: notify.all
      data:
        message: "It will rain soon.  Are your car windows closed?"

  - id: alert_house_windows_open_pressure_dropping
    alias: alert_house_windows_open_pressure_dropping
    trigger: 
    - platform: state
      entity_id: 
        - binary_sensor.pressure_falling
        - binary_sensor.pressure_falling_quickly
        - binary_sensor.pressure_falling_v_rapidly
      from: 'off'
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: group.egress_points
        state: 'on'
      - condition: template
        value_template: >-
          {{ states.sensor.dark_sky_precip_probability_1h | int > 50 }}
      - condition: template
        value_template: >-
          {{ not is_state('sensor.season', 'winter') }}
    action: 
    - service: persistent_notification.create
      data_template:
        title:  "Uh Oh"
        message: >
          ![image]({{ [
          "https://media1.tenor.com/images/2c7e865ab2e4d8084356b9f306011a1d/tenor.gif?itemid=5043009",
          "https://i.imgur.com/0Y9CfFt.gif",
          "https://media0.giphy.com/media/3orieNWYPMcSvsbL9e/giphy.gif",
          "https://media.giphy.com/media/3orieZMmRdBlKk5nY4/giphy.gif",
          "https://media3.giphy.com/media/c1izstLXX1nxu/giphy.gif",
          "https://media2.giphy.com/media/xT5LMq3JLEak50YXHG/giphy.gif",
          "http://s2.quickmeme.com/img/2b/2bacb9823bbf1efd53d3e8f5c9133814bfad9fd59c53c13f793d6fe9292ba1be.jpg"
            ] | random }})
          You left a window open at home. Dumbass.
    - service: notify.ios_wethop
      data_template:
        title: "Open Window"
        message: "It's going to rain and you left a window open at home"
        data:
          attachment: 
            url: >-
              {{ [
              "https://media1.tenor.com/images/2c7e865ab2e4d8084356b9f306011a1d/tenor.gif?itemid=5043009",
              "https://i.imgur.com/0Y9CfFt.gif",
              "https://media0.giphy.com/media/3orieNWYPMcSvsbL9e/giphy.gif",
              "https://media.giphy.com/media/3orieZMmRdBlKk5nY4/giphy.gif",
              "https://media3.giphy.com/media/c1izstLXX1nxu/giphy.gif",
              "https://media2.giphy.com/media/xT5LMq3JLEak50YXHG/giphy.gif",
              ] | random }}
            content-type: gif
            hide-thumbnail: false
            
  - id: notify_tornado_warning_alert
    alias: notify_tornado_warning_alert
    trigger:
    - platform: numeric_state
      entity_id: sensor.pws_alerts
      above: 1
    condition:
      condition: template
      value_template: >-
        {{ ((states.sensor.pws_alerts.attributes.TYPE == "TOR") or
        (states.sensor.pws_alerts.attributes.Description == "Tornado Warning"))
        and (is_state("binary_sensor.bayesian_zeke_home", 'on')) }}
    action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_all
        flash: long
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: switch.turn_on
      data:
        entity_id: group.all_switches

  - id: notify_weather_alert
    alias: notify_weather_alert
    trigger:
    - platform: numeric_state
      entity_id: sensor.pws_alerts
      above: 0
    condition: []
    action:
    - service: notify.all
      data_template:
        message: >-
          {{ states.sensor.pws_alerts.attributes.Description }}

########################
# Binary Sensors
########################
binary_sensor:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
  # - platform: wunderground
  #   api_key: !secret wunderground_api_key
  #   monitored_conditions:
  #     - alerts
  #     - dewpoint_f
  #     - feelslike_f
  #     - heat_index_f
  #     - observation_time
  #     - precip_today_in
  #     - precip_1d_in
  #     - precip_1d
  #     - pressure_mb
  #     - pressure_trend
  #     - relative_humidity
  #     - temp_f
  #     - temp_high_1d_f
  #     - temp_low_1d_f
  #     - weather
  #     - weather_1d
  #     - weather_1n
  #     - weather_2d
  #     - weather_2n
  #     - weather_3d
  #     - weather_3n
  #     - weather_1h
  #     - weather_2h
  #     - weather_3h
  #     - weather_4h
  #     - weather_5h
  #     - weather_6h
  #     - wind_mph
  #     - wind_dir
  #     - wind_1d_mph

  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
      - 1
      - 2
      - 4
    hourly_forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    monitored_conditions:
      #- alerts
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - daily_summary
      - temperature_high
      - temperature_low
      - hourly_summary
   #  - visibility
   #  - ozone

  - platform: template
    sensors:
      precip_next_6h:
        unit_of_measurement: "%"
        value_template: >-
          {{ [ (states.sensor.dark_sky_precip_probability_1h|float),
               (states.sensor.dark_sky_precip_probability_2h|float),
               (states.sensor.dark_sky_precip_probability_3h|float),
               (states.sensor.dark_sky_precip_probability_4h|float),
               (states.sensor.dark_sky_precip_probability_5h|float),
               (states.sensor.dark_sky_precip_probability_6h|float), ] |max }}
