################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'weather'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################
    automation.notify_tornado_warning_alert:
      <<: *customize
      friendly_name: Tornado Warning

    automation.notify_weather_alert:
      <<: *customize
      friendly_name: Weather Alerts

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Groups
    ################################################
    group.weather_alert_card:
      <<: *customize
      friendly_name: Weather Alerts
    group.weather_current_conditions_card:
      <<: *customize
      friendly_name: Current Conditions
    group.weather_daily_forecast_card:
      <<: *customize
      friendly_name: Four-day Forecast
    group.weather_hourly_forecast_card:
      <<: *customize
      friendly_name: Four-hour Forecast

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################

################################################
## Automation
################################################
automation:
  - id: notify_tornado_warning_alert
    alias: notify_tornado_warning_alert
    trigger:
    - platform: state
      entity_id: sensor.pws_alerts
      above: 1
    condition:
      condition: data_template
      value_template: >-
        {{ ((states.sensor.pws_alerts.attributes.TYPE == "TOR") or
        (states.sensor.pws_alerts.attributes.Description == "Tornado Warning"))
        and (is_state("binary_sensor.bayesian_zeke_home", "on")) }}
    action:
    - service: light.turn_on
      data:
        entity_id: light.all_living_room
        flash: long
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: switch.turn_on
      data:
        entity_id: group.all_switches

  - id: notify_weather_alert
    alias: notify_weather_alert
    trigger:
    - platform: state
      entity_id: sensor.pws_alerts
      above: 1
    condition: []
    action:
    - service: notify.all
      data_template:
        message: >-
          {{ states.sensor.pws_alerts.attributes.Description }}



########################
# Binary Sensors
########################
binary_sensor:

########################
# Input Booleans
########################
input_boolean:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  weather_daily_forecast_card:
    entities:
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
  weather_hourly_forecast_card:
    entities:
      - sensor.pws_weather
      - sensor.pws_weather_1h
      - sensor.pws_weather_2h
      - sensor.pws_weather_3h
      - sensor.pws_weather_4h
  weather_alert_card:
    entities:
      - sensor.pws_alerts
  weather_current_conditions_card:
    entities:
      - sun.sun
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_feelslike_f
      - sensor.pws_dewpoint_f
      - sensor.pws_relative_humidity
      - sensor.pws_heat_index_f
      - sensor.pws_pressure_trend
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip
      - sensor.pws_observation_time
########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

################################################
## Sensors
################################################
sensor:
