################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'workday'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.arrive_at_work:
      <<: *customize
      friendly_name: "Arrive at work"

    automation.vacuum_while_working:
      <<: *customize
      friendly_name: "Vacuum while at work"
      icon: mdi:robot-vacuum

    automation.wake_up_lights:
      <<: *customize
      friendly_name: "Wake up lights"
      icon: mdi:briefcase

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Input Datetime
    ################################################
    input_datetime.next_work_meeting:
      <<: *customize
      friendly_name: "Next work meeting"
      icon: mdi:briefcase

################################################
## Automation
################################################
automation:
  - id: arrive_at_work
    alias: arrive_at_work
    trigger:
      # - platform: state
      #   entity_id: device_tracker.bayesian_zeke_home
      #   to: 'Work'
      - platform: zone
        entity_id: device_tracker.bayesian_zeke_home
        event: enter
        zone: zone.work
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    action:
      - service: climate.set_away_mode
        data:
          away_mode: true
          entity_id: all
      - service: notify.all
        data:
          message: 'Arriving at work. Setting Nest Away.'

  - id: vacuum_while_working
    alias: vacuum_while_working
    trigger:
      # - platform: state
      #   entity_id: device_tracker.bayesian_zeke_home
      #   to: 'Work'
      - entity_id: device_tracker.bayesian_zeke_home
        event: enter
        platform: zone
        zone: zone.work
    condition: []
    action:
      - service: vacuum.start

  - id: wake_up_lights
    alias: wake_up_lights
    trigger:
      - platform: template
        value_template: "{{states.sensor.time.state == states.input_datetime.next_work_meeting.state[0:5]}}"
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: state
        entity_id: device_tracker.bayesian_zeke_home
        state: 'home'
        ## TODO Need to add condition that checks that I'm still in bed
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom
          transition: 300
          brightness_pct: 100

########################
# Binary Sensors
########################
binary_sensor:
  - platform: workday
    country: US
    province: !secret home_state

########################
# Input Booleans
########################
input_boolean:
  morning_routine:

################################################
## Input Datetime
################################################
input_datetime:
  next_work_meeting:
    has_date: false
    has_time: true

################################################
## Sensor
################################################
