################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'workday'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.arrive_at_work:
      <<: *customize
      friendly_name: "Arrive at work"

    automation.vacuum_while_working:
      <<: *customize
      friendly_name: "Vacuum while at work"
      icon: mdi:robot-vacuum
      

    ################################################
    ## Binary Sensors
    ################################################

################################################
## Automation
################################################
automation:
  - id: arrive_at_work
    alias: arrive_at_work
    trigger:
      - platform: zone
        entity_id: device_tracker.bayesian_zeke_home
        event: enter
        zone: zone.work
    condition: []
    action:
      - service: climate.set_away_mode
        data:
          away_mode: true
          entity_id: climate.hallway_glycol
#      - service: notify.all
#        data:
#          message: 'Arriving at work. Setting Nest Away.'

  - id: 'vacuum_while_working'
    alias: vacuum_while_working
    trigger:
      - entity_id: device_tracker.bayesian_zeke_home
        event: enter
        platform: zone
        zone: zone.work
    condition: []
    action:
      - service: vacuum.turn_on

########################
# Binary Sensors
########################
binary_sensor:
  - platform: workday
    country: US
    state: !secret home_state

################################################
## Sensor
################################################
