################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "workday"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.arrive_at_work:
      <<: *customize
      friendly_name: "Arrive at work"

    automation.vacuum_while_working:
      <<: *customize
      friendly_name: "Vacuum while at work"
      icon: mdi:robot-vacuum

    automation.turn_off_office_lamp_when_work_tp_camera_active:
      <<: *customize
      friendly_name: "Turn off Rear Office Lamp when Camera On"

    automation.turn_on_office_lamp_when_work_tp_camera_inactive:
      <<: *customize
      friendly_name: "Turn on Rear Office Lamp when Camera Off"

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Input Datetime
    ################################################

################################################
## Automation
################################################
automation:
  - id: arrive_at_work
    alias: arrive_at_work
    trigger:
      - trigger: zone
        entity_id: device_tracker.bayesian_zeke_home
        event: enter
        # zone: zone.work
        zone: zone.rochester
    condition:
      condition: state
      entity_id: "binary_sensor.workday_sensor"
      state: "on"
    action:
      - action: climate.set_preset_mode
        enabled: false
        entity_id: climate.my_ecobee
        data:
          preset_mode: "away_indefinitely"
      - action: notify.all
        data:
          data:
            url: "/ryan-new-mushroom/climate"
          message: "Arriving at work. Setting Ecobee Away."

  - id: turn_off_morning_routine
    alias: turn_off_morning_routine
    trigger:
      - trigger: time
        at: "00:00:01"
    action:
      - action: input_boolean.turn_off
        data:
          entity_id: input_boolean.morning_routine

  - id: turn_off_office_lamp_when_work_tp_camera_active
    alias: turn_off_office_lamp_when_work_tp_camera_active
    trigger:
      - trigger: state
        entity_id: binary_sensor.ryans_work_macbook_pro_m1_camera_in_use
        to: "on"
    action:
      - action: retry.actions
        data:
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.office_ceiling
          initial_grace_period: 5
          expected_state:
            - "off"
      - action: media_player.media_pause
        data:
          entity_id:
            - media_player.spotify_ryan_claussen
            - media_player.office_sonos
      - delay:
          seconds: 5
      - action: light.turn_off
        target:
          entity_id: light.office_ceiling

  - id: turn_on_office_lamp_when_work_tp_camera_inactive
    alias: turn_on_office_lamp_when_work_tp_camera_inactive
    trigger:
      - trigger: state
        entity_id: binary_sensor.ryans_work_macbook_pro_m1_camera_in_use
        to: "off"
    action:
      - action: light.turn_on
        data:
          entity_id: light.office_ceiling

  - id: vacuum_while_working
    alias: vacuum_while_working
    trigger:
      # - platform: state
      #   entity_id: device_tracker.bayesian_zeke_home
      #   to: 'Work'
      - entity_id: device_tracker.bayesian_zeke_home
        event: enter
        trigger: zone
        # zone: zone.work
        zone: zone.rochester
      # - platform: event
      #   event_type: ios.notification_action_fired
      #   event_data:
      #     actionName: VACUUM_HOUSE
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: VACUUM_HOUSE
    condition: []
    action:
      # Revert back when batteries are all reset/new
      # including main level vacuum
      # - alias: Start Vacuums
      #   action: vacuum.start
      #   target:
      #     entity_id: all
      - action: mqtt.publish
        data:
          topic: valetudo/upstairs-vacuum/MapSegmentationCapability/clean/set
          payload: >-
            {% set segment_id = now().weekday() + 1 %}
            {"segment_ids": ["{{segment_id}}"],"iterations": 4,"customOrder": true}

########################
# Binary Sensors
########################
binary_sensor:
  # Moved to UI configuration
  # - platform: workday
  #   country: US
  #   province: !secret home_state

########################
# Input Booleans
########################
input_boolean:
  morning_routine:

################################################
## Input Datetime
################################################
input_datetime:

################################################
## Sensor
################################################
sensor:
  - platform: time_date
    display_options:
      - time
