################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "workday"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.arrive_at_work:
      <<: *customize
      friendly_name: "Arrive at work"

    automation.vacuum_while_working:
      <<: *customize
      friendly_name: "Vacuum while at work"
      icon: mdi:robot-vacuum

    ################################################
    ## Binary Sensors
    ################################################

    ################################################
    ## Input Datetime
    ################################################

################################################
## Automation
################################################
automation:
  # Implemented in Schedy
  # - id: arrive_at_work
  #   alias: arrive_at_work
  #   trigger:
  #     # - platform: state
  #     #   entity_id: device_tracker.bayesian_zeke_home
  #     #   to: 'Work'
  #     - platform: zone
  #       entity_id: device_tracker.bayesian_zeke_home
  #       event: enter
  #       zone: zone.work
  #   condition:
  #     condition: state
  #     entity_id: 'binary_sensor.workday_sensor'
  #     state: 'on'
  #   action:
  #     - service: climate.set_preset_mode
  #       data:
  #         preset_mode: 'Away and Eco'
  #         entity_id: all
  #     - service: notify.all
  #       data:
  #         message: 'Arriving at work. Setting Nest Away.'

  - id: turn_off_morning_routine
    alias: turn_off_morning_routine
    trigger:
      - platform: time
        at: "00:00:01"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.morning_routine

  - id: vacuum_while_working
    alias: vacuum_while_working
    trigger:
      # - platform: state
      #   entity_id: device_tracker.bayesian_zeke_home
      #   to: 'Work'
      - entity_id: device_tracker.bayesian_zeke_home
        event: enter
        platform: zone
        zone: zone.work
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: VACUUM_HOUSE
    condition: []
    action:
      - service: vacuum.start
        data:
          entity_id: all

########################
# Binary Sensors
########################
binary_sensor:
  - platform: workday
    country: US
    province: !secret home_state

########################
# Input Booleans
########################
input_boolean:
  morning_routine:

################################################
## Input Datetime
################################################
input_datetime:

################################################
## Sensor
################################################
sensor:
  - platform: time_date
    display_options:
      - time
