################################################################
## Packages / Zigbee
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "zigbee"

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automations
    ################################################

    ################################################
    ## Binary Sensors
    ################################################
    binary_sensor.basement_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Basement Door"

    binary_sensor.se_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South East Basement Window"

    binary_sensor.sw_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South West Basement Window"

    binary_sensor.deck_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Deck Door"

    binary_sensor.downstairs_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Downstairs Motion"

    binary_sensor.ene_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "East North East Window"

    binary_sensor.ese_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "East South East Window"

    binary_sensor.front_door_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Front Door"

    binary_sensor.hallway_motion:
      <<: *customize
      device_class: motion
      friendly_name: "Hallway Motion"

    binary_sensor.kitchen_button:
      <<: *customize
      friendly_name: "Kitchen Button push"

    binary_sensor.living_room_button_hold:
      <<: *customize
      friendly_name: "Living Room Button hold"

    binary_sensor.living_room_button_push:
      <<: *customize
      friendly_name: "Living Room Button push"

    binary_sensor.master_bed_occupancy:
      <<: *customize
      device_class: occupancy
      friendly_name: "Master Bed Occupancy"
      icon: mdi:bed-empty

    binary_sensor.owner_suite_occupancy:
      <<: *customize
      device_class: motion
      friendly_name: "Master Bedroom Occupancy"

    binary_sensor.living_room_motion_sensor:
      <<: *customize
      device_class: motion
      friendly_name: "Living Room Motion"

    binary_sensor.nne_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "North North East Window"

    binary_sensor.north_kitchen_sink_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Kitchen Sink Window"

    binary_sensor.north_master_bedroom_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Master Bedroom Window"

    binary_sensor.nw_basement_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "North West Basement Window"

    binary_sensor.office_button:
      <<: *customize
      friendly_name: "Office Button push"

    binary_sensor.office_north_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "Office Window"

    binary_sensor.sse_window_contact:
      <<: *customize
      device_class: opening
      friendly_name: "South South East Living Room Window"

    ################################################
    ## Device Trackers
    ################################################

    ################################################
    ## Groups
    ################################################
    group.egress_points:
      <<: *customize
      friendly_name: Sensors on Doors and Windows

    ################################################
    ## Input Boolean
    ################################################

    ################################################
    ## Input Numbers
    ################################################

    ################################################
    ## Proximity
    ################################################

    ################################################
    ## Scripts
    ################################################

    ################################################
    ## Sensors
    ################################################
    sensor.arrival_sensor_battery:
      <<: *customize
      friendly_name: "Arrival Sensor Battery"

    sensor.basement_door_battery:
      <<: *customize
      friendly_name: "Basement Door Battery"

    sensor.deck_door_battery:
      <<: *customize
      friendly_name: "Deck Door Battery"
      device_class: battery

    sensor.downstairs_illumination:
      <<: *customize
      friendly_name: "Downstairs Illumination"
      device_class: illuminance

    sensor.downstairs_motion_battery:
      <<: *customize
      friendly_name: "Downstairs Motion Battery"
      device_class: battery

    sensor.ene_window_battery:
      <<: *customize
      friendly_name: "East North East Window Battery"
      device_class: battery

    sensor.ese_window_battery:
      <<: *customize
      friendly_name: "East South East Window Battery"
      device_class: battery

    sensor.front_door_battery:
      <<: *customize
      friendly_name: "Front Door Battery"
      device_class: battery

    sensor.guest_room_battery:
      <<: *customize
      friendly_name: "Guest Room Battery"
      device_class: battery

    sensor.guest_room_button_battery:
      <<: *customize
      friendly_name: "Guest Room Button Battery"
      device_class: battery

    sensor.guest_room_humidity:
      <<: *customize
      friendly_name: "Guest Room Humidity"
      device_class: humidity

    sensor.guest_room_pressure:
      <<: *customize
      friendly_name: "Guest Room Pressure"
      icon: mdi:gauge

    sensor.guest_room_temperature:
      <<: *customize
      friendly_name: "Guest Room Temperature"
      device_class: temperature

    sensor.hallway_motion_battery:
      <<: *customize
      friendly_name: "Hallway Motion Sensor Battery"
      device_class: battery

    sensor.hallway_illumination:
      <<: *customize
      friendly_name: "Hallway Illumination"
      device_class: illuminance

    sensor.kitchen_button_battery:
      <<: *customize
      device_class: battery
      friendly_name: "Kitchen Button Battery"

    sensor.kitchen_temperature:
      <<: *customize
      friendly_name: "Kitchen Temperature"
      device_class: temperature

    sensor.kitchen_humidity:
      <<: *customize
      friendly_name: "Kitchen Humidity"
      device_class: humidity

    sensor.kitchen_pressure:
      <<: *customize
      friendly_name: "Kitchen Pressure"
      icon: mdi:gauge

    sensor.kitchen_battery:
      <<: *customize
      friendly_name: "Kitchen Battery"
      device_class: battery

    sensor.living_room_battery:
      <<: *customize
      friendly_name: "Living Room Battery"
      device_class: battery

    sensor.living_room_button_battery:
      <<: *customize
      friendly_name: "Living Room Button Battery"
      device_class: battery

    sensor.living_room_humidity:
      <<: *customize
      friendly_name: "Living Room Humidity"
      device_class: humidity

    sensor.living_room_pressure:
      <<: *customize
      friendly_name: "Living Room Pressure"
      icon: mdi:gauge

    sensor.living_room_temperature:
      <<: *customize
      friendly_name: "Living Room Temperature"
      device_class: temperature

    sensor.master_bed_occupancy_battery:
      <<: *customize
      friendly_name: "Master Bed Occupancy Sensor Battery"
      device_class: battery

    #    sensor.master_bedroom_battery:
    #      <<: *customize
    #      friendly_name: "Master Bedroom Battery"
    #      device_class: battery

    sensor.owner_suite_tph_humidity:
      <<: *customize
      friendly_name: "Master Bedroom Humidity"
      device_class: humidity

    sensor.master_bedroom_illumination:
      <<: *customize
      friendly_name: "Master Bedroom Illumination"
      device_class: illuminance

    sensor.master_bedroom_motion_battery:
      <<: *customize
      friendly_name: "Master Bedroom Motion Sensor Battery"
      device_class: battery

    sensor.owner_suite_tph_pressure:
      <<: *customize
      friendly_name: "Master Bedroom Pressure"
      icon: mdi:gauge

    sensor.owner_suite_tph_temperature:
      <<: *customize
      friendly_name: "Master Bedroom Temperature"
      device_class: temperature

    sensor.motion_sensor_battery:
      <<: *customize
      friendly_name: "Living Room Motion Sensor Battery"
      device_class: battery

    sensor.north_kitchen_sink_window_battery:
      <<: *customize
      friendly_name: "North Kitchen Sink Window Battery"
      device_class: battery

    sensor.north_master_bedroom_window_battery:
      <<: *customize
      friendly_name: "North Master Bedroom Window Battery"
      device_class: battery

    sensor.nne_window_battery:
      <<: *customize
      friendly_name: "North North East Window Battery"
      device_class: battery

    sensor.nw_basement_window_battery:
      <<: *customize
      friendly_name: "North West Basement Window Battery"
      device_class: battery

    #    sensor.office_button_battery:
    #      <<: *customize
    #      device_class: battery
    #      friendly_name: "Office Button Battery"

    sensor.office_motion_battery:
      <<: *customize
      friendly_name: "Office Motion Sensor Battery"
      device_class: battery

    sensor.office_illumination:
      <<: *customize
      friendly_name: "Office Illumination"
      device_class: illuminance

    sensor.office_north_window_battery:
      <<: *customize
      friendly_name: "Office North Window Battery"
      device_class: battery

    sensor.se_basement_window_battery:
      <<: *customize
      friendly_name: "South East Basement Window Battery"
      device_class: battery

    sensor.sse_window_battery:
      <<: *customize
      friendly_name: "South South East Window Battery"
      device_class: battery

    sensor.sw_basement_window_battery:
      <<: *customize
      friendly_name: "South West Basement Window Battery"
      device_class: battery

    ################################################
    ## Switches
    ################################################
    switch.bathroom_light_fan_switch:
      <<: *customize
      friendly_name: "Bathroom Light and Fan"
      icon: mdi:shower

    switch.humidifier:
      <<: *customize
      friendly_name: Humidifier
      icon: mdi:air-humidifier
    ################################################
    ## Thermostats
    ################################################

    ################################################
    ## Zone
    ################################################

################################################
## Automation
################################################
automation:
  - alias: in_bed_on
    id: in_bed_on
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bed_occupancy
        to: "on"
    # condition:
    #   condition: state
    #   entity_id: binary_sensor.master_bed_occupancy
    #   state: "on"
    #   for:
    #     seconds: 5
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.master_bed_occupancy
      - service: cover.close_cover
        entity_id:
          - cover.owner_suite_blinds
          - cover.garage_door

  - alias: in_bed_off
    id: in_bed_off
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bed_occupancy
        to: "off"
    # condition:
    #   condition: state
    #   entity_id: binary_sensor.master_bed_occupancy
    #   state: "off"
    #   for:
    #     seconds: 5
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.master_bed_occupancy

  - id: mail_delivered
    alias: mail_delivered
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox_contact
        from: "off"
        to: "on"
    condition:
      - condition: and
        conditions:
          - alias: "Mailbox empty"
            condition: state
            entity_id: input_boolean.mail_delivered
            state: "off"
          - alias: "On a trip"
            condition: state
            entity_id: input_boolean.trip
            state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mail_delivered
      - service: notify.all
        data:
          message: >-
            Mail delivered.

  - id: reset_mail_delivery
    alias: reset_mail_delivery
    trigger:
      - platform: time
        at: "01:00:00"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mail_delivered

  - id: turn_on_guest_bedroom_fan_light_zwave_switch
    alias: turn_on_guest_bedroom_fan_light_zwave_switch
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          # The data on this page has the right idea but the events are wrong in OZW Beta
          # Use the event recorder for "ozw.scene_activated" to see what actually are the values triggered
          # https://www.home-assistant.io/docs/z-wave/device-specific/#inovelli-scene-capable-onoff-and-dimmer-wall-switches
          node_id: 13 # Switch in guest room
          scene_id: 2 # Top/on button press
          scene_value_id: 1 # pressed once
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.guest_ceiling

  - id: turn_on_guest_bedroom_side_lamps_zwave_switch
    alias: turn_on_guest_bedroom_fan_lamps_zwave_switch
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          # The data on this page has the right idea but the events are wrong in OZW Beta
          # Use the event recorder for "ozw.scene_activated" to see what actually are the values triggered
          # https://www.home-assistant.io/docs/z-wave/device-specific/#inovelli-scene-capable-onoff-and-dimmer-wall-switches
          node_id: 13 # Switch in guest room
          scene_id: 2 # Top/on button press
          scene_value_id: 4 # pressed twice
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.guest_side_lamps

  - id: turn_off_guest_bedroom_side_lamps_zwave_switch
    alias: turn_off_guest_bedroom_side_lamps_zwave_switch
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          # The data on this page has the right idea but the events are wrong in OZW Beta
          # Use the event recorder for "ozw.scene_activated" to see what actually are the values triggered
          # https://www.home-assistant.io/docs/z-wave/device-specific/#inovelli-scene-capable-onoff-and-dimmer-wall-switches
          node_id: 13 # Switch in guest room
          scene_id: 1 # Bottom/off button press
          scene_value_id: 4 # pressed twice
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.guest_side_lamps

  - id: turn_off_guest_bedroom_fan_light_zwave_switch
    alias: turn_off_guest_bedroom_fan_light_zwave_switch
    trigger:
      - platform: event
        event_type: ozw.scene_activated
        event_data:
          # The data on this page has the right idea but the events are wrong in OZW Beta
          # Use the event recorder for "ozw.scene_activated" to see what actually are the values triggered
          # https://www.home-assistant.io/docs/z-wave/device-specific/#inovelli-scene-capable-onoff-and-dimmer-wall-switches
          node_id: 13 # Switch in guest room
          scene_id: 1 # Bottom/off button press
          scene_value_id: 1 # pressed once
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.guest_ceiling
          # - alias: xiaomi_mqtt_button_pressed
  #   id: xiaomi_mqtt_button_pressed
  #   trigger:
  #   - platform: state
  #     entity_id:
  #       - binary_sensor.living_room_button
  #       - binary_sensor.guest_room_button
  #   action:
  #   - service: notify.all
  #     data_template:
  #       message: >-
  #         {{ trigger.entity_id }}

########################
# Binary Sensors
########################
binary_sensor:
  - platform: template
    sensors:
      master_bed_occupancy:
        device_class: occupancy
        value_template: >-
          {{ states('sensor.average_bed_load')| int(0) > 40 }}
        # value_template: >-
        #   {{
        #     states('sensor.bed_load_cell_1') | int(0) > 15
        #       or
        #     states('sensor.bed_load_cell_2') | int(0) > 15
        #   }}

########################
# Device Trackers
########################
device_tracker:

########################
# Input Booleans
########################
input_boolean:
  master_bed_occupancy:
  mail_delivered:

########################
# Input Numbers
########################
input_number:

########################
# Groups
########################
group:
  egress_points:
    entities:
      # The doors
      - binary_sensor.den_doors_contact
      - binary_sensor.kitchen_deck_contact
      - binary_sensor.main_foyer_front_door_contact
      - binary_sensor.tiki_room_deck_contact
      - binary_sensor.hall_garage_entry_contact

########################
# Proximity
########################
proximity:

########################
# Scenes
########################
scene:

########################
# Scripts
########################
script:

########################
# Sensor
########################
sensor:
  - platform: template
    sensors:
      average_bed_load:
        friendly_name: "Average Bed Load"
        unit_of_measurement: "kg"
        value_template: >-
          {{ ((states('sensor.bed_load_cell_1') | int(0) )+(states('sensor.bed_load_cell_2') | int(0) ))/2.0 }}

########################
# Zone
########################
zone:
